// A single learning workspace reuses the original attempts, records and calendar.
const guidedParent={sessions:null,loading:false,error:'',pending:null,busy:false,editor:null,workspace:null,materialReturn:null,planEditor:null,conflict:null,notice:''};
const guidedStateLabel=s=>({draft:'未分享',active:'可尝试',paused:'已暂停',closed:'本次已结束',skipped:'本次跳过'}[s]||s);
const guidedPlanFields={goal:'这次想学会什么',success_criteria:'怎样看出有进展',start:'怎么开始',ask:'可以怎么问',help:'卡住时怎么帮',stop:'什么时候先停',retry:'下次怎么再试'};
const guidedSession=id=>guidedParent.sessions?.find(s=>s.id===id);
const guidedLatestRecord=s=>[...s.events].reverse().find(e=>e.kind==='attempt'&&e.record_id)?.record_id||s.related_record_id||null;
const guidedIsDrafting=()=>guidedParent.pending?.body.action==='guide_draft';
function guidedOriginals(items){return (items||[]).map(a=>`<a href="${esc(endpoint('/upload/'+a.id))}" target="_blank" rel="noopener noreferrer">${esc(a.name||'原件')}</a>`).join(' · ')}
function guidedDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?'时间待核对':new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}
function guidedEvents(s){return s.events.filter(e=>!['material','guide_plan','guide_draft'].includes(e.kind)).map(e=>`<article class="record"><p class="small muted">${esc(({attempt:e.attempt_kind==='first'?'首次尝试':'再次表达',hint:'系统提示',pause:'暂停',resume:'继续',skip:'跳过',finish:'结束本次'}[e.kind]||'安排调整'))} · ${esc(({child:'孩子',parent:'家长',model:'系统'}[e.actor]||e.actor))} · ${esc(guidedDate(e.created))}</p>${e.kind==='hint'?`<p class="source">${esc(e.status==='ready'?[e.hint,e.question].filter(Boolean).join('\n'):e.status==='stale'?'这条提示已失效，没有继续引导。':e.message||'提示尚未就绪')}</p>`:`<p class="source">${esc(e.text||e.message||'')}</p>`}${e.assistance?`<p class="small">实际帮助：${esc(e.assistance)}</p>`:''}${guidedOriginals(e.attachments)}${e.uncertainties?.length?`<details><summary>提示的局限</summary><p class="source">${e.uncertainties.map(esc).join('；')}</p></details>`:''}</article>`).join('')||(s.shared?'<p class="muted">已经分享，等孩子留下自己的想法。</p>':'<p class="muted">还没有孩子自己的尝试。先把任务分享给孩子。</p>')}
async function guidedRead(){if(guidedParent.loading||guidedParent.busy)return;guidedParent.loading=true;document.querySelectorAll('[data-guided-refresh]').forEach(b=>b.disabled=true);try{const result=await guidedFetch('state',{});guidedParent.sessions=result.sessions;guidedParent.error='';if(guidedParent.workspace&&$('#guidedDialog')?.open&&!guidedParent.planEditor)guidedReview(guidedParent.workspace)}catch(e){guidedParent.error=e.message}finally{guidedParent.loading=false;if(page==='learning')render()}}
async function guidedFetch(action,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),body.action==='guide_draft'?100000:25000);try{const r=await apiFetch('/api/guided/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':data.token},body:JSON.stringify(body),signal:controller.signal}),result=await r.json();if(!r.ok){const e=Error(result.error||'暂时无法保存');e.status=r.status;e.code=result.code;throw e}if(result.ok!==true||!Array.isArray(result.sessions))throw Error('保存回执暂时无法核对');return result}catch(e){if(e.name==='AbortError')throw Error('等待超时，原输入仍保留');throw e}finally{clearTimeout(timer)}}
function guidedHTML(){return `<section class="card guided-entry"><div class="toolbar"><h2>一起学习</h2><button class="primary" data-guided-create>新建学习任务</button><button data-guided-refresh>更新尝试</button></div><p class="muted">定一个小目标，在同一处准备、看尝试、记反馈。</p>${guidedParent.error?`<p role="alert">${esc(guidedParent.error)} <button data-guided-refresh>重试读取</button></p>`:''}${guidedParent.pending?'<p class="note">上次请求结果待核对。<button data-guided-retry>用原内容重试</button></p>':''}${(guidedParent.sessions||[]).filter(s=>!child||data.children.find(c=>c.id===s.child_id)?.name===child).map(s=>`<article class="task" data-guided-session="${esc(s.id)}"><span class="chip">${esc(data.children.find(c=>c.id===s.child_id)?.name||'归属待核对')} · ${esc(guidedStateLabel(s.state))}${s.shared?' · 已分享':''}</span><h3>${esc(s.title)}</h3>${s.plan?.goal?`<p>${esc(s.plan.goal)}</p>`:''}<div class="toolbar"><button data-guided-review="${esc(s.id)}">${s.events.some(e=>e.kind==='attempt')?'看尝试与提示':'打开学习任务'}</button>${s.state==='draft'?`<button data-guided-edit="${esc(s.id)}">继续准备</button>`:''}</div></article>`).join('')||'<p class="muted">可以直接安排一次学习，也可以从已有记录开始。</p>'}</section>`}
function guidedDialog(){let d=$('#guidedDialog');if(!d){d=document.createElement('dialog');d.id='guidedDialog';d.setAttribute('aria-label','一起学习');document.body.append(d);d.addEventListener('cancel',e=>{if(guidedParent.busy&&!guidedIsDrafting())e.preventDefault()})}return d}
function guidedShow(d){if(!d.open)d.showModal()}
function guidedOpen(recordID=null,session=null,preset={}){
 if(guidedParent.busy||guidedParent.pending){toast('请先核对上次保存结果');return}
 const r=recordID?data.records.find(r=>r.id===Number(recordID)):null;
 if(recordID&&!r){toast('关联记录暂时无法读取，请刷新核对');return}
 const c=data.children.find(c=>c.name===(r?.child||child))||data.children[0];if(!session&&!c)return;
 const d=guidedDialog(),previous=guidedParent.workspace;d.classList.remove('guided-workspace');
 const remembered=guidedParent.editor&&guidedParent.editor.related_record_id===(r?.id||null)&&!Object.keys(preset).length?guidedParent.editor:null;
 const v=session?{...session,question_attachments:session.question_attachments.map(a=>a.id)}:remembered||{child_id:c.id,version:0,title:r?.title||'',subject:r?.subject||'',question_text:'',question_attachments:[],reference_text:'',reference_checked:false,related_record_id:r?.id||null,practice_relation:'',shared:false,...preset};
 guidedParent.editor=v;guidedParent.materialReturn=previous;guidedParent.workspace=null;
 d.innerHTML=`<form id="guidedMaterialForm"><h2>${session?'继续准备学习任务':'新建学习任务'}</h2><div class="formrow"><label>孩子<select name="child_id" ${session||r?'disabled':''}>${data.children.map(c=>`<option value="${esc(c.id)}" ${v.child_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>科目 · 可选<input name="subject" maxlength="80" value="${esc(v.subject)}"></label></div><label>这次练什么<input name="title" required maxlength="200" value="${esc(v.title)}" placeholder="例如：说清楚分数表示什么"></label>${v.related_record_id?`<label>与关联记录的材料关系<select name="practice_relation"><option value="">还不确定</option>${['同一道题或同一片段','相近的新题或新片段','范围或难度不同'].map(x=>`<option ${v.practice_relation===x?'selected':''}>${x}</option>`).join('')}</select></label>`:''}<label>题目或任务说明 · 可稍后补充<textarea name="question_text" rows="3" maxlength="4000" placeholder="只写孩子这次需要看到的内容。">${esc(v.question_text)}</textarea></label><details class="ask-citation"><summary>选择孩子可见的原件 · 最多 3 份</summary><p class="small">原记录原件不会自动分享，请只勾选这次的题目。</p>${(data.uploads||[]).map(a=>`<label class="child-share-option"><input type="checkbox" name="question_attachments" value="${esc(a.id)}" ${v.question_attachments.includes(a.id)?'checked':''}><span>${esc(a.name)}</span></label>`).join('')||'<p>暂无上传原件，可以填写题目文字。</p>'}</details><details class="ask-citation" id="guidedReferences"><summary>参考与答案 · 可稍后补充</summary><label>家长参考<textarea name="reference_text" rows="4" maxlength="4000" placeholder="核对过的解法与依据；不确定的地方请写明。">${esc(v.reference_text)}</textarea></label><p class="small muted">仅供家长与本家模型核对，不直接展示给孩子。</p><label class="child-share-option"><input name="reference_checked" type="checkbox" ${v.reference_checked?'checked':''}><span>我已核对题目与参考</span></label></details><label class="child-share-option"><input name="shared" type="checkbox" ${v.shared?'checked':''}><span>把这个任务分享给孩子</span></label><p id="guidedMaterialError" class="error" role="alert"></p><div class="actions"><button type="button" data-guided-dismiss>稍后继续</button><button class="primary" type="submit">保存安排</button></div></form>`;
 const f=$('#guidedMaterialForm'),remember=()=>{Object.assign(v,{child_id:f.elements.child_id.value,subject:f.elements.subject.value,title:f.elements.title.value,practice_relation:f.elements.practice_relation?.value||'',question_text:f.elements.question_text.value,question_attachments:[...f.querySelectorAll('[name=question_attachments]:checked')].map(x=>x.value),reference_text:f.elements.reference_text.value,reference_checked:f.elements.reference_checked.checked,shared:f.elements.shared.checked})};
 f.addEventListener('input',remember);f.addEventListener('change',remember);f.onsubmit=e=>{e.preventDefault();remember();if(v.question_attachments.length>3){$('#guidedMaterialError').textContent='这次最多选择 3 份题目原件。';return}const body=Object.fromEntries(['id','version','child_id','title','subject','question_text','question_attachments','reference_text','reference_checked','related_record_id','practice_relation','shared'].filter(k=>v[k]!==undefined).map(k=>[k,v[k]]));guidedSave('material',body)};guidedShow(d);
}
function guidedObservations(s){
 const ids=new Set([s.related_record_id,...s.events.filter(e=>e.kind==='attempt').map(e=>e.record_id)].filter(Boolean)),name=data.children.find(c=>c.id===s.child_id)?.name;
 const rows=(data.records||[]).filter(r=>r.child===name&&ids.has(r.related_record_id)&&r.followup_kind==='补充观察'&&!String(r.source||'').startsWith('短引导尝试:'));
 return rows.map(r=>`<article class="record"><p class="small muted">${esc(r.day)} · ${esc(r.source)}</p><p class="source">${esc(r.note||r.title)}</p>${recordUploads(r)}</article>`).join('')||'<p class="muted">还没有针对这次学习补充的观察。</p>';
}
async function guidedWithRecord(s,action){const id=s&&guidedLatestRecord(s);if(!id)return;if(!(data.records||[]).some(r=>r.id===id)){try{await load()}catch{toast('尝试已保存，原记录暂时无法读取，请刷新后重试');return}}if(guidedParent.workspace!==s.id||!$('#guidedDialog')?.open)return;if(!(data.records||[]).some(r=>r.id===id)){toast('关联原记录暂时无法核对');return}action(id)}
function guidedPlanDisplay(s){const p=s.plan;return p?`<p class="source"><strong>${esc(p.goal)}</strong></p><p class="source">观察进展：${esc(p.success_criteria)}</p>${p.share_goal?'<p class="small muted">目标与观察点已向孩子开放。</p>':''}<div class="guided-plan-steps">${Object.entries(guidedPlanFields).filter(([k])=>!['goal','success_criteria'].includes(k)&&p[k]).map(([k,label])=>`<div class="guided-plan-step"><strong>${label}</strong><p class="source">${esc(p[k])}</p></div>`).join('')||'<p class="muted">可以按实际需要补充引导方法。</p>'}</div>`:'<p class="muted">先写清这次想学什么、怎样看出有进展；引导方法可以一起准备。</p>'}
function guidedDraftCaption(draft){const observations=Number.isInteger(draft?.observation_count)&&draft.observation_count>0?draft.observation_count:0,older=Number.isInteger(draft?.older_observations_count)&&draft.older_observations_count>0?draft.older_observations_count:0;if(observations)return `已参考 ${observations} 条家长观察${older?`，另有 ${older} 条较早反馈未纳入`:''}，核对后保存。`;if(older)return `另有 ${older} 条较早反馈未纳入，核对后保存。`;return '未确认草稿，核对后保存。'}
function guidedPlanForm(s){const editor=guidedParent.planEditor;if(!editor||editor.id!==s.id||editor.open===false)return '';const v=editor.plan,draft=s.plan_draft,usingDraft=editor.based_on_draft_id&&draft?.id===editor.based_on_draft_id;
 return `<form id="guidedPlanForm"><p class="small muted">${usingDraft?guidedDraftCaption(draft):'可直接手写目标与观察点，其余按需填写。'}</p><label>${guidedPlanFields.goal}<textarea name="goal" required maxlength="300" rows="2">${esc(v.goal)}</textarea></label><label>${guidedPlanFields.success_criteria}<textarea name="success_criteria" required maxlength="600" rows="2">${esc(v.success_criteria)}</textarea></label><details ${usingDraft?'open':''}><summary>具体引导方法 · 可选</summary>${Object.entries(guidedPlanFields).filter(([k])=>!['goal','success_criteria'].includes(k)).map(([k,label])=>`<label>${label}<textarea name="${k}" maxlength="600" rows="2">${esc(v[k])}</textarea></label>`).join('')}</details>${usingDraft&&draft.uncertainties?.length?`<p class="note source">${draft.uncertainties.map(esc).join('；')}${draft.goal_source==='proposal'||draft.success_criteria_source==='proposal'?' 目标或观察点也由系统提出，需要确认。':''}</p>`:''}<label class="child-share-option"><input name="share_goal" type="checkbox" ${editor.share_goal?'checked':''}><span>向孩子展示目标和观察点</span></label><p class="small muted">给孩子看前，检查是否提前写出了答案。</p><p class="small muted">生成具体指南需先补充并核对参考；也可手写。${s.editable?` <button type="button" data-guided-edit="${esc(s.id)}">补充题目与参考</button>`:''}</p><div class="toolbar"><button type="button" data-guided-plan-draft>根据本题生成草稿</button><button class="primary" type="submit">确认并保存指南</button><button type="button" data-guided-plan-cancel>先收起</button></div></form>`;
}
function guidedConflictHTML(s){const conflict=guidedParent.conflict;if(!conflict||conflict.id!==s.id)return '';return `<section id="guidedConflictPanel" class="note"><p>安排已变化，当前输入保留着，尚未覆盖新的指南。</p>${conflict.latest?`${guidedPlanDisplay(conflict.latest)}<button type="button" data-guided-adopt-version>已核对，保留输入继续</button>`:'<button type="button" data-guided-reconcile>核对最新安排</button>'}</section>`}
async function guidedReconcile(){if(guidedParent.busy||guidedParent.pending)return;const conflict=guidedParent.conflict;if(!conflict)return;guidedParent.busy=true;guidedLock();try{const result=await guidedFetch('state',{});guidedParent.sessions=result.sessions;const latest=guidedSession(conflict.id);if(!latest)throw Error('这项任务暂时无法读取，输入仍保留');conflict.latest=latest;guidedParent.error='';guidedReview(latest.id)}catch(e){guidedParent.error=e.message;const out=$('#guidedMaterialError');if(out)out.textContent=e.message}finally{guidedParent.busy=false;guidedLock()}}
function guidedAdoptVersion(){const conflict=guidedParent.conflict,edit=guidedParent.planEditor;if(!conflict?.latest||!edit||edit.id!==conflict.id)return;edit.version=conflict.latest.version;const draft=conflict.latest.plan_draft,stale=edit.based_on_draft_id&&(!draft||draft.id!==edit.based_on_draft_id||draft.status!=='ready');if(stale)edit.based_on_draft_id=null;guidedParent.notice=stale?'输入已保留；原草稿已失效，本次将作为手动指南保存，请再次核对。':'输入已保留，并采用刚核对的版本；确认保存才会更新指南。';guidedParent.conflict=null;guidedReview(edit.id)}
function guidedPlanEdit(s){const old=guidedParent.planEditor;if(!old||old.id!==s.id){const p=s.plan||{};guidedParent.planEditor={id:s.id,version:s.version,plan:Object.fromEntries(Object.keys(guidedPlanFields).map(k=>[k,p[k]||''])),share_goal:p.share_goal===true,based_on_draft_id:null,dirty:false,open:true}}guidedParent.planEditor.open=true;guidedReview(s.id);$('#guidedPlanForm [name="goal"]')?.focus()}
function guidedRememberPlan(){const f=$('#guidedPlanForm'),e=guidedParent.planEditor;if(!f||!e)return;e.plan=Object.fromEntries(Object.keys(guidedPlanFields).map(k=>[k,f.elements[k].value]));e.share_goal=f.elements.share_goal.checked;e.dirty=true}
function guidedSync(){const s=guidedSession(guidedParent.workspace),d=$('#guidedDialog');if(!s||!d?.open)return;const out=$('#guidedObservations');if(out)out.innerHTML=guidedObservations(s)}
function guidedReview(id){
 const s=guidedSession(id);if(!s)return;const d=guidedDialog(),recordID=guidedLatestRecord(s);if((!guidedParent.planEditor||guidedParent.planEditor.id!==id)&&s.plan_draft?.status==='ready'&&s.plan_draft.plan)guidedParent.planEditor={id:s.id,version:s.version,plan:{...s.plan_draft.plan},share_goal:s.plan?.share_goal===true,based_on_draft_id:s.plan_draft.id,dirty:false,open:true};guidedParent.workspace=id;guidedParent.editor=null;guidedParent.materialReturn=null;
 d.classList.add('guided-workspace');d.innerHTML=`<div class="guided-workspace-content" data-guided-workspace="${esc(s.id)}"><header class="section-head"><div><p class="small muted">${esc(data.children.find(c=>c.id===s.child_id)?.name)} · ${esc(guidedStateLabel(s.state))}${s.shared?' · 已分享给孩子':''}</p><h2>${esc(s.title)}</h2></div><button data-guided-dismiss>关闭</button></header><div class="toolbar guided-workspace-actions"><button class="primary" data-guided-plan-edit="${esc(s.id)}" ${s.allowed_actions.includes('guide_save')?'':'disabled'}>生成 / 调整指南</button><button data-guided-feedback="${esc(s.id)}" ${recordID?'':'disabled'}>记这次反馈</button><button data-guided-calendar="${esc(s.id)}">安排再试</button></div><section class="guided-workspace-section"><h3>本次目标与教学指南</h3><div id="guidedPlanDisplay" ${guidedParent.planEditor?.id===s.id&&guidedParent.planEditor.open!==false?'hidden':''}>${guidedPlanDisplay(s)}</div>${guidedPlanForm(s)}${guidedConflictHTML(s)}${guidedParent.notice?`<p class="note">${esc(guidedParent.notice)}</p>`:''}${s.plan_draft?.status==='failed'||s.plan_draft?.status==='stale'?`<p class="note">${esc(s.plan_draft.message||'上次指南草稿暂时无法使用，可以修改材料或直接手写。')}</p>`:''}${s.plan_draft?.status==='pending'?'<p role="status">正在准备指南草稿。可以关闭这里，稍后回来核对。</p>':''}</section><section class="guided-workspace-section"><h3>题目与实际尝试</h3>${!s.shared&&s.allowed_actions.includes('share')?`<button class="primary" data-guided-action="share" data-id="${esc(s.id)}">分享给孩子</button>`:''}<p class="source">${esc(s.question_text||'题目说明尚未补充。')}</p><p>${guidedOriginals(s.question_attachments)}</p>${guidedEvents(s)}</section><section class="guided-workspace-section"><h3>家长观察</h3><div id="guidedObservations">${guidedObservations(s)}</div>${!recordID?'<p class="small muted">先让孩子留下一次真实尝试，再针对这次尝试记录反馈。</p>':''}</section><section class="guided-workspace-section"><h3>下次安排</h3><p class="small muted">先商量再试的时间，或从这次尝试准备一题相近的新材料。</p><button data-guided-next="${esc(s.id)}" ${recordID?'':'disabled'}>准备相近新题</button></section><details class="ask-citation"><summary>更多操作与材料参考</summary><div class="toolbar">${['unshare','pause','resume','close'].filter(a=>s.allowed_actions.includes(a)).map(a=>`<button data-guided-action="${a}" data-id="${esc(s.id)}">${({share:'分享给孩子',unshare:'停止分享',pause:'先暂停',resume:'继续',close:'结束本次'})[a]}</button>`).join('')}${s.state==='draft'?`<button data-guided-edit="${esc(s.id)}">调整题目与参考</button>`:''}<button data-child-access="${esc(s.child_id)}">孩子入口</button></div><p class="source">${esc(s.reference_text||'尚未提供参考。')}</p>${s.material_gaps.map(x=>`<p class="small">${esc(x)}</p>`).join('')}</details><p id="guidedMaterialError" class="error" role="alert">${esc(guidedParent.error)}</p>${guidedParent.pending?'<p class="note">请求内容与编号已保留。<button data-guided-retry>用原内容重试</button></p>':''}</div>`;
 const f=$('#guidedPlanForm');if(f){f.oninput=guidedRememberPlan;f.onchange=guidedRememberPlan;f.onsubmit=e=>{e.preventDefault();guidedRememberPlan();const edit=guidedParent.planEditor;guidedSave('action',{id:s.id,child_id:s.child_id,version:edit.version,action:'guide_save',plan:edit.plan,share_goal:edit.share_goal,...(edit.based_on_draft_id?{based_on_draft_id:edit.based_on_draft_id}:{})})}}
 guidedShow(d);d.scrollTop=0;guidedLock();
}
function guidedLock(){const d=$('#guidedDialog');d?.querySelectorAll('input,select,textarea,button').forEach(el=>{const closing=el.hasAttribute('data-guided-dismiss'),retry=el.hasAttribute('data-guided-retry');if(guidedParent.busy||guidedParent.pending){if(!el.hasAttribute('data-guided-locked'))el.dataset.guidedLocked=String(el.disabled);el.disabled=!(closing&&(!guidedParent.busy||guidedIsDrafting())||retry&&!guidedParent.busy)}else if(el.hasAttribute('data-guided-locked')){el.disabled=el.dataset.guidedLocked==='true';delete el.dataset.guidedLocked}})}
async function guidedSave(action,body){
 if(guidedParent.busy)return;if(action&&guidedParent.pending){toast('请先用原内容核对上次保存');return}
 if(!guidedParent.pending)guidedParent.pending={action,body:{...body,request_key:crypto.randomUUID()},knownIDs:(guidedParent.sessions||[]).map(s=>s.id)};
 const request=guidedParent.pending,operation=request.body.action||request.action;guidedParent.busy=true;guidedLock();
 try{
  const result=await guidedFetch(request.action,request.body);guidedParent.sessions=result.sessions;guidedParent.error='';guidedParent.notice='';guidedParent.conflict=null;guidedParent.pending=null;guidedParent.editor=null;
  let id=result.session_id||request.body.id;
  if(!id){const candidates=result.sessions.filter(s=>!request.knownIDs.includes(s.id)&&s.child_id===request.body.child_id);if(candidates.length===1)id=candidates[0].id}
  const s=guidedSession(id);if(!s)throw Error('安排已保存，但当前任务编号暂时无法核对，请从列表打开。');
  if(operation==='guide_draft'&&s.plan_draft?.status==='ready'&&s.plan_draft.plan){guidedParent.planEditor={id:s.id,version:s.version,plan:{...s.plan_draft.plan},share_goal:guidedParent.planEditor?.id===s.id?guidedParent.planEditor.share_goal:s.plan?.share_goal===true,based_on_draft_id:s.plan_draft.id,dirty:false,open:true}}
  else if(operation==='guide_draft'&&guidedParent.planEditor?.id===s.id)guidedParent.planEditor.version=s.version;
  else if(operation==='guide_save')guidedParent.planEditor=null;
  else if(operation==='material'&&guidedParent.planEditor?.id===s.id){guidedParent.planEditor.version=s.version;guidedParent.planEditor.based_on_draft_id=null;guidedParent.planEditor.dirty=true;guidedParent.notice='材料已更新，原指南输入保留，请核对后再保存。'}
  toast(operation==='guide_draft'?(s.plan_draft?.status==='ready'?'指南草稿已返回，请核对':'指南尚未就绪，可以直接手写'):operation==='guide_save'?'教学指南已保存':'学习安排已保存');
  const wasOpen=$('#guidedDialog')?.open,stillCurrent=guidedParent.workspace===s.id;
  if(operation!=='guide_draft'||stillCurrent)guidedParent.workspace=s.id;if(page==='learning')render();
  if(operation!=='guide_draft'||wasOpen&&stillCurrent)guidedReview(s.id);
 }catch(e){if([400,404,409].includes(e.status))guidedParent.pending=null;if(e.status===409&&['version_conflict','guide_context_changed','record_context_changed','state_conflict'].includes(e.code)&&['guide_save','guide_draft'].includes(operation))guidedParent.conflict={id:request.body.id,latest:null};guidedParent.error=e.message;const out=$('#guidedMaterialError');if(out){out.textContent=e.message+(guidedParent.pending?'。内容和编号已保留，请用原内容重试。':'。输入仍保留，请核对最新安排。');if(guidedParent.conflict&&!$('#guidedDialog [data-guided-reconcile]'))out.insertAdjacentHTML('beforeend',' <button type="button" data-guided-reconcile>核对最新安排</button>');if(guidedParent.pending&&!$('#guidedDialog [data-guided-retry]'))out.insertAdjacentHTML('beforeend',' <button type="button" data-guided-retry>用原内容重试</button>')}if(page==='learning'&&!$('#guidedDialog')?.open)render()}
 finally{guidedParent.busy=false;guidedLock()}
}
window.FamilyGuided={html:guidedHTML,sync:guidedSync,wire(){if(!guidedParent.sessions&&!guidedParent.loading&&!guidedParent.error)guidedRead();guidedSync()}};
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-guided-create'))guidedOpen();
 if(b.hasAttribute('data-guided-new'))guidedOpen(b.dataset.guidedNew);
 if(b.hasAttribute('data-guided-refresh'))guidedRead();
 if(b.hasAttribute('data-guided-review'))guidedReview(b.dataset.guidedReview);
 if(b.hasAttribute('data-guided-edit')){const s=guidedSession(b.dataset.guidedEdit);if(s)guidedOpen(s.related_record_id,s)}
 if(b.hasAttribute('data-guided-dismiss')&&(!guidedParent.busy||guidedIsDrafting())){if(guidedParent.materialReturn&&!guidedParent.pending){const id=guidedParent.materialReturn;guidedParent.editor=null;guidedReview(id)}else $('#guidedDialog')?.close()}
 if(b.hasAttribute('data-guided-retry'))guidedSave();
 if(b.hasAttribute('data-guided-reconcile'))guidedReconcile();
 if(b.hasAttribute('data-guided-adopt-version'))guidedAdoptVersion();
 if(b.dataset.guidedAction){const s=guidedSession(b.dataset.id);if(s)guidedSave('action',{id:s.id,child_id:s.child_id,version:s.version,action:b.dataset.guidedAction})}
 if(b.dataset.guidedPlanEdit){const s=guidedSession(b.dataset.guidedPlanEdit);if(s)guidedPlanEdit(s)}
 if(b.hasAttribute('data-guided-plan-cancel')){guidedRememberPlan();const id=guidedParent.workspace;guidedParent.planEditor.open=false;guidedReview(id)}
 if(b.hasAttribute('data-guided-plan-draft')){guidedRememberPlan();const s=guidedSession(guidedParent.workspace),v=guidedParent.planEditor;if(s&&v)guidedSave('action',{id:s.id,child_id:s.child_id,version:v.version,action:'guide_draft',goal:v.plan.goal,success_criteria:v.plan.success_criteria})}
 if(b.dataset.guidedFeedback){const s=guidedSession(b.dataset.guidedFeedback);guidedWithRecord(s,id=>{const trigger=document.createElement('button');trigger.dataset.followup=id;trigger.dataset.followupKind='补充观察';document.body.append(trigger);trigger.click();trigger.remove()})}
 if(b.dataset.guidedNext){const s=guidedSession(b.dataset.guidedNext);guidedWithRecord(s,id=>guidedOpen(id,null,{title:s.title,subject:s.subject,practice_relation:'相近的新题或新片段'}))}
 if(b.dataset.guidedCalendar){const s=guidedSession(b.dataset.guidedCalendar);if(!s)return;if(calendarPending||calendarSaving){toast('请先核对上次日历保存结果');return}calendarOpen(null,{child_ids:[s.child_id],title:'再试一题：'+s.title,category:'study',day:'',start_time:'',end_time:'',note:'与孩子商量再试，回看“'+s.title+'”的首次尝试与实际提示。',status:'tentative',repeat:'none',until:''})}
});
window.addEventListener('beforeunload',e=>{if(guidedParent.pending||guidedParent.editor||guidedParent.planEditor?.dirty){e.preventDefault();e.returnValue=''}});
