"""Run python3 test_task_video.py. Synthetic household, generated bytes, mocked ffprobe and model; no household services or paid models."""
import base64
import datetime as dt
import http.client
import io
import json
import os
import shutil
import subprocess
import tempfile
import threading
import unittest
from unittest import mock

import family_agent as agent
import family_llm
import family_task_video as tv
import test_goals

DRAFT=dict(observations=[dict(start_seconds=1,end_seconds=3.5,text='虚构：画面中逐行书写听写词')],uncertainties=['虚构：第二行被手遮挡'])
NONE=dict(used=0,failed=0);SENT=dict(used=1,failed=0);FAILED=dict(used=1,failed=1)


class TaskVideoTests(unittest.TestCase):
    action=test_goals.GoalTests.action;reply=test_goals.GoalTests.reply
    TASK=test_goals.MediaFeedbackEvidenceTests.TASK;OTHER='M-synthetic-2';SIBLING='M-synthetic-3'

    def setUp(self):
        test_goals.MediaFeedbackEvidenceTests.setUp(self)
        self.app.DATA=self.app.DATA.resolve();self.data=self.app.DATA  # read_file refuses a symlink anywhere in the path; macOS temp dirs sit behind one.
        self.agent=agent.Store(self.app.connect,self.app.profiles,self.app.DATA,app=self.app)
        self.duration='12.5';self.probes=[];self.sent=[];self.during_probe=self.during_call=None;self.fail=False;self.uploads={};self.changes=[]
        mock.patch.object(subprocess,'run',side_effect=self.ffprobe).start();mock.patch.object(family_llm,'configuration').start()
        self.model.side_effect=self.chat;self.enable(True)

    def enable(self,on):(self.app.DATA/'agent.json').write_text(json.dumps(dict(enabled=on,sources=[])))

    def ffprobe(self,args,**kwargs):
        assert args[0]=='ffprobe' and args[args.index('-protocol_whitelist')+1]=='pipe' and args[args.index('-i')+1]=='pipe:0',args
        if 'stream=codec_type:format=duration' in args:  # The job's probe; an upload asks for the streams only.
            self.probes.append(kwargs['input'])
            if self.during_probe:self.during_probe();self.changes.append('probe')
        return subprocess.CompletedProcess(args,0,stdout=json.dumps(dict(streams=[dict(codec_type='video')],format=dict(duration=self.duration))).encode())

    def chat(self,messages,schema,name,timeout,**kwargs):
        if name!='family_video_feedback_draft':return self.reply(messages,schema,name,timeout,**kwargs)
        self.sent.append(json.loads(messages[-1]['content'][0]['text']))
        if self.during_call:self.during_call();self.changes.append('call')
        if self.fail:raise family_llm.LLMDraftError('虚构模型失败')
        return json.loads(json.dumps(DRAFT))

    def clip(self,name='synthetic-clip.mp4'):
        self.count+=1;body=(b'\x1a\x45\xdf\xa3synthetic webm %d' if name.endswith('.webm') else b'\x00\x00\x00\x18ftypisomsynthetic %d')%self.count
        return self.app.save_upload(io.BytesIO(body),len(body),name)['id']

    def feedback(self,upload=None):
        self.count+=1
        return self.app.save_task_feedback(dict(task_id=self.TASK,child='示例甲',day=self.now.date().isoformat(),subject='英语',
            request_key='synthetic-video-'+str(self.count).zfill(8),attachments=[upload or self.clip()]))['record_id']

    def record(self,**obj):
        return dict(child='示例甲',day=self.now.date().isoformat(),category='学习进展',subject='英语',title='虚构练习视频',note='虚构说明',source='家长网页记录')|obj

    def linked(self,task=None):
        upload=self.clip();ident=self.app.save_record(self.record(attachments=[upload]))['record_id'];self.uploads[ident]=upload
        if task:self.app.link_record_task(dict(record_id=ident,child='示例甲',task_id=task))
        return ident

    def relink(self,ident):
        with self.app.connect() as c:at=c.execute('SELECT linked_task_at FROM records WHERE id=?',(ident,)).fetchone()[0]
        return lambda:self.app.link_record_task(dict(record_id=ident,child='示例甲',task_id=self.OTHER,expected_linked_at=at))

    def correct(self,ident):  # A note-only correction: subject, originals and link stay as they were.
        return lambda:self.app.save_record(self.record(id=ident,note='虚构：更正说明',attachments=[self.uploads[ident]]))

    def tick(self,minutes=0):return tv.prepare(self.app,self.agent,self.now+dt.timedelta(minutes=minutes))

    def lines(self):
        with self.app.connect() as c:return set(c.iterdump())

    def files(self):return {p.name:p.read_bytes() for p in (self.app.DATA/'uploads').iterdir()}

    def rows(self,table):
        with self.app.connect() as c:return c.execute('SELECT COUNT(*) FROM '+table+(" WHERE id LIKE 'record-video:%'" if table=='agent_jobs' else '')).fetchone()[0]

    def view(self,ident):
        """Every read in these tests also proves that reading calls nothing and writes nothing."""
        before=(self.lines(),self.files(),len(self.probes),len(self.sent));result=tv.view(self.app,self.agent,ident)
        self.assertEqual((self.lines(),self.files(),len(self.probes),len(self.sent)),before);return result

    def state(self,ident):return [v['state'] for v in self.view(ident)['videos']]

    def test_feedback_and_link_each_leave_once_and_records_tasks_and_originals_stay_as_they_were(self):
        first=self.feedback();second=self.linked(self.TASK);before=self.lines();files=self.files()
        self.assertEqual((self.state(first),self.state(second)),(['pending'],['pending']))
        with mock.patch.object(tv.family_media,'read_file',wraps=tv.family_media.read_file) as read:
            self.assertEqual([self.tick(),self.tick(),self.tick(),self.tick(60*24)],[SENT,SENT,NONE,NONE])
        self.assertTrue(read.call_args_list and all(call.args[1]==family_llm.MAX_INPUT for call in read.call_args_list),'bounded read only')
        self.assertEqual(len(self.sent),2);self.assertEqual(self.sent[0]['task'],dict(title='虚构听写',subject='英语',requirement='虚构要求'))
        views=[self.view(i) for i in (first,second)]
        self.assertEqual([(v['basis'],v['task_id'],v['audience'],v['read_only'],v['videos'][0]['state']) for v in views],
                         [('feedback',self.TASK,'parent',True,'ready'),('link',self.TASK,'parent',True,'ready')])
        video=views[0]['videos'][0];self.assertEqual((video['duration_seconds'],video['draft']['observations'],video['draft']['audio_assessed']),(12.5,DRAFT['observations'],False))
        changed=before^self.lines();self.assertTrue(changed);self.assertTrue(all('record_video_drafts' in l or 'agent_jobs' in l for l in changed),changed)
        self.assertEqual(self.files(),files)

    def test_another_childs_task_a_shared_original_an_unlinked_record_and_a_disabled_agent_never_leave(self):
        plain=self.linked();foreign=self.linked(self.TASK);shared=self.feedback()
        with self.app.connect() as c:
            c.execute('UPDATE records SET linked_task_id=? WHERE id=?',(self.SIBLING,foreign))  # The other child's task.
            c.execute("INSERT INTO records(child,day,category,subject,title,note,source,created,attachments) VALUES('示例乙',?,'学习进展','英语','虚构','虚构','家长网页记录',?,?)",
                      (self.now.date().isoformat(),self.now.isoformat(),c.execute('SELECT attachments FROM records WHERE id=?',(shared,)).fetchone()[0]))
        self.assertEqual(self.tick(),NONE);self.enable(False);allowed=self.feedback();self.assertEqual(self.tick(),NONE)
        self.assertEqual((self.sent,self.probes,self.rows('agent_jobs'),self.rows('record_video_drafts')),([],[],0,0))
        self.assertEqual([self.state(i) for i in (plain,foreign,shared,allowed)],[[],[],['unavailable'],['unavailable']])
        self.assertTrue(self.view(plain)['explanation'] and self.view(foreign)['explanation'])
        # Counter-proof: the same household does call out once the switch is on, so the zeros above are the guards' doing.
        self.enable(True);self.assertEqual(self.tick(),SENT);self.assertEqual((self.state(allowed),self.state(shared),len(self.sent)),(['ready'],['unavailable'],1))

    def test_a_change_before_or_during_the_call_is_neither_saved_nor_shown(self):
        for when in ('during_probe','during_call'):
            for name,change in (('relink',self.relink),('correct',self.correct),('disable',lambda ident:lambda:self.enable(False))):
                with self.subTest(when=when,change=name):
                    self.enable(True);ident=self.linked(self.TASK);sent=len(self.sent);changes=len(self.changes);setattr(self,when,change(ident))
                    try:result=self.tick()
                    finally:setattr(self,when,None)
                    self.assertEqual(len(self.changes),changes+1,'the injected change must succeed, not merely raise inside the job');called=int(when=='during_call');self.assertEqual((result,len(self.sent)-sent),(dict(used=called,failed=1),called))
                    self.assertEqual(self.rows('record_video_drafts'),0);self.assertNotIn('ready',self.state(ident))

    def test_a_note_only_correction_hides_the_ready_draft_and_without_the_last_recheck_a_stale_result_is_stored(self):
        ident=self.linked(self.TASK);self.assertEqual(self.tick(),SENT);self.assertEqual(self.state(ident),['ready'])
        self.correct(ident)();self.assertEqual(self.state(ident),['pending'])
        # Counter-proof: with only the final re-check removed, the same mid-call relink stores the stale draft.
        ident=self.linked(self.TASK);real=tv._current;calls=[]
        def unguarded(app,store,c,value):
            calls.append(1);return real(app,store,c,value) if len(calls)<3 else value
        self.during_call=self.relink(ident)
        with mock.patch.object(tv,'_current',unguarded):self.assertEqual(self.tick(),SENT)
        self.during_call=None;self.assertEqual(self.rows('record_video_drafts'),2);self.assertEqual(self.state(ident),['pending'],'the read still compares the fingerprint')

    def test_three_failures_back_off_and_then_wait_for_the_parents_retry(self):
        ident=self.feedback();self.fail=True
        self.assertEqual([self.tick(m) for m in (0,1,5,6,15,16,999)],[FAILED,NONE,FAILED,NONE,FAILED,NONE,NONE])
        video=self.view(ident)['videos'][0];self.assertEqual((video['state'],video['attempts'],video['exhausted'],len(self.sent)),('error',3,True,3))
        self.assertIn('虚构模型失败',video['explanation']);self.assertEqual(self.rows('record_video_drafts'),0)
        self.fail=False;self.agent.act(dict(action='retry',id=video['job_id']))
        self.assertEqual((self.tick(999),self.tick(999)),(SENT,NONE));self.assertEqual((self.state(ident),len(self.sent)),(['ready'],4))

    def test_independent_agent_uses_only_remaining_budget_and_does_not_repeat(self):
        ident=self.feedback()
        with mock.patch.object(test_goals.goals.Store,'run',return_value=dict(used=3,created=0,failed=0,children=[])),mock.patch.object(tv,'prepare',wraps=tv.prepare) as prepare:
            agent.run_once(self.app,self.now)
            prepare.assert_not_called()
        self.assertEqual((self.sent,self.state(ident)),([],['pending']))
        self.model.reset_mock()
        result=agent.run_once(self.app,self.now)
        self.assertEqual((result['failed'],len(self.sent),self.state(ident)),(0,1,['ready']))
        self.assertLessEqual(self.model.call_count,3)
        agent.run_once(self.app,self.now)
        self.assertEqual(len(self.sent),1)

    def test_a_webm_without_a_duration_is_refused_as_unsupported_and_is_not_sent(self):
        self.duration='N/A'
        for mime,code in (('video/webm','webm_duration_unsupported'),('video/mp4','duration_invalid')):
            with self.assertRaises(tv.VideoDraftError) as caught:tv.probe(b'synthetic',mime)
            self.assertEqual(caught.exception.code,code)
        ident=self.feedback(self.clip('synthetic-clip.webm'));self.assertEqual(self.tick(),dict(used=0,failed=1));self.assertEqual(self.sent,[])
        video=self.view(ident)['videos'][0];self.assertEqual(video['state'],'error');self.assertIn('尚未支持',video['explanation'])


class TaskVideoHttpTests(unittest.TestCase):
    """#23 over real HTTP: the parent reads the checked draft; a child session, the public anonymous entry and malformed
    requests get nothing; a read calls no model or ffprobe and writes nothing; the retry stays the existing CSRF-checked action."""
    action=TaskVideoTests.action;reply=TaskVideoTests.reply;TASK=TaskVideoTests.TASK;OTHER=TaskVideoTests.OTHER;SIBLING=TaskVideoTests.SIBLING
    ffprobe=TaskVideoTests.ffprobe;chat=TaskVideoTests.chat;enable=TaskVideoTests.enable;clip=TaskVideoTests.clip;feedback=TaskVideoTests.feedback;record=TaskVideoTests.record
    linked=TaskVideoTests.linked;relink=TaskVideoTests.relink;correct=TaskVideoTests.correct;tick=TaskVideoTests.tick;lines=TaskVideoTests.lines;files=TaskVideoTests.files
    PUBLIC='family.example.ts.net';LAN='192.168.50.2:8765';PASSWORD='synthetic-http-parent-password-123'

    def setUp(self):
        TaskVideoTests.setUp(self);self.server=self.app.ThreadingHTTPServer(('127.0.0.1',0),self.app.Handler)
        worker=threading.Thread(target=self.server.serve_forever,daemon=True);worker.start()
        self.addCleanup(lambda:(self.server.shutdown(),self.server.server_close(),worker.join()))

    def request(self,path,body=None,headers=None,host=None):
        client=http.client.HTTPConnection('127.0.0.1',self.server.server_port,timeout=5)
        try:
            client.request('POST' if body is not None else 'GET',path,json.dumps(body) if body is not None else None,
                           {'Content-Type':'application/json',**({'Host':host} if host else {}),**(headers or {})})
            response=client.getresponse();raw=response.read()
            try:value=json.loads(raw)
            except ValueError:value=None  # An original, not JSON.
            return response.status,value,dict(response.getheaders())
        finally:client.close()

    def calls(self):return (self.lines(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent))

    def video(self,ident,headers=None,host=None):
        """Every HTTP read in these tests also proves that reading calls nothing and writes nothing."""
        before=self.calls();status,result,_=self.request('/api/record/video?record_id=%d'%ident,headers=headers,host=host)
        self.assertEqual(self.calls(),before);return status,result

    def entry(self,base):
        path=self.app.DATA/'access.json';path.write_text(json.dumps(self.app.family_access.make_config(base,'parent',self.PASSWORD)),encoding='utf-8');path.chmod(0o600)

    def test_the_parent_reads_the_checked_draft_and_a_child_the_public_entry_and_malformed_requests_get_nothing(self):
        first=self.linked(self.TASK);second=self.linked(self.TASK);self.assertEqual([self.tick(),self.tick()],[SENT,SENT])
        upload=self.uploads[first];text=DRAFT['observations'][0]['text'];status,result=self.video(first)
        self.assertEqual((status,result['record_id'],result['task_id'],result['basis'],result['audience'],result['read_only']),(200,first,self.TASK,'link','parent',True))
        video,=result['videos']
        self.assertEqual((video['state'],video['upload_id'],video['job_id'],video['duration_seconds']),('ready',upload,tv.job_key(first,upload),12.5))
        self.assertEqual(video['draft']['observations'],DRAFT['observations']);self.assertIs(video['draft']['audio_assessed'],False)
        self.assertEqual(self.video(first),(200,result),'a repeated read is the same read')
        for query in ('','?','?record_id=','?record_id=0','?record_id=-1','?record_id=01','?record_id=1.0','?record_id=%2B1','?record_id=abc','?record_id=9223372036854775808',
                      '?record_id=%EF%BC%91','?id=%d'%first,'?record_id=%d&record_id=%d'%(first,first),'?record_id=%d&child=x'%first,'?record_id=%d;record_id=%d'%(first,second)):
            with self.subTest(query=query):
                before=self.calls();status,refused,_=self.request('/api/record/video'+query)
                self.assertEqual((status,set(refused)),(400,{'error'}));self.assertEqual(self.calls(),before)
        before=self.calls();status,refused,_=self.request('/api/record/video?record_id=987654')
        self.assertEqual((status,refused.get('code')),(404,'record_missing'));self.assertEqual(self.calls(),before)
        # The same child's own session: no draft, no retry and no original, on the loopback entry and with the parent token too.
        child=self.app.family_child;child.parent_action(self.app,'study',dict(child_id='child-1',enabled=True))
        status,state,headers=self.request('/child/api/login',dict(invite=child.parent_action(self.app,'invite',dict(child_id='child-1'))['invite']));self.assertEqual(status,200)
        cookie={'Cookie':headers['Set-Cookie'].split(';',1)[0]};kid=cookie|{'X-Child-CSRF':state['csrf']}
        status,state,_=self.request('/child/api/state',headers=kid);self.assertEqual(status,200)
        for hidden in (text,upload):self.assertNotIn(hidden,json.dumps(state,ensure_ascii=False))
        retry=dict(action='retry',id=video['job_id']);token={'X-Family-Token':self.app.TOKEN}
        def refused_everywhere(who,status,host=None):
            before=self.calls();got,body,_=self.request('/api/record/video?record_id=%d'%first,headers=who,host=host)
            self.assertEqual(got,status);self.assertNotIn('videos',body);self.assertNotIn(text,json.dumps(body,ensure_ascii=False))
            self.assertEqual(self.request('/api/agent/action',retry,who|token,host=host)[0],status)
            self.assertEqual(self.request('/upload/'+upload,headers=who,host=host)[0],status);self.assertEqual(self.calls(),before)
        for who in (cookie,kid):refused_everywhere(who,403)
        self.assertEqual(self.request('/child/upload/'+upload,headers=kid)[0],403)
        self.assertEqual(self.request('/upload/'+upload)[0],200,'the same original stays readable for the parent')
        # Public entry: anonymous and child-only requests are not a parent; the signed-in parent reads the same draft.
        self.entry('https://'+self.PUBLIC+'/family');self.addCleanup((self.app.DATA/'access.json').unlink)
        for who in ({},cookie,kid):refused_everywhere(who,401,self.PUBLIC)
        basic={'Authorization':'Basic '+base64.b64encode(('parent:'+self.PASSWORD).encode()).decode('ascii')}
        self.assertEqual(self.video(first,headers=basic,host=self.PUBLIC),(200,result))
        # Home-network entry without login: the parent reads, a child session on the same network still does not.
        self.entry('http://'+self.LAN)
        with mock.patch.dict(os.environ,FAMILY_LAN_NO_LOGIN='1'):
            self.assertEqual(self.video(first,host=self.LAN),(200,result))
            for who in (cookie,kid):refused_everywhere(who,403,self.LAN)
        # Authorization withdrawn, a correction and a moved link: the stored draft is no longer shown.
        self.enable(False);status,off=self.video(first);self.assertEqual((status,[v['state'] for v in off['videos']]),(200,['unavailable']));self.assertNotIn(text,json.dumps(off,ensure_ascii=False))
        self.enable(True);self.assertEqual(self.video(first),(200,result))
        self.correct(first)();self.relink(second)()
        for ident,task in ((first,self.TASK),(second,self.OTHER)):
            status,stale=self.video(ident);self.assertEqual((status,stale['task_id'],[v['state'] for v in stale['videos']]),(200,task,['pending']))
            self.assertNotIn('draft',stale['videos'][0]);self.assertNotIn(text,json.dumps(stale,ensure_ascii=False))

    def test_the_existing_retry_keeps_its_csrf_check_and_only_queues_the_job(self):
        ident=self.feedback();self.fail=True;self.assertEqual([self.tick(m) for m in (0,5,15)],[FAILED]*3)
        status,result=self.video(ident);video,=result['videos']
        self.assertEqual((status,video['state'],video['attempts'],video['exhausted']),(200,'error',3,True));self.assertNotIn('draft',video)
        retry=dict(action='retry',id=video['job_id'])
        for headers in ({},{'X-Family-Token':'invalid-token'}):
            before=self.calls();status,refused,_=self.request('/api/agent/action',retry,headers)
            self.assertEqual((status,refused.get('code')),(403,'csrf_expired'));self.assertEqual(self.calls(),before)
        self.assertEqual(self.tick(999),NONE,'an exhausted job waits for the parent')
        before=self.calls();status,done,_=self.request('/api/agent/action',retry,{'X-Family-Token':self.app.TOKEN});after=self.calls()
        self.assertEqual((status,done),(200,dict(ok=True,state='retry_pending')))
        self.assertEqual(after[1:],before[1:],'the retry calls no model or ffprobe and touches no original')
        changed=before[0]^after[0];self.assertTrue(changed and all('agent_jobs' in line for line in changed),changed)
        self.assertEqual([v['state'] for v in self.video(ident)[1]['videos']],['pending'])
        self.fail=False;self.assertEqual((self.tick(999),self.tick(999)),(SENT,NONE))
        self.assertEqual(([v['state'] for v in self.video(ident)[1]['videos']],len(self.sent)),(['ready'],4))


if __name__=='__main__':unittest.main()
