// Run with PLAYWRIGHT_MODULE / PLAYWRIGHT_CHANNEL as in test_startup_ui.cjs.
// Synthetic records only; optional LEARNING_UI_PROOF_DIR writes private proof/screenshots.
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const vm=require('node:vm');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const net=require('node:net');
const {setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const escaped=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function eventually(check,label,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await delay(40)}throw Error('Timed out: '+label)}
async function server(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 const processHandle=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let failure;processHandle.on('error',e=>failure=e);processHandle.stdout.resume();processHandle.stderr.resume();
 const stop=async()=>{if(processHandle.exitCode!==null||processHandle.signalCode!==null)return;const done=once(processHandle,'exit');processHandle.kill('SIGINT');await Promise.race([done,delay(2500)]);if(processHandle.exitCode===null&&processHandle.signalCode===null){processHandle.kill('SIGKILL');await done}};
 const url='http://127.0.0.1:'+port+'/';try{await eventually(async()=>{if(failure)throw failure;if(processHandle.exitCode!==null)throw Error('Synthetic demo exited');try{return(await fetch(url+'api/state')).ok}catch{return false}},'demo');return {url,stop}}catch(e){await stop();throw e}
}
async function guardChecks(){
 const record=(id,child='测试甲',extra={})=>({id,child,category:'学习进展',day:'2026-09-01',title:'虚构记录 '+id,note:'自己的观察',related_record_id:null,followup_kind:'',attachments:[],...extra});
 const records=[record(101),record(102,'测试甲',{related_record_id:101,followup_kind:'订正',day:'2026-09-02'}),record(103,'测试甲',{related_record_id:102,followup_kind:'复测',day:'2026-09-04',assistance:'独立尝试',practice_relation:'相近的新题或新片段'}),record(104,'测试甲',{related_record_id:103,followup_kind:'补充观察',category:'家长观察'}),record(201,'测试乙',{title:'OTHER_CHILD_PRIVATE_CANARY'}),record(105,'测试甲',{related_record_id:201}),record(106,'测试甲',{related_record_id:999}),record(107,'测试甲',{related_record_id:108}),record(108,'测试甲',{related_record_id:107}),record(109,'测试甲',{followup_kind:'独立复测'}),record(110),record(110,'测试甲',{title:'DUPLICATE_ID'}),record(111,'测试甲',{related_record_id:110}),record(112,'测试甲',{note:'<img src=x onerror=alert(1)>',attachments:['f'.repeat(32)]})];
 const context={data:{records,uploads:[]},child:'测试甲',esc:escaped,empty:s=>'<div>'+escaped(s)+'</div>',recordUploads:()=>''};
 const api=vm.runInNewContext(await fs.readFile(path.join(__dirname,'learning.js'),'utf8')+'\n;({learningCases,learningDateGap,learningEvidenceNotes,learningJourneysHTML})',context);
 const cases=api.learningCases(records,'测试甲');assert.ok(cases.every(g=>g.items.every(r=>r.child==='测试甲')));
 const linked=cases.find(g=>g.root.id===101);assert.deepEqual(Array.from(linked.items,r=>r.id).sort((a,b)=>a-b),[101,102,103,104]);assert.equal(linked.parents.get(records[2]).id,102);
 for(const id of [105,106,107,108,109,110,111])assert.ok(cases.find(g=>g.root.id===id)?.issues.length,'unsafe / unlinked chain '+id+' is explicit');
 for(const id of [107,108])assert.equal(cases.find(g=>g.root.id===id).items.length,1);
 assert.equal(api.learningDateGap('2026-09-01','2026-09-04'),-3);assert.equal(api.learningDateGap('2026-02-30','2026-02-28'),null);
 const legacy=api.learningEvidenceNotes(record(120,'测试甲',{followup_kind:'独立复测',practice_relation:'同一道题或同一片段'}),record(121));assert.ok(legacy.some(s=>s.includes('帮助情况未记录')));assert.ok(legacy.some(s=>s.includes('同一天')));assert.ok(legacy.some(s=>s.includes('新材料的迁移')));
 const html=api.learningJourneysHTML();assert.equal(html.includes('OTHER_CHILD_PRIVATE_CANARY'),false);assert.equal(html.includes('data-followup="110"'),false);assert.equal(html.includes('<img src=x'),false);assert.ok(html.includes('&lt;img'));assert.ok(html.includes('当前缺少元数据'));assert.ok(html.includes('独立复测 · 未关联'));assert.ok(html.includes('与关联记录的日期差：2 天'));
 const appSource=await fs.readFile(path.join(__dirname,'app.js'),'utf8');
 const evidence=appSource.slice(appSource.indexOf('function learningEvidenceHTML('),appSource.indexOf('function recordHTML('));
 const historySource=appSource.slice(appSource.indexOf('function recordVersionHTML('),appSource.indexOf('async function loadRecordHistory('));
 assert.ok(evidence&&historySource,'real history renderer found');
 const historyHTML=vm.runInNewContext(evidence+'\n'+historySource+'\n;recordHistoryHTML',{data:{records:[]},esc:escaped,endpoint:value=>value});
 const old=record(130),current={...old,assistance:'',practice_relation:'',comparison_note:''};
 const changedSummary=(now,previous)=>Array.from(historyHTML({current:now,attachments:[],history:[{changed:'2026-09-01T12:00:00',previous}]}).matchAll(/<summary>(.*?)<\/summary>/g),m=>m[1]).find(text=>text.includes('更正前'));
 for(const previous of [old,{...old,assistance:null,practice_relation:null,comparison_note:null}])assert.equal(/帮助情况|材料关系|比较条件/.test(changedSummary(current,previous)),false,'old schema empty context is not an edit');
 assert.match(changedSummary({...current,assistance:'独立尝试'},old),/帮助情况/,'actual changed help is still shown');
 return 'same-child and corrupt-chain guards, signed gaps, legacy unknowns, missing originals and old-schema history diff are checked';
}
(async()=>{
 let runtime,browser;const checks=[await guardChecks()],proofDir=process.env.LEARNING_UI_PROOF_DIR;
 try{
  runtime=await server();let current=await (await fetch(runtime.url+'api/state')).json();const first=current.children[0].name,second=current.children[1].name;
  async function save(fields){const r=await fetch(runtime.url+'api/record',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':current.token},body:JSON.stringify({child:first,day:'2026-09-01',category:'学习进展',subject:'虚构数学',title:'虚构测试记录',note:'原始观察',source:'试卷 / 作业核对',score:'',total:'',attachments:[],...fields})});const result=await r.json();assert.equal(r.status,200,result.error);current=await(await fetch(runtime.url+'api/state')).json();return current.records.find(x=>x.title===fields.title)}
  const original=await save({title:'虚构面积练习的第一次尝试',category:'成绩',score:6,total:10,note:'长方形面积步骤写出了一半，单位还需要核对。',assistance:'看过讲解或答案'});
  await save({child:second,title:'OTHER_CHILD_LEARNING_CANARY',note:'不应出现在另一位孩子的线索里。'});
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.goto(runtime.url);await p.locator('nav [data-page="learning"]').click();await eventually(()=>p.locator('[data-learning-case="'+original.id+'"]').isVisible(),'learning journeys integrated');await p.locator('#childFilter').selectOption({label:first});
  const card=()=>p.locator('[data-learning-case="'+original.id+'"]');assert.equal((await p.locator('.learning-journeys').innerText()).includes('OTHER_CHILD_LEARNING_CANARY'),false);
  await card().locator('[data-followup-kind="订正"]').click();assert.equal(await p.locator('#recordForm [name="followup_kind"]').inputValue(),'订正');assert.equal(await p.locator('#recordForm [name="related_record_id"]').inputValue(),String(original.id));
  await p.locator('#recordForm [name="day"]').fill('2026-09-02');await p.locator('#recordForm [name="title"]').fill('虚构面积练习的订正');await p.locator('#recordForm [name="note"]').fill('在提示下重新画图，补出了面积单位。');
  if((await p.locator('#learningEvidenceFields').getAttribute('open'))===null)await p.locator('#learningEvidenceFields > summary').click();
  await p.locator('#recordForm [name="assistance"]').selectOption('少量提示');await p.locator('#recordForm [name="practice_relation"]').selectOption('同一道题或同一片段');await p.locator('#recordForm [name="comparison_note"]').fill('同一张练习，家长提示检查单位。');await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>!(await p.locator('#recordDialog').isVisible()),'correction saved');await eventually(async()=>/尚无复测记录/.test(await card().innerText()),'correction without retest is visible');
  current=await(await fetch(runtime.url+'api/state')).json();const correction=current.records.find(r=>r.title==='虚构面积练习的订正');assert.equal(correction.assistance,'少量提示');assert.equal(correction.practice_relation,'同一道题或同一片段');
  checks.push('real parent form saves correction context and keeps no-retest gap visible');
  await card().locator('[data-followup-kind="复测"]').click();assert.equal(await p.locator('#recordForm [name="followup_kind"]').inputValue(),'复测');assert.notEqual(await p.locator('#learningEvidenceFields').getAttribute('open'),null);await p.locator('#recordForm [name="day"]').fill('2026-09-04');await p.locator('#recordForm [name="title"]').fill('虚构面积练习的再次尝试');await p.locator('#recordForm [name="note"]').fill('尝试一题相近的新材料，自己画图并写出单位；答案需核对。');await p.locator('#recordForm [name="assistance"]').selectOption('独立尝试');await p.locator('#recordForm [name="practice_relation"]').selectOption('相近的新题或新片段');await p.locator('#recordForm [name="comparison_note"]').fill('同一知识点，题目换了数字；尚未评估难度是否一致。');
  // Reject one real form POST so failed-save input retention is checked without writing twice.
  let rejected=false;await p.route('**/api/record',async route=>{if(!rejected){rejected=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构网络故障'})})}else await route.continue()});await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>/虚构网络故障/.test(await p.locator('#recordError').innerText()),'failed save visible');assert.equal(await p.locator('#recordForm [name="assistance"]').inputValue(),'独立尝试');assert.match(await p.locator('#recordForm [name="comparison_note"]').inputValue(),/尚未评估/);await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>!(await p.locator('#recordDialog').isVisible()),'retest saved after explicit retry');await p.unroute('**/api/record');
  await card().locator('.learning-compare > summary').click();assert.match(await card().innerText(),/这一次记录仍不足以认定稳定掌握/);assert.match(await card().innerText(),/日期差仅来自记录日期/);
  current=await(await fetch(runtime.url+'api/state')).json();const retest=current.records.find(r=>r.title==='虚构面积练习的再次尝试');assert.equal(retest.related_record_id,original.id);assert.equal(retest.followup_kind,'复测');assert.equal(retest.assistance,'独立尝试');assert.equal(retest.practice_relation,'相近的新题或新片段');
  checks.push('real retest form records attempt conditions, failed save preserves inputs, comparison avoids mastery inference');
  await card().locator('[data-learning-record="'+retest.id+'"] [data-record]').click();assert.equal(await p.locator('#recordForm [name="assistance"]').inputValue(),'独立尝试');await p.locator('#recordForm [name="assistance"]').selectOption('逐步帮助');await p.locator('#recordForm [name="comparison_note"]').fill('更正：回看当时过程，实际有逐步提示。');await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>!(await p.locator('#recordDialog').isVisible()),'context correction saved');await card().locator('.learning-compare > summary').click();assert.match(await card().innerText(),/逐步帮助/);assert.equal((await card().innerText()).includes('记录了独立尝试相近新材料'),false);
  const linked=await save({title:'虚构直接关联订正的复测',day:'2026-09-04',related_record_id:correction.id,followup_kind:'独立复测',note:'帮助情况没有填写，不能由旧名称推断。',assistance:'',practice_relation:'同一道题或同一片段'});
  await p.locator('#refresh').click();await eventually(()=>card().isVisible(),'fresh linked record');await card().locator('.learning-compare > summary').click();const linkedRow=card().locator('[data-learning-record="'+linked.id+'"]');assert.match(await linkedRow.innerText(),/直接关联：虚构面积练习的订正/);assert.match(await linkedRow.innerText(),/日期差：2 天/);assert.match(await linkedRow.innerText(),/帮助情况未记录/);assert.match(await linkedRow.innerText(),/不能据此判断对新材料的迁移/);
  current=await(await fetch(runtime.url+'api/state')).json();assert.equal(current.records.find(r=>r.id===retest.id).practice_relation,'相近的新题或新片段','editing help retained unedited relation');
  await card().locator('[data-learning-record="'+retest.id+'"] [data-record]').click();await p.locator('#recordForm [name="assistance"]').selectOption('');await p.locator('#recordForm [name="practice_relation"]').selectOption('');await p.locator('#recordForm [name="comparison_note"]').fill('');await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>!(await p.locator('#recordDialog').isVisible()),'explicit context clearing saved');current=await(await fetch(runtime.url+'api/state')).json();const cleared=current.records.find(r=>r.id===retest.id);assert.deepEqual([cleared.assistance,cleared.practice_relation,cleared.comparison_note],['','','']);await card().locator('.learning-compare > summary').click();assert.match(await card().locator('[data-learning-record="'+retest.id+'"]').innerText(),/帮助情况未记录/);
  checks.push('editing context retains untouched fields or explicitly clears them; immediate parent and legacy unknowns remain visible');
  if(proofDir){await fs.mkdir(proofDir,{recursive:true});await eventually(()=>p.locator('#toast').isHidden(),'saved feedback cleared before screenshots',5000)}
  const contrast=await card().evaluate(el=>{const luminance=raw=>{const values=raw.match(/[\d.]+/g).slice(0,3).map(Number).map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4});return values[0]*.2126+values[1]*.7152+values[2]*.0722};const ratio=(fg,bg)=>{const a=luminance(fg),b=luminance(bg);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};const title=el.querySelector('h3'),fact=el.querySelector('.learning-facts dd'),warning=el.querySelector('.learning-limit');return [ratio(getComputedStyle(title).color,getComputedStyle(el).backgroundColor),ratio(getComputedStyle(fact).color,getComputedStyle(fact.closest('.learning-facts')).backgroundColor),ratio(getComputedStyle(warning).color,getComputedStyle(warning).backgroundColor)]});assert.ok(contrast.every(r=>r>=4.5),'new comparison title, facts and warning text have readable contrast');
  for(const width of [360,400,1440]){await p.setViewportSize({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'learning page width '+width);assert.equal(await card().evaluate(el=>el.scrollWidth>el.clientWidth),false,'comparison width '+width);if(proofDir){await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(proofDir,'synthetic-viewport-'+width+'.png')});await p.screenshot({path:path.join(proofDir,'synthetic-learning-'+width+'.png'),fullPage:true});await card().screenshot({path:path.join(proofDir,'synthetic-comparison-'+width+'.png')})}}
  await p.locator('#childFilter').selectOption({label:second});assert.equal(await p.locator('[data-learning-case="'+original.id+'"]').count(),0);assert.match(await p.locator('.learning-journeys').innerText(),/OTHER_CHILD_LEARNING_CANARY/);await p.reload();await p.locator('nav [data-page="learning"]').click();await p.locator('#childFilter').selectOption({label:first});assert.equal((await p.locator('.learning-journeys').innerText()).includes('OTHER_CHILD_LEARNING_CANARY'),false);assert.deepEqual(errors,[]);
  checks.push('360 / 400 / 1440 responsive comparisons, readable text contrast, child filtering and reload persistence');
  const proof={checkedAt:new Date().toISOString(),passed:checks.length,checks,syntheticOnly:true,realPhoneTested:false};if(proofDir)await fs.writeFile(path.join(proofDir,'ui-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify(proof,null,2));
 }finally{await browser?.close();await runtime?.stop()}
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
