// Disposable synthetic demo only. Optional PLAYWRIGHT_MODULE, PLAYWRIGHT_CHANNEL,
// FAMILY_TEST_PYTHON and TASK_FOCUS_UI_PROOF_DIR. No family account or model calls.
const assert=require('node:assert/strict'),net=require('node:net');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {setTimeout:delay}=require('node:timers/promises'),{randomUUID}=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(check,label,timeout=12000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await delay(40)}throw Error('Timed out: '+label)}
async function demoServer(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 const proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let error='';proc.stdout.resume();proc.stderr.on('data',b=>error+=String(b));proc.on('error',e=>error=e.message);
 const url='http://127.0.0.1:'+port+'/',stop=async()=>{if(proc.exitCode!==null||proc.signalCode!==null)return;const done=once(proc,'exit');proc.kill('SIGINT');await Promise.race([done,delay(2500)]);if(proc.exitCode===null&&proc.signalCode===null){proc.kill('SIGKILL');await done}};
 try{await eventually(async()=>{if(proc.exitCode!==null)throw Error(error||'Demo exited');try{return(await fetch(url,{signal:AbortSignal.timeout(400)})).ok}catch{return false}},'isolated demo');return{url,stop}}catch(e){await stop();throw e}
}
const addDays=(day,n)=>{const date=new Date(day+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10)};
async function fit(p){
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal page overflow');
 assert.equal(await p.locator('dialog[open]').evaluateAll(xs=>xs.some(x=>x.scrollWidth>x.clientWidth)),false,'no horizontal form overflow');
 assert.equal(await p.locator('.task button:visible,#taskFocusForm button:visible').evaluateAll(xs=>xs.some(x=>x.getBoundingClientRect().height<44)),false,'action buttons have 44px touch targets');
}
async function proof(p,name){if(process.env.TASK_FOCUS_UI_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.TASK_FOCUS_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.TASK_FOCUS_UI_PROOF_DIR,name+'.png'),fullPage:false})}}
(async()=>{
 let browser;const results=[];
 try{
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  for(const width of [360,1440]){
   const server=await demoServer(),p=await browser.newPage({viewport:{width,height:900}}),errors=[],writes=[];
   p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/task/focus')writes.push(r.postDataJSON())});
   const read=async()=>await(await fetch(server.url+'api/state')).json(),post=async(path,body)=>{const state=await read(),r=await fetch(server.url+path,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify(body)});const value=await r.json();assert.equal(r.ok,true,JSON.stringify(value));return value};
   const ready=()=>eventually(()=>p.locator('.today-dashboard').isVisible(),'home ready'),tasks=async()=>{await p.locator('[data-page="tasks"]').first().click();await eventually(()=>p.locator('[data-view="等待中"]').isVisible(),'action list ready')};
   const card=id=>p.locator('[data-query-target="task:'+id+'"]'),form=p.locator('#taskFocusForm'),save=()=>form.locator('[type="submit"]').click();
   let id;
   const fresh=async()=>(await read()).tasks.find(t=>t.id===id),open=async()=>{const button=card(id).locator('[data-task-focus]');if(!await button.isVisible())await card(id).locator('summary').filter({hasText:'更多操作'}).click();await button.click();await eventually(()=>p.locator('#taskFocusDialog').isVisible(),'focus form open')};
   const saved=()=>eventually(async()=>!(await p.locator('#taskFocusDialog').isVisible()),'focus saved and dialog closed');
   try{
    const before=await read(),due=addDays(before.today,7),tomorrow=addDays(before.today,1),title='虚构材料核对 '+width,action='数学练习第 12—14 页，完成第 1、3、5 题。\n打印第 2—3 页回执，周五上学前带给老师。';
    await p.goto(server.url);await ready();await tasks();await p.locator('[data-new-task]').click();const collect=p.locator('#newTaskForm');await collect.locator('[name="child"]').selectOption({label:before.children[0].name});await collect.locator('[name="title"]').fill(title);await collect.locator('[name="due"]').fill(due);await collect.locator('[name="action"]').fill(action);await collect.locator('[name="source"]').fill('虚构学校原始通知');await collect.locator('[type="submit"]').click();await eventually(async()=>!(await p.locator('#newTaskDialog').isVisible())&&(await read()).tasks.some(t=>t.title===title),'new actionable task');id=(await read()).tasks.find(t=>t.title===title).id;
    const requirement=card(id).locator('.task-requirement');assert.equal(await requirement.isVisible(),true);assert.equal(await requirement.innerText(),action);assert.equal(await requirement.evaluate(el=>el.closest('details')===null),true);assert.equal(await card(id).locator('details').count(),1);assert.equal(await card(id).locator('details').getAttribute('open'),null);assert.match(await card(id).locator('summary').innerText(),/出处与历史/);assert.equal(await card(id).locator('details').textContent().then(t=>t.includes(action)),false);await fit(p);await proof(p,'action-visible-'+width);
    await open();await form.locator('[name="mode"]').selectOption('waiting');assert.equal(await form.locator('[name="waiting_for"]').getAttribute('required'),'');const count=writes.length;await save();assert.equal(writes.length,count,'empty waiting condition cannot submit');await form.locator('[name="next_action"]').fill('收到回复后，核对所需页码。');await form.locator('[name="waiting_for"]').fill('等老师确认回执版本');await form.locator('[name="review_on"]').fill(tomorrow);await fit(p);await proof(p,'waiting-form-'+width);await save();await saved();await eventually(async()=>await card(id).count()===0,'waiting item leaves next actions');assert.equal((await fresh()).due,due);assert.equal((await fresh()).focus.version,1);
    await p.locator('[data-view="等待中"]').click();assert.equal(await card(id).isVisible(),true);assert.match(await card(id).innerText(),/等老师确认回执版本/);await p.reload();await ready();await tasks();await p.locator('[data-view="等待中"]').click();assert.equal(await card(id).isVisible(),true,'waiting persists after reload');
    await open();await form.locator('[name="mode"]').selectOption('later');await form.locator('[name="review_on"]').fill(before.today);await save();await saved();await p.locator('[data-view="待跟进"]').click();assert.equal(await card(id).isVisible(),true,'due review returns to next actions');await p.locator('[data-page="home"]').first().click();assert.equal(await p.locator('.today-reviews [data-today-task="'+id+'"]').isVisible(),true);assert.equal(await card(id).count(),1,'review is not duplicated');assert.equal((await fresh()).due,due);await fit(p);await card(id).scrollIntoViewIfNeeded();await proof(p,'review-due-'+width);
    await open();await form.locator('[name="mode"]').selectOption('next');assert.equal(await form.locator('[name="review_on"]').inputValue(),'');await save();await saved();assert.equal((await fresh()).focus.mode,'next');assert.equal((await fresh()).focus.review_on,'');assert.equal(await p.locator('.today-reviews [data-today-task="'+id+'"]').count(),0);await tasks();assert.equal(await card(id).isVisible(),true);
    // A successful commit with a lost reply retries the same receipt, not a second change.
    await open();await form.locator('[name="mode"]').selectOption('waiting');await form.locator('[name="waiting_for"]').fill('等家庭讨论时间');await form.locator('[name="review_on"]').fill(tomorrow);const retryKey=await form.locator('[name="request_key"]').inputValue();let dropped=false;
    await p.route('**/api/task/focus',async route=>{if(!dropped){dropped=true;const response=await route.fetch();assert.equal(response.ok(),true);await route.abort('failed')}else await route.continue()});await save();await eventually(async()=>dropped&&(await form.locator('[type="submit"]').isEnabled())&&/输入已保留/.test(await p.locator('#taskFocusError').innerText()),'lost reply retains focus form');const committed=(await fresh()).focus;assert.equal(await form.locator('[name="request_key"]').inputValue(),retryKey);assert.equal(await form.locator('[name="waiting_for"]').inputValue(),'等家庭讨论时间');await save();await saved();await p.unroute('**/api/task/focus');assert.deepEqual((await fresh()).focus,committed,'retry does not advance version or timestamp');const retries=writes.filter(w=>w.request_key===retryKey);assert.equal(retries.length,2);assert.deepEqual(retries[0],retries[1]);
    // A second parent's newer arrangement must be reviewed without losing the local draft.
    await p.locator('[data-view="等待中"]').click();await open();await form.locator('[name="mode"]').selectOption('later');await form.locator('[name="next_action"]').fill('虚构保留草稿：饭后一起核对');await form.locator('[name="review_on"]').fill(before.today);const staleKey=await form.locator('[name="request_key"]').inputValue(),latest=await fresh();const external=await post('api/task/focus',{id,version:latest.focus.version,request_key:randomUUID(),mode:'waiting',next_action:'另一家长已联系老师',waiting_for:'等待新版本',review_on:tomorrow});await save();await eventually(()=>p.locator('#taskFocusReload').isVisible(),'concurrent update conflict');assert.equal(await form.locator('[name="next_action"]').inputValue(),'虚构保留草稿：饭后一起核对');assert.equal(await form.locator('[name="review_on"]').inputValue(),before.today);assert.equal((await fresh()).focus.version,external.focus.version);await fit(p);await proof(p,'focus-conflict-'+width);await p.locator('#taskFocusReload').click();await eventually(async()=>/另一家长已联系老师/.test(await p.locator('#taskFocusLatest').innerText()),'latest arrangement shown');assert.equal(Number(await form.locator('[name="version"]').inputValue()),external.focus.version);assert.notEqual(await form.locator('[name="request_key"]').inputValue(),staleKey);assert.equal(await form.locator('[name="mode"]').inputValue(),'later');assert.equal(await form.locator('[name="next_action"]').inputValue(),'虚构保留草稿：饭后一起核对');await save();await saved();assert.equal((await fresh()).focus.version,external.focus.version+1);
    await p.locator('[data-page="home"]').first().click();assert.equal(await p.locator('.today-reviews [data-today-task="'+id+'"]').isVisible(),true);await card(id).locator('[data-task-decisions]').click();await p.locator('#taskDecisionForm [name="status"][value="不参加"]').check();await p.locator('#taskDecisionForm [name="note"]').fill('虚构家庭决定：本次不参加');await p.locator('#taskDecisionForm [type="submit"]').click();await eventually(async()=>!(await p.locator('#taskDecisionDialog').isVisible())&&(await fresh()).update?.status==='不参加','review dismissed');assert.equal(await card(id).count(),0,'dismissed task absent from home and reviews');await p.reload();await ready();assert.equal(await card(id).count(),0);await tasks();await p.locator('[data-view="待跟进"]').click();assert.equal(await card(id).count(),0);await p.locator('[data-view="已搁置"]').click();assert.equal(await card(id).isVisible(),true);assert.equal(await card(id).locator('[data-task-focus],[data-check]').count(),0);
    const after=await read();assert.equal((await fresh()).due,due);assert.equal((await fresh()).action,action);assert.deepEqual(after.records,before.records);assert.deepEqual(after.rewards,before.rewards);assert.deepEqual(after.reading,before.reading);assert.deepEqual(errors,[]);await fit(p);await proof(p,'focus-dismissed-'+width);
    results.push({width,actionVisibleWithoutExpansion:true,waitingRequired:true,deadlineUnchanged:true,reviewResurfaces:true,nextRestores:true,retrySameKeyAndVersion:true,conflictPreservesDraft:true,dismissalNoReward:true,persistsAfterReload:true,noOverflow:true,pageErrors:0});
   }finally{await p.close();await server.stop()}
  }
  console.log(JSON.stringify({passed:results.length,results,syntheticOnly:true,phoneHardwareTested:false,proof:process.env.TASK_FOCUS_UI_PROOF_DIR||null},null,2));
 }finally{await browser?.close()}
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
