// Synthetic records only. All writes use a disposable real HTTP app; no model/device calls.
const assert=require('node:assert/strict'),net=require('node:net'),{spawn}=require('node:child_process'),{once}=require('node:events'),{randomUUID}=require('node:crypto'),{setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(f,label){const until=Date.now()+15000;while(Date.now()<until){if(await f())return;await delay(40)}throw Error('Timed out: '+label)}
async function server(){const s=net.createServer();s.listen(0,'127.0.0.1');await once(s,'listening');const port=s.address().port;await new Promise(r=>s.close(r));const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];const proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let error='';proc.stdout.resume();proc.stderr.on('data',b=>error+=b);const url='http://127.0.0.1:'+port+'/';const stop=async()=>{if(proc.exitCode!==null||proc.signalCode!==null)return;const ended=once(proc,'exit');proc.kill('SIGINT');await Promise.race([ended,delay(2500)]);if(proc.exitCode===null&&proc.signalCode===null){proc.kill('SIGKILL');await ended}};try{await eventually(async()=>{if(proc.exitCode!==null)throw Error(error);try{return(await fetch(url)).ok}catch{return false}},'demo');return{url,stop}}catch(e){await stop();throw e}}
const add=(day,n)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
async function fit(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('dialog[open]').evaluateAll(xs=>xs.some(x=>x.scrollWidth>x.clientWidth)),false);assert.equal(await p.locator('#calendarOccurrenceForm button:visible,#calendarOccurrenceForm input:visible,#calendarOccurrenceForm select:visible,#calendarOccurrenceForm summary:visible').evaluateAll(xs=>xs.some(x=>x.getBoundingClientRect().height<44)),false,'44px controls')}
async function proof(p,name){if(process.env.CALENDAR_OCCURRENCE_UI_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.CALENDAR_OCCURRENCE_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.CALENDAR_OCCURRENCE_UI_PROOF_DIR,name+'.png')})}}
(async()=>{let browser;const results=[];try{browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});for(const width of [360,1440]){const service=await server(),p=await browser.newPage({viewport:{width,height:900}}),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const read=async(path='api/state')=>await(await fetch(service.url+path)).json();const post=async(path,body,status=200)=>{const s=await read(),r=await fetch(service.url+path,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':s.token},body:JSON.stringify(body)}),v=await r.json();assert.equal(r.status,status,JSON.stringify(v));return v};const snapshot=async(day,end=day)=>(await read('api/calendar?start='+day+'&end='+end)).events;const f=p.locator('#calendarOccurrenceForm'),dialog=p.locator('#calendarOccurrenceDialog'),close=()=>p.locator('#calendarOccurrenceClose').click(),save=()=>p.locator('#calendarOccurrenceSave').click(),saved=()=>eventually(async()=>!await dialog.isVisible(),'save done');
try{const state=await read(),day=state.today,moved=add(day,24),id=randomUUID().replaceAll('-',''),slot='b'.repeat(16),base={id,version:0,child_ids:[state.children[0].id],title:'虚构：共读后讲一个发现',category:'family',day,start_time:'17:00',end_time:'17:20',location:'',note:'读一页，再讲一个发现。',status:'confirmed',repeat:'daily',until:add(day,2),repeat_days:[],extra_times:[{id:slot,start_time:'19:00',end_time:'19:20'}]};await post('api/calendar/save',base);
const navigate=async target=>{await p.locator('[data-page="calendar"]').first().click();await eventually(()=>p.locator('[data-agenda-date]').isVisible(),'calendar');await p.locator('[data-agenda-date]').fill(target);await p.locator('[data-agenda-date]').dispatchEvent('change');await eventually(()=>p.locator('#calendarDayDetails').textContent().then(s=>s.includes(target)),'selected day');await eventually(()=>p.locator('[data-calendar-once]').count().then(n=>n>0),'occurrences loaded')};const open=async(ident,target)=>{await p.locator('[data-calendar-once="'+ident+'"][data-occurrence-day="'+target+'"]').first().click();await eventually(()=>dialog.isVisible(),'occurrence dialog')};
await p.goto(service.url);await eventually(()=>p.locator('body[data-page=home] #task-group-homework').isVisible(),'home');await navigate(day);await p.locator('[data-calendar-child="'+state.children[0].id+'"]').click();await open(id+'.'+slot,day);assert.equal(await f.locator('[name=day]').inputValue(),day);await f.locator('[name=note]').fill('先保留这次输入');await close();await open(id+'.'+slot,day);assert.equal(await f.locator('[name=note]').inputValue(),'先保留这次输入');await f.locator('[name=day]').fill(moved);await f.locator('[name=start_time]').fill('18:00');await f.locator('[name=end_time]').fill('18:20');await fit(p);await proof(p,'reschedule-'+width);await save();await saved();assert.equal(await p.locator('[data-calendar-child="'+state.children[0].id+'"]').getAttribute('aria-pressed'),'true','child filter survives save');
let original=await snapshot(day,add(day,2));assert.equal(original.length,5);assert.equal(original.filter(e=>e.id===id&&e.day===day).length,1);let replacement=(await snapshot(moved))[0];assert.equal(replacement.occurrence.day,day);assert.equal(replacement.occurrence.history.length,1);const oid=replacement.id;assert.equal((await read()).today_calendar.inbox.find(x=>x.kind==='event'&&x.event.id===oid).closed,false);await open(oid,moved);await f.locator('details').evaluate(x=>x.open=true);assert.match(await p.locator('#calendarOccurrenceHistory').textContent(),/读一页/);await f.locator('[name=status]').selectOption('completed');await f.locator('[name=note]').fill('能说出自己的发现，家长确认这次已完成。');await save();await saved();replacement=(await snapshot(moved))[0];assert.equal(replacement.occurrence.history.length,2);assert.equal((await read()).today_calendar.inbox.find(x=>x.kind==='event'&&x.event.id===oid).closed,true);await p.locator('nav [data-page=tasks]').click();await p.locator('[data-task-box=已完成]').click();await open(oid,moved);assert.equal(await f.locator('[name=status]').inputValue(),'completed');await close();await navigate(moved);
// Same occurrence, simultaneous parent edit: stale save must not overwrite; refresh keeps typed input.
await open(oid,moved);await f.locator('[name=note]').fill('保留我的补充');let o=replacement.occurrence;await post('api/calendar/occurrence',{series_id:o.series_id,series_version:o.series_version,origin_day:o.day,slot_id:o.slot_id,version:o.version,day:moved,start_time:'18:00',end_time:'18:20',status:'cancelled',note:'另一位家长取消了本次'});await save();await eventually(()=>p.locator('#calendarOccurrenceRefresh').isVisible(),'conflict');assert.equal(await f.locator('[name=note]').inputValue(),'保留我的补充');await p.locator('#calendarOccurrenceRefresh').click();await eventually(()=>p.locator('#calendarOccurrenceStatus').textContent().then(t=>t.includes('最新记录：已取消')),'refreshed conflict');assert.equal(await f.locator('[name=note]').inputValue(),'保留我的补充');await proof(p,'conflict-'+width);assert.equal(await f.locator('[name=status]').inputValue(),'cancelled','untouched prefill follows co-parent; note cannot silently undo cancellation');await save();await saved();assert.equal((await snapshot(moved))[0].version,4);assert.equal((await snapshot(moved))[0].status,'cancelled');
// Drop a committed response, close/reopen and retry the exact same body. No duplicate history.
let drop=true;await p.route('**/api/calendar/occurrence',async route=>{requests.push(route.request().postData());if(drop){drop=false;await route.fetch();await route.abort('failed')}else await route.continue()});await open(oid,moved);await f.locator('[name=status]').selectOption('cancelled');await f.locator('[name=note]').fill('本次不参加');await save();await eventually(()=>p.locator('#calendarOccurrenceStatus').textContent().then(t=>t.includes('请重试同一次保存')),'lost reply');assert.equal(await f.locator('[name=note]').isDisabled(),true);await close();await p.locator('[data-calendar-ask]').click();await p.locator('[data-calendar-resume]').click();assert.equal(await dialog.isVisible(),true);await save();await saved();assert.equal(requests.length,2);assert.equal(requests[0],requests[1]);assert.equal((await snapshot(moved))[0].version,5);await p.unroute('**/api/calendar/occurrence');
// Update the template and preserve already handled records; untouched future dates adopt the edit.
let master=(await read()).today_calendar.inbox.find(x=>x.kind==='event'&&x.event.id===id).event;await post('api/calendar/save',{...base,version:master.version,start_time:'16:00',end_time:'16:20'});assert.equal((await snapshot(add(day,1))).find(e=>e.id===id).start_time,'16:00');assert.equal((await snapshot(moved))[0].start_time,'18:00');await post('api/calendar/save',{...base,version:2,repeat:'none',until:'',extra_times:[]},409);
await p.reload();await eventually(()=>p.locator('body[data-page=home] #task-group-homework').isVisible(),'reopen');await p.locator('nav [data-page=tasks]').click();await p.locator('[data-task-box=已搁置]').click();await open(oid,moved);assert.equal(await f.locator('[name=status]').inputValue(),'cancelled');await f.locator('details').evaluate(x=>x.open=true);assert.match(await p.locator('#calendarOccurrenceHistory').textContent(),/另一位家长取消/);assert.doesNotMatch(await p.locator('#calendarOccurrenceHistory').textContent(),/T\d\d:\d\d:.*\+00:00/);const actionBox=await p.locator('#calendarOccurrenceSave').boundingBox();assert.ok(actionBox&&actionBox.y+actionBox.height<=900,'save remains visible with long history');await fit(p);await proof(p,'history-'+width);await close();
// A changed template child must not be silently rebased into a different child's occurrence.
await navigate(add(day,1));await open(id,add(day,1));await f.locator('[name=note]').fill('旧孩子输入保留');await post('api/calendar/save',{...base,version:2,child_ids:[state.children[1].id],start_time:'16:00',end_time:'16:20'});await save();await eventually(()=>p.locator('#calendarOccurrenceRefresh').isVisible(),'master conflict');await p.locator('#calendarOccurrenceRefresh').click();await eventually(()=>p.locator('#calendarOccurrenceStatus').textContent().then(t=>t.includes('参加孩子已变化')),'scope conflict');assert.equal(await f.locator('[name=note]').inputValue(),'旧孩子输入保留');assert.equal(await p.locator('#calendarOccurrenceSave').isDisabled(),true);await close();
const denied=await fetch(service.url+'api/calendar/occurrence',{method:'POST',headers:{'Content-Type':'application/json'},body:requests[0]});assert.equal(denied.status,403);const childDenied=await fetch(service.url+'api/calendar/occurrence',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token,'X-Child-CSRF':'synthetic-child'},body:requests[0]});assert.equal(childDenied.status,403);assert.equal((await snapshot(moved))[0].version,5);assert.equal(errors.length,0,errors.join('\n'));results.push({width,passed:true,singleSlotOnly:true,moveAcrossMonth:true,completionAndCancel:true,historySurvivesReload:true,exactRetry:true,conflictInputPreserved:true,childChangeNotRebased:true,pageErrors:0});
}finally{await p.close();await service.stop()}}console.log(JSON.stringify({passed:results.length,results,syntheticOnly:true,realHTTP:true,realPhone:false},null,2))}finally{await browser?.close()}})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
