// Synthetic browser + real local API checks; no real family, CLI or model calls.
const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events'),net=require('node:net'),{setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function until(check,label){for(let i=0;i<200;i++){if(await check())return;await delay(50)}throw Error(label)}
async function fits(page){
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no document overflow');
 assert.equal(await page.locator('dialog[open]').evaluateAll(items=>items.some(d=>d.scrollWidth>d.clientWidth)),false,'no dialog overflow');
 assert.equal(await page.locator('[data-school-record-agent]:visible,[data-school-record-task]:visible,#recordForm button:visible').evaluateAll(items=>items.some(b=>b.getBoundingClientRect().height<40)),false,'school learning actions are usable touch targets');
}
async function proof(page,name){if(process.env.AGENT_UI_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.AGENT_UI_PROOF_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.AGENT_UI_PROOF_DIR,name+'.png')})}}
const fixture=String.raw`
import tempfile,os,json,datetime,io,struct,zlib
from pathlib import Path
with tempfile.TemporaryDirectory(prefix='synthetic-agent-ui-') as tmp:
 os.environ['FAMILY_DATA']=tmp
 import app,family_agent
 app.DATA=Path(tmp);app.DB=app.DATA/'family.sqlite3'
 docs={'家庭运行规则.md':'| child-1 | 示例星星 | — | 9岁 | 三年级 |\n| child-2 | 示例小宇 | — | 12岁 | 六年级 |\n'}
 app.read=lambda name:docs.get(name,'')
 app.connect().close()
 today=datetime.datetime.now(family_agent.TZ).date().isoformat()
 app.save_record(dict(child='示例小宇',day=today,category='学习进展',title='虚构阅读尝试',note='还需要一次提示',subject='语文',source='家长观察'))
 app.save_record(dict(child='示例星星',day=today,category='学习进展',title='虚构时间管理依据',note='最近记录显示需要一次提示',subject='数学',source='家长观察'))
 app.save_record(dict(child='示例小宇',day=today,category='学习进展',title='SIBLING_SAME_SOURCE_CANARY',note='另一孩子的同来源记录，不能代替当前孩子。',source='message:synthetic:0'))
 (app.DATA/'agent.json').write_text(json.dumps({'enabled':True,'sources':[{'id':'synthetic','platform':'wechat','child_id':'child-1','name':'虚构原件通知','cursor':'','enabled':True}]}))
 store=app.agent_store();now=datetime.datetime.now(family_agent.TZ)
 def chunk(kind,data): return struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data)&0xffffffff)
 pixels=b''.join(b'\x00'+bytes([30+(row%2)*40,120,220,255])*96 for row in range(64))
 png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',96,64,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(pixels))+chunk(b'IEND',b'')
 existing_upload=app.save_upload(io.BytesIO(png),len(png),'synthetic-existing.png')
 messages=[dict(id=str(i),time=now.isoformat(),kind='image',sender='虚构老师',text='虚构老师通知：请准备观察材料。<img src=x onerror=alert(1)>',unread=True) for i in range(4)]
 for width in (360,1440): messages.append(dict(id='image:'+str(width),time=now.isoformat(),kind='image',sender='虚构老师',text='虚构图片消息说明：原件内容尚未读取。',unread=True));messages.append(dict(id='original:'+str(width),time=now.isoformat(),kind='image',sender='虚构老师',text='虚构原件关联通知 '+str(width)+'：请核对图片附件内容。',unread=True))
 store.ingest(dict(source_id='synthetic',expected_cursor='',cursor='cursor-1',checked_at=now.isoformat(),last_message_time=now.isoformat(),messages=messages,error=''))
 for i in range(4):
  store._save('school:'+str(i),'fixture',[dict(child_id='child-1',kind='school',title='虚构学校准备 '+str(i),body='核对后准备观察材料。',due=today,evidence=[{'ref':'message:synthetic:'+str(i),'text':'虚构老师通知：请准备观察材料。<img src=x onerror=alert(1)>'}])],now)
 store._save('record:1','fixture',[dict(child_id='child-2',kind='care',title='虚构学习跟进',body='请孩子讲讲自己的想法。',record_id=1,evidence=[{'ref':'record:1','text':'还需要一次提示'}])],now)
 for width in (360,1440):
  store._save('care:planned:'+str(width),'fixture',[dict(child_id='child-1',kind='care',title='虚构时间管理小动作 '+str(width),body='今晚用计时器完成一轮数学练习。',record_id=2,plan={'goal':'把数学练习拆成一轮可完成的小步骤','why_now':'最近记录显示需要一次提示','estimated_minutes':25,'review_on':today},evidence=[{'ref':'record:2','text':'最近记录显示需要一次提示'}])],now)
  image_title='待核对：[image：内容未读取，仅保留消息说明]'
  store._save('school:image:'+str(width),'fixture',[dict(child_id='child-1',kind='school',title=image_title,body='genericbody',due=today,evidence=[{'ref':'message:synthetic:image:'+str(width),'text':'虚构图片消息说明：原件内容尚未读取。'}])],now)
  store._save('school:original:'+str(width),'fixture',[dict(child_id='child-1',kind='school',title='虚构原件关联通知 '+str(width),body='请核对图片附件内容。',due=today,evidence=[{'ref':'message:synthetic:original:'+str(width),'text':'虚构原件关联通知 '+str(width)+'：请核对图片附件内容。'}])],now)
 store._runtime('ready',now)
 app.prepare_assets()
 server=app.ThreadingHTTPServer(('127.0.0.1',int(os.environ['TEST_AGENT_PORT'])),app.Handler)
 try:server.serve_forever()
 except KeyboardInterrupt:pass
 finally:server.server_close()
`;
(async()=>{let proc,browser;try{
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));const url='http://127.0.0.1:'+port+'/',env={...process.env,TEST_AGENT_PORT:String(port)};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['-c',fixture],{cwd:__dirname,env,stdio:['ignore','ignore','pipe']});let errors='';proc.stderr.on('data',b=>errors+=b);proc.on('error',e=>errors+=e.message);
 await until(async()=>{if(proc.exitCode!==null)throw Error(errors);try{return(await fetch(url)).ok}catch{return false}},'server startup');const state=async()=>await(await fetch(url+'api/state')).json();
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
 for(const width of [360,1440]){
  const page=await browser.newPage({viewport:{width,height:820}}),pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));await page.goto(url);await page.locator('.today-dashboard').waitFor();
  assert.equal(await page.locator('[data-today-child="child-2"] [data-agent-item]').count(),0,'care reminders stay off the school summary');assert.equal(await page.locator('[data-today-child="child-1"] [data-followup="1"]').count(),0);
  await fits(page);
  const imageTitle='待核对：[image：内容未读取，仅保留消息说明]';await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();let imageState=await state(),imageItem=imageState.agent.items.find(x=>x.kind==='school'&&x.state==='pending'&&x.title===imageTitle);assert.ok(imageItem,'image placeholder school item is pending');const imageCard=page.locator('[data-agent-item="'+imageItem.id+'"]');assert.equal(await imageCard.locator('h3').innerText(),'原件内容待核对');assert.equal(await imageCard.locator('[data-agent-accept]').innerText(),'补充具体要求');await imageCard.locator('[data-agent-accept]').click();await page.locator('#agentDialog').waitFor();const imageForm=page.locator('#agentForm');assert.equal(await imageForm.locator('[name="title"]').inputValue(),'');assert.equal(await imageForm.locator('[name="body"]').inputValue(),'');assert.equal(await imageForm.locator('[name="title"]').getAttribute('required'),'');assert.equal(await imageForm.locator('[name="body"]').getAttribute('required'),'');assert.match(await imageForm.innerText(),/原件内容尚未读取，请先核对并填写具体事项。也可以明确安排先核对原件。/);await imageForm.locator('details > summary').click();assert.match(await imageForm.innerText(),/虚构图片消息说明：原件内容尚未读取/);const imageRecordsBefore=imageState.records.length,imageTasksBefore=imageState.tasks.length;await imageForm.locator('[name="title"]').fill('虚构核对后的具体事项 '+width);await imageForm.locator('[name="body"]').fill('虚构明确动作：先核对图片原件，再按通知准备材料。');await imageForm.locator('[type="submit"]').click();await until(async()=>!(await page.locator('#agentDialog').isVisible()),'image placeholder accepted');const imageAfter=await state(),acceptedImage=imageAfter.agent.items.find(x=>x.id===imageItem.id),imageTask=imageAfter.tasks.find(t=>t.title==='虚构核对后的具体事项 '+width);assert.equal(acceptedImage.state,'accepted');assert.ok(imageTask,'accepted image source creates school task');assert.equal(imageAfter.records.length,imageRecordsBefore,'accepting image source creates no learning record');assert.equal(imageAfter.tasks.length,imageTasksBefore+1,'accepting image source creates exactly one task');assert.match(imageTask.source,/message:synthetic:image:/);assert.equal(imageTask.original_status,'待跟进');await page.locator('[data-page="tasks"]').first().click();const imageStudyButton=page.locator('[data-study-task-add="'+imageTask.id+'"]');await imageStudyButton.waitFor();assert.equal(await imageStudyButton.count(),1,'accepted source task can enter today study');await page.locator('[data-page="home"]').first().click();await page.locator('.today-dashboard').waitFor();
  // Original-message review is scoped to one child and one message; it must not create a learning fact.
  const originalRef='message:synthetic:original:'+width,original=(await state()).agent.items.find(x=>x.kind==='school'&&x.state==='pending'&&x.evidence?.some(e=>e.ref===originalRef));assert.ok(original,'synthetic original-message school item is pending');const originalBase=await state(),existing=originalBase.uploads.find(x=>x.name==='synthetic-existing.png'),originalIDs={child_id:'child-1',source_id:'synthetic',message_id:'original:'+width};assert.ok(existing,'unlinked existing image is available');
  const readOriginal=async childID=>{const query=new URLSearchParams({...originalIDs,child_id:childID}),response=await fetch(url+'api/agent/message?'+query);return {status:response.status,value:await response.json()}};
  const changeOriginal=async (attachmentID,action)=>{const response=await fetch(url+'api/agent/message/attachment',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':originalBase.token},body:JSON.stringify({...originalIDs,attachment_id:attachmentID,action})});return {status:response.status,value:await response.json()}};
  let originalView=await readOriginal('child-1');assert.equal(originalView.status,200);assert.equal(originalView.value.child_id,'child-1');assert.equal(originalView.value.source_id,'synthetic');assert.equal(originalView.value.message_id,'original:'+width);assert.equal(originalView.value.message.unread,true);assert.deepEqual(originalView.value.attachments,[]);const wrongChild=await readOriginal('child-2');assert.notEqual(wrongChild.status,200,'another child cannot read this message');
  const originalCard=page.locator('[data-agent-item="'+original.id+'"]'),originalButton=originalCard.locator('[data-school-original-ref="'+originalRef+'"][data-school-original-child="child-1"]');await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();await originalButton.waitFor();await originalButton.click();const originalDialog=page.locator('#schoolOriginalDialog');await originalDialog.waitFor();const originalFiles=originalDialog.locator('[data-school-original-files]'),originalSelect=originalDialog.locator('[name="attachment_id"]');await originalFiles.waitFor();await originalSelect.waitFor();assert.equal(await originalFiles.count(),1);assert.ok(await originalSelect.locator('option[value="'+existing.id+'"]').count(),'existing original is selectable');await fits(page);await proof(page,'school-original-open-'+width);
  await originalSelect.selectOption(existing.id);await originalDialog.locator('[data-school-original-attach]').click();await until(async()=>originalDialog.locator('[data-school-original-detach="'+existing.id+'"]').isVisible(),'existing original attached');originalView=await readOriginal('child-1');assert.deepEqual(originalView.value.attachments.map(x=>x.id),[existing.id]);assert.equal(originalView.value.message.unread,true);const afterExisting=await state();assert.deepEqual(afterExisting.records,originalBase.records);assert.deepEqual(afterExisting.rewards,originalBase.rewards);const linkedImage=originalFiles.locator('img').first();await linkedImage.waitFor();await until(async()=>linkedImage.evaluate(img=>img.complete&&img.naturalWidth===96&&img.naturalHeight===64),'linked existing image decoded');
  const duplicate=await changeOriginal(existing.id,'attach');assert.equal(duplicate.status,200);assert.deepEqual(duplicate.value.attachments.map(x=>x.id),[existing.id],'repeated association stays one link');await originalDialog.locator('[data-school-original-detach="'+existing.id+'"]').click();await until(async()=>!(await originalDialog.locator('[data-school-original-detach="'+existing.id+'"]').count()),'existing original detached');originalView=await readOriginal('child-1');assert.deepEqual(originalView.value.attachments,[]);assert.ok((await state()).uploads.some(x=>x.id===existing.id),'detaching leaves uploaded file available');assert.equal(originalView.value.message.unread,true);
  const uploadCalls=[],attachmentCalls=[],newPNG=Buffer.from(await (await fetch(url+'upload/'+existing.id)).arrayBuffer());await page.route('**/api/upload',async route=>{uploadCalls.push(route.request().headers()['x-file-name']||'');await route.continue()});await page.route('**/api/agent/message/attachment',async route=>{attachmentCalls.push(route.request().postDataJSON());if(attachmentCalls.length===1)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构原件关联暂时失败'})});await route.continue()});await originalDialog.locator('[data-school-original-upload]').setInputFiles({name:'synthetic-message-'+width+'.png',mimeType:'image/png',buffer:newPNG});await until(async()=>originalDialog.locator('[data-school-original-retry]').isVisible(),'association retry is offered');assert.equal(uploadCalls.length,1,'failed association does not retry upload');const uploaded=(await state()).uploads.find(x=>x.name==='synthetic-message-'+width+'.png');assert.ok(uploaded,'uploaded original survives association failure');assert.equal(attachmentCalls.length,1);await originalDialog.locator('[data-school-original-retry]').click();await until(async()=>originalDialog.locator('[data-school-original-detach="'+uploaded.id+'"]').isVisible(),'uploaded original association retried');assert.equal(uploadCalls.length,1,'retry reuses uploaded id');assert.equal(attachmentCalls.length,2);assert.equal(attachmentCalls[1].attachment_id,uploaded.id);originalView=await readOriginal('child-1');assert.deepEqual(originalView.value.attachments.map(x=>x.id),[uploaded.id]);assert.equal(originalView.value.message.unread,true);const uploadedImage=originalFiles.locator('img').first();await uploadedImage.waitFor();await until(async()=>uploadedImage.evaluate(img=>img.complete&&img.naturalWidth===96&&img.naturalHeight===64),'linked uploaded image decoded');await fits(page);await proof(page,'school-original-retry-'+width);
  await originalDialog.locator('[data-school-original-detach="'+uploaded.id+'"]').click();await until(async()=>!(await originalDialog.locator('[data-school-original-detach="'+uploaded.id+'"]').count()),'uploaded original detached');originalView=await readOriginal('child-1');assert.deepEqual(originalView.value.attachments,[]);assert.ok((await state()).uploads.some(x=>x.id===uploaded.id),'detached upload remains in整理资料');assert.deepEqual((await state()).records,originalBase.records);const lostName='synthetic-lost-response-'+width+'.png',lostUploadCalls=[];await page.route('**/api/upload',async route=>{lostUploadCalls.push(route.request().headers()['x-file-name']||'');const response=await route.fetch();await route.abort('connectionreset')});await originalDialog.locator('[data-school-original-upload]').setInputFiles({name:lostName,mimeType:'image/png',buffer:newPNG});await until(async()=>originalDialog.locator('[name="attachment_id"] option').filter({hasText:lostName}).count().then(n=>n===1),'saved upload returns after lost receipt');assert.equal(lostUploadCalls.length,1,'lost upload receipt does not cause a second upload');const lostUploaded=(await state()).uploads.find(x=>x.name===lostName);assert.ok(lostUploaded,'lost upload remains available');assert.deepEqual((await state()).records,originalBase.records);await originalDialog.locator('[name="attachment_id"]').selectOption(lostUploaded.id);await originalDialog.locator('[data-school-original-attach]').click();await until(async()=>originalDialog.locator('[data-school-original-detach="'+lostUploaded.id+'"]').isVisible(),'saved upload can be associated after lost receipt');assert.equal(lostUploadCalls.length,1);await originalDialog.locator('[data-school-original-detach="'+lostUploaded.id+'"]').click();await until(async()=>!(await originalDialog.locator('[data-school-original-detach="'+lostUploaded.id+'"]').count()),'lost upload detached');await page.unroute('**/api/upload');await page.unroute('**/api/agent/message/attachment');await originalDialog.locator('[data-school-original-close]').click();await page.reload();await page.locator('.today-dashboard').waitFor();await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();const restored=page.locator('[data-agent-item="'+original.id+'"]');await restored.waitFor();assert.equal(await restored.locator('[data-school-original-ref="'+originalRef+'"][data-school-original-child="child-1"]').count(),1,'detached message returns to整理');await fits(page);await proof(page,'school-original-restored-'+width);
  await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();const before=await state(),school=before.agent.items.find(x=>x.kind==='school'&&x.state==='pending'&&!x.needs_task_details&&/^虚构学校准备 /.test(x.title)),schoolID=school?.id,sourceButton=page.locator('[data-agent-item="'+schoolID+'"] [data-school-record-agent]').first(),ref=school?.evidence?.[0]?.ref;assert.ok(school&&schoolID&&ref,'normal school source remains pending after placeholder acceptance')
  assert.ok(school&&school.kind==='school');
  // A malformed source cannot fall through to the general form's default child.
  await sourceButton.evaluate(b=>b.setAttribute('data-school-record-agent',''));
  await page.locator('[data-school-record-agent=""]').click();await delay(150);
  assert.equal(await page.locator('#recordDialog').isVisible(),false,'empty source ID never opens a default-child record');
  assert.equal((await state()).records.length,before.records.length);
  await page.reload();await page.locator('.today-dashboard').waitFor();await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();
  await page.locator('[data-school-record-agent="'+schoolID+'"]').click();await page.locator('#recordDialog').waitFor();
  const record=page.locator('#recordForm');
  assert.equal(await record.locator('[name="child"]').inputValue(),'示例星星');
  assert.equal(await record.locator('[name="category"]').inputValue(),'学习进展');
  assert.deepEqual(await record.locator('[name="category"]').evaluate(select=>[...select.options].map(option=>option.value)),['学习进展','成绩'],'school material can explicitly become a score record');
  assert.equal(await record.locator('[name="source"]').inputValue(),ref);
  assert.equal(await record.locator('[name="day"]').inputValue(),'','notification due is not the actual learning date');
  assert.equal(await record.locator('[name="related_record_id"]').inputValue(),'');
  assert.equal(await record.locator('[name="followup_kind"]').inputValue(),'');
  assert.equal(await record.locator('[name="assistance"]').inputValue(),'');
  const material=await record.locator('[name="note"]').inputValue();
  assert.match(material,/虚构老师通知：请准备观察材料/);assert.match(material,/待核对/);assert.ok(material.includes('<img src=x onerror=alert(1)>'));
  assert.equal(await page.locator('#recordDialog img').count(),0);
  assert.equal((await state()).records.length,before.records.length,'opening a school source does not fabricate a learning fact');
  await record.locator('[name="day"]').fill(before.today);await record.locator('[name="note"]').fill(material+'\n虚构家长补记：实际表现还要听孩子说明。');
  const attempts=[];let recordPhase=0;
  await page.route('**/api/record',async route=>{
   attempts.push(route.request().postDataJSON());recordPhase++;
   if(recordPhase===1)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构学校记录网络故障'})});
   if(recordPhase===2){const response=await route.fetch();assert.equal(response.status(),200);return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构学校记录回执丢失'})})}
   await route.continue();
  });
  await record.locator('[type="submit"]').click();await until(async()=>/虚构学校记录网络故障/.test(await page.locator('#recordError').innerText()),'school save failure visible');
  assert.equal((await state()).records.length,before.records.length);assert.equal(await record.locator('[name="source"]').inputValue(),ref);assert.match(await record.locator('[name="note"]').inputValue(),/虚构家长补记/);
  await fits(page);await proof(page,'school-record-retry-'+width);
  await record.locator('[type="submit"]').click();await until(async()=>/虚构学校记录回执丢失/.test(await page.locator('#recordError').innerText()),'lost receipt visible');
  assert.equal((await state()).records.filter(r=>r.child==='示例星星'&&r.source===ref).length,1,'unknown response already saved exactly once');
  await record.locator('[type="submit"]').click();await until(async()=>!(await page.locator('#recordDialog').isVisible()),'same source request retried');await page.unroute('**/api/record');
  assert.equal(attempts.length,3);assert.ok(attempts[0].request_key);assert.deepEqual(attempts[1],attempts[0]);assert.deepEqual(attempts[2],attempts[0]);
  let current=await state();const schoolRecord=current.records.find(r=>r.child==='示例星星'&&r.source===ref);assert.ok(schoolRecord);
  assert.equal(current.records.length,before.records.length+1);assert.deepEqual(current.tasks,before.tasks,'school record does not create or complete a task');
  const learning=()=>page.locator('[data-learning-case="'+schoolRecord.id+'"]');await until(()=>learning().isVisible(),'saved school record stays in its learning case');
  assert.equal((await page.locator('.learning-journeys').innerText()).includes('SIBLING_SAME_SOURCE_CANARY'),false,'same source from a sibling cannot be selected or shown as this child case');
  assert.doesNotMatch(await learning().innerText(),/尚无复测|还没有复测|订正 0|复测 0/,'ordinary school context does not force a correction/retest path');
  await proof(page,'school-learning-case-'+width);
  await page.locator('[data-page="home"]').first().click();await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();
  const first=page.locator('[data-agent-accept="'+schoolID+'"]');await first.click();await page.locator('#agentDialog').waitFor();await page.locator('#agentForm [name="title"]').fill('虚构家长核对 '+width);await page.locator('#agentForm [name="body"]').fill('带一本笔记本');
  await page.route('**/api/agent/action',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构网络暂不可用'})}),{times:1});
  await page.locator('#agentForm [type="submit"]').click();await until(()=>page.locator('#agentError').textContent().then(t=>t.includes('虚构网络')),'failed save visible');assert.equal(await page.locator('#agentForm [name="body"]').inputValue(),'带一本笔记本');
  assert.equal(await page.locator('#agentDialog').evaluate(d=>d.scrollWidth>d.clientWidth),false);
  await proof(page,'agent-form-'+width);
  await page.locator('#agentForm [type="submit"]').click();await until(()=>page.locator('#agentDialog').isVisible().then(v=>!v),'saved');await page.reload();await page.locator('.today-dashboard').waitFor();
  const saved=await state();assert.equal(saved.tasks.filter(t=>t.title==='虚构家长核对 '+width).length,1);assert.equal(saved.tasks.find(t=>t.title==='虚构家长核对 '+width).child,'示例星星');
  const acceptedTask=saved.tasks.find(t=>t.title==='虚构家长核对 '+width);
  await page.locator('[data-page="tasks"]').first().click();await page.locator('[data-school-record-task="'+acceptedTask.id+'"]').click();await until(()=>learning().isVisible(),'accepted task opens existing same-source learning case');
  assert.equal(await page.locator('#recordDialog').isVisible(),false);assert.equal((await state()).records.filter(r=>r.child==='示例星星'&&r.source===ref).length,1);
  await learning().locator('[data-followup-kind="补充观察"]').click();await page.locator('#recordDialog').waitFor();
  assert.ok((await record.locator('[name="category"]').evaluate(select=>[...select.options].map(option=>option.value))).includes('家长观察'),'ordinary followup restores the full record categories');
  assert.equal(await record.locator('[name="child"]').inputValue(),'示例星星');assert.equal(await record.locator('[name="related_record_id"]').inputValue(),String(schoolRecord.id));assert.equal(await record.locator('[name="followup_kind"]').inputValue(),'补充观察');
  await record.locator('[name="day"]').fill(saved.today);await record.locator('[name="title"]').fill('虚构孩子解释 '+width);await record.locator('[name="note"]').fill('孩子说想先画出观察到的形状；这次没有核对是否完成。');
  await record.locator('[type="submit"]').click();await until(async()=>!(await page.locator('#recordDialog').isVisible()),'child explanation appended');
  current=await state();const observation=current.records.find(r=>r.title==='虚构孩子解释 '+width);assert.equal(observation.related_record_id,schoolRecord.id);assert.equal(observation.child,schoolRecord.child);assert.equal(observation.followup_kind,'补充观察');assert.deepEqual(current.tasks.find(t=>t.id===acceptedTask.id),acceptedTask);
  // A second source begins from an existing task so all task feedback must carry over.
  const pendingSchool=current.agent.items.find(x=>x.kind==='school'&&x.state==='pending'&&!x.needs_task_details&&/^虚构学校准备 /.test(x.title)),token=current.token;assert.ok(pendingSchool,'a normal pending school source remains for task feedback');
  const accept=await fetch(url+'api/agent/action',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':token},body:JSON.stringify({id:pendingSchool.id,action:'accept',title:'虚构已反馈事项 '+width,body:'核对原通知，和孩子商量观察材料。'})});assert.equal(accept.status,200);const secondTaskID=(await accept.json()).task_id,secondRef=pendingSchool.evidence[0].ref;
  await page.reload();await page.locator('.today-dashboard').waitFor();await page.locator('[data-page="tasks"]').first().click();
  for(const [status,note] of [['待跟进','虚构第一条反馈：还要核对当天安排。'],['进行中','虚构第二条反馈：孩子想先画图，请听他解释。']]){
   await page.locator('[data-task="'+secondTaskID+'"]').click();await page.locator('#taskDialog').waitFor();await page.locator('#taskForm [name="status"]').selectOption(status);await page.locator('#taskForm [name="note"]').fill(note);await page.locator('#taskForm [type="submit"]').click();await until(async()=>!(await page.locator('#taskDialog').isVisible()),'task feedback saved');
  }
  const taskBeforeRecord=(await state()).tasks.find(t=>t.id===secondTaskID);
  await page.locator('[data-school-record-task="'+secondTaskID+'"]').click();await page.locator('#recordDialog').waitFor();
  assert.equal(await record.locator('[name="source"]').inputValue(),secondRef);assert.equal(await record.locator('[name="child"]').inputValue(),'示例星星');assert.equal(await record.locator('[name="day"]').inputValue(),'');
  const feedback=await record.locator('[name="note"]').inputValue();assert.match(feedback,/虚构老师通知：请准备观察材料/);assert.match(feedback,/虚构第一条反馈/);assert.match(feedback,/虚构第二条反馈/);assert.match(feedback,/待核对/);assert.doesNotMatch(feedback,/已经完成|已经掌握|孩子未做|孩子没有做/);
  await record.locator('[name="day"]').fill(current.today);await fits(page);await proof(page,'school-task-material-'+width);
  await page.route('**/api/record',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'虚构关闭前回执未知'})})},{times:1});
  await record.locator('[type="submit"]').click();await until(async()=>/虚构关闭前回执未知/.test(await page.locator('#recordError').innerText()),'task-source receipt unknown');
  await page.locator('[data-close="recordDialog"]').click();await page.locator('[data-school-record-task="'+secondTaskID+'"]').click();
  const afterUnknown=await state(),taskRecord=afterUnknown.records.find(r=>r.child==='示例星星'&&r.source===secondRef);assert.ok(taskRecord);await until(()=>page.locator('[data-learning-case="'+taskRecord.id+'"]').isVisible(),'fresh state recovers an unknown saved receipt into existing case');
  assert.equal(await page.locator('#recordDialog').isVisible(),false);assert.equal(afterUnknown.records.filter(r=>r.child==='示例星星'&&r.source===secondRef).length,1);assert.deepEqual(afterUnknown.tasks.find(t=>t.id===secondTaskID),taskBeforeRecord);
  await page.locator('[data-page="home"]').first().click();await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();
  await page.locator('[data-followup="1"]').click();await page.locator('#recordDialog').waitFor();assert.equal(await page.locator('#recordForm [name="child"]').inputValue(),'示例小宇');assert.equal(await page.locator('#recordForm [name="related_record_id"]').inputValue(),'1');await page.locator('[data-close="recordDialog"]').click();
  await page.locator('.agent-status details summary').click();assert.equal(await page.locator('.agent-item img').count(),0);assert.match(await page.locator('.agent-status').innerText(),/上次整理/);
  await fits(page);await proof(page,'agent-'+width);
  // Planned care is a separate synthetic item: approval edits are visible, retry keeps the same form/id, and defer keeps a parent-chosen date.
  const planned=page.locator('[data-agent-item]').filter({hasText:'虚构时间管理小动作 '+width});await planned.scrollIntoViewIfNeeded();await proof(page,'planned-care-'+width);assert.match(await planned.innerText(),/具体动作|目标：|为什么现在：|25 分钟/);const plannedID=await planned.getAttribute('data-agent-item');await planned.locator('[data-agent-accept]').click();await page.locator('#agentDialog').waitFor();assert.equal(await page.locator('#agentForm [name="review_on"]').inputValue(),current.today);await page.locator('#agentForm [name="title"]').fill('虚构已核对的时间安排 '+width);await page.locator('#agentForm [name="body"]').fill('19:00 开始，完成一轮后记录实际分钟数');await page.locator('#agentForm [name="estimated_minutes"]').fill('30');await page.route('**/api/agent/action',async r=>{await r.fetch();await r.abort('connectionreset')},{times:1});await page.locator('#agentForm [type="submit"]').click();await until(()=>page.locator('#agentError').textContent().then(t=>Boolean(t)),'planned care failure visible');assert.equal(await page.locator('#agentForm [name="body"]').inputValue(),'19:00 开始，完成一轮后记录实际分钟数');await page.locator('#agentForm [type="submit"]').click();await until(()=>page.locator('#agentDialog').isVisible().then(v=>!v),'planned care accepted');await page.unroute('**/api/agent/action');let plannedState=await state();assert.equal(plannedState.agent.items.filter(x=>x.id===plannedID).length,1);const plannedTask=plannedState.tasks.find(t=>t.title==='虚构已核对的时间安排 '+width);assert.ok(plannedTask);await page.locator('details.card').filter({hasText:'虚构已核对的时间安排 '+width}).locator('summary').first().click();const acceptedPlanned=page.locator('[data-task="'+plannedTask.id+'"]').locator('xpath=ancestor::article[@data-agent-item]');assert.ok(await acceptedPlanned.count());await acceptedPlanned.locator('[data-agent-defer]').click();await page.locator('#agentDeferDialog').waitFor();const deferredDate=new Date(Date.parse(current.today+'T12:00:00Z')+7*86400000).toISOString().slice(0,10);await page.locator('#agentDeferForm [name="review_on"]').fill(deferredDate);
  const competingDate=new Date(Date.parse(current.today+'T12:00:00Z')+5*86400000).toISOString().slice(0,10);
  const competing=await fetch(url+'api/agent/action',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':token},body:JSON.stringify({id:plannedID,action:'defer',review_on:competingDate,expected_updated:plannedState.agent.items.find(x=>x.id===plannedID).updated})});assert.equal(competing.status,200);
  await page.locator('#agentDeferForm [type="submit"]').click();await page.locator('[data-agent-refresh-defer]:visible').waitFor();assert.equal(await page.locator('#agentDeferForm [name="review_on"]').inputValue(),deferredDate,'real CAS conflict preserves the proposed date');
  await page.locator('[data-agent-refresh-defer]').click();await until(()=>page.locator('#agentDeferCurrent').innerText().then(t=>t.includes(competingDate)),'latest parent decision visible before overwrite');assert.equal(await page.locator('#agentDeferForm [name="review_on"]').inputValue(),deferredDate);await fits(page);
  await page.locator('#agentDeferForm [type="submit"]').click();await until(()=>page.locator('#agentDeferDialog').isVisible().then(v=>!v),'planned care deferred');const deferredState=await state();assert.equal(deferredState.agent.items.find(x=>x.id===plannedID).plan.approved.review_on,deferredDate);await page.reload();await page.locator('.today-dashboard').waitFor();await page.locator('nav [data-page="more"]').click();await page.locator('#content [data-page="agent"]').click();await page.locator('#content h1').waitFor();await page.locator('details.card').filter({hasText:'虚构已核对的时间安排 '+width}).locator('summary').first().click();await until(async()=>page.locator('[data-agent-item="'+plannedID+'"]').innerText().then(t=>t.includes(deferredDate)),'deferred date visible');await page.locator('[data-agent-item="'+plannedID+'"]').scrollIntoViewIfNeeded();await proof(page,'planned-care-confirm-'+width);
  assert.deepEqual(pageErrors,[]);await page.close();
 }
 const p=await browser.newPage();await p.goto(url);await p.locator('.today-dashboard').waitFor();await p.locator('nav [data-page="more"]').click();await p.locator('#content [data-page="agent"]').click();await p.locator('#content h1').waitFor();const recordsBeforeDismiss=(await state()).records.length;await p.locator('[data-agent-dismiss]').first().click();await until(async()=>!(await state()).agent.items.some(x=>x.kind==='care'&&x.state==='pending'),'dismiss saved');assert.equal((await state()).records.length,recordsBeforeDismiss,'acknowledgement does not fabricate child feedback');await p.close();
 console.log(JSON.stringify({passed:true,widths:[360,1440],realAPI:true,syntheticOnly:true,formRetry:true,childBinding:true,escapedEvidence:true,acknowledgementNotFeedback:true,schoolSourceEntry:true,actualDayNotGuessed:true,taskFeedbackPreserved:true,sameSourceSameCase:true,observationSameChain:true,stableRecordRetry:true,closedUnknownReceiptRecovered:true,recordDoesNotChangeTask:true,emptySourceNoDefaultChild:true,ordinarySchoolEventNoForcedRetest:true,plannedCareLostReceipt:true,plannedCareConcurrentDeferral:true}));
}finally{if(browser)await browser.close();if(proc&&proc.exitCode===null){proc.kill('SIGINT');await once(proc,'exit')}}})().catch(e=>{console.error(e);process.exitCode=1});
