"""Run python3 test_task_video.py. Synthetic household, generated bytes, mocked ffprobe and model; no household services or paid models."""
import base64
import datetime as dt
import http.client
import io
import json
import os
import shutil
import sqlite3
import subprocess
import tempfile
import threading
import sys
import time
import unittest
import wave
from unittest import mock

import family_agent as agent
import family_goals as goals
import family_llm
import family_task_video as tv
import test_goals

DRAFT=dict(observations=[dict(start_seconds=1,end_seconds=3.5,text='虚构：画面中逐行书写听写词')],uncertainties=['虚构：第二行被手遮挡'])
REAL_RUN=subprocess.run
NONE=dict(used=0,failed=0);SENT=dict(used=1,failed=0);FAILED=dict(used=1,failed=1)


class TaskVideoTests(unittest.TestCase):
    action=test_goals.GoalTests.action;reply=test_goals.GoalTests.reply
    TASK=test_goals.MediaFeedbackEvidenceTests.TASK;OTHER='M-synthetic-2';SIBLING='M-synthetic-3'

    def setUp(self):
        test_goals.MediaFeedbackEvidenceTests.setUp(self)
        self.app.DATA=self.app.DATA.resolve();self.data=self.app.DATA  # read_file refuses a symlink anywhere in the path; macOS temp dirs sit behind one.
        self.agent=agent.Store(self.app.connect,self.app.profiles,self.app.DATA,app=self.app)
        self.duration='12.5';self.probes=[];self.sent=[];self.during_probe=self.during_call=None;self.model_fails=False;self.uploads={};self.changes=[]
        mock.patch.object(subprocess,'run',side_effect=self.ffprobe).start();mock.patch.object(family_llm,'configuration').start()
        self.model.side_effect=self.chat;self.enable(True)

    def enable(self,on):(self.app.DATA/'agent.json').write_text(json.dumps(dict(enabled=on,sources=[])))

    def ffprobe(self,args,**kwargs):
        assert args[0]=='ffprobe' and args[args.index('-protocol_whitelist')+1]=='pipe' and args[args.index('-i')+1]=='pipe:0',args
        if 'stream=codec_type:format=duration' in args:  # The job's probe; an upload asks for the streams only.
            self.probes.append(kwargs['input'])
            if self.during_probe:self.during_probe();self.changes.append('probe')
        return subprocess.CompletedProcess(args,0,stdout=json.dumps(dict(streams=[dict(codec_type='video')],format=dict(duration=self.duration))).encode())

    def chat(self,messages,schema,name,timeout,**kwargs):
        if name!='family_video_feedback_draft':return self.reply(messages,schema,name,timeout,**kwargs)
        self.sent.append(json.loads(messages[-1]['content'][0]['text']))
        if self.during_call:self.during_call();self.changes.append('call')
        if self.model_fails:raise family_llm.LLMDraftError('虚构模型失败')
        return json.loads(json.dumps(DRAFT))

    def clip(self,name='synthetic-clip.mp4'):
        self.count+=1;body=(b'\x1a\x45\xdf\xa3synthetic webm %d' if name.endswith('.webm') else b'\x00\x00\x00\x18ftypisomsynthetic %d')%self.count
        return self.app.save_upload(io.BytesIO(body),len(body),name)['id']

    def feedback(self,upload=None):
        self.count+=1
        return self.app.save_task_feedback(dict(task_id=self.TASK,child='示例甲',day=self.now.date().isoformat(),subject='英语',
            request_key='synthetic-video-'+str(self.count).zfill(8),attachments=[upload or self.clip()]))['record_id']

    def record(self,**obj):
        return dict(child='示例甲',day=self.now.date().isoformat(),category='学习进展',subject='英语',title='虚构练习视频',note='虚构说明',source='家长网页记录')|obj

    def linked(self,task=None):
        upload=self.clip();ident=self.app.save_record(self.record(attachments=[upload]))['record_id'];self.uploads[ident]=upload
        if task:self.app.link_record_task(dict(record_id=ident,child='示例甲',task_id=task))
        return ident

    def relink(self,ident):
        with self.app.connect() as c:at=c.execute('SELECT linked_task_at FROM records WHERE id=?',(ident,)).fetchone()[0]
        return lambda:self.app.link_record_task(dict(record_id=ident,child='示例甲',task_id=self.OTHER,expected_linked_at=at))

    def correct(self,ident):  # A note-only correction: subject, originals and link stay as they were.
        return lambda:self.app.save_record(self.record(id=ident,note='虚构：更正说明',attachments=[self.uploads[ident]]))

    def tick(self,minutes=0):return tv.prepare(self.app,self.agent,self.now+dt.timedelta(minutes=minutes))

    def lines(self):
        with self.app.connect() as c:return set(c.iterdump())

    def files(self):return {p.name:p.read_bytes() for p in (self.app.DATA/'uploads').iterdir()}

    def rows(self,table):
        with self.app.connect() as c:return c.execute('SELECT COUNT(*) FROM '+table+(" WHERE id LIKE 'record-video:%'" if table=='agent_jobs' else '')).fetchone()[0]

    def view(self,ident):
        """Every read in these tests also proves that reading calls nothing and writes nothing."""
        before=(self.lines(),self.files(),len(self.probes),len(self.sent));result=tv.view(self.app,self.agent,ident)
        self.assertEqual((self.lines(),self.files(),len(self.probes),len(self.sent)),before);return result

    def state(self,ident):return [v['state'] for v in self.view(ident)['videos']]

    def test_feedback_and_link_each_leave_once_and_records_tasks_and_originals_stay_as_they_were(self):
        first=self.feedback();second=self.linked(self.TASK);before=self.lines();files=self.files()
        self.assertEqual((self.state(first),self.state(second)),(['pending'],['pending']))
        with mock.patch.object(tv.family_media,'read_file',wraps=tv.family_media.read_file) as read:
            self.assertEqual([self.tick(),self.tick(),self.tick(),self.tick(60*24)],[SENT,SENT,NONE,NONE])
        self.assertTrue(read.call_args_list and all(call.args[1]==family_llm.MAX_INPUT for call in read.call_args_list),'bounded read only')
        self.assertEqual(len(self.sent),2);self.assertEqual(self.sent[0]['task'],dict(title='虚构听写',subject='英语',requirement='虚构要求'))
        views=[self.view(i) for i in (first,second)]
        self.assertEqual([(v['basis'],v['task_id'],v['audience'],v['read_only'],v['videos'][0]['state']) for v in views],
                         [('feedback',self.TASK,'parent',True,'ready'),('link',self.TASK,'parent',True,'ready')])
        video=views[0]['videos'][0];self.assertEqual((video['duration_seconds'],video['draft']['observations'],video['draft']['audio_assessed']),(12.5,DRAFT['observations'],False))
        changed=before^self.lines();self.assertTrue(changed);self.assertTrue(all('record_video_drafts' in l or 'agent_jobs' in l for l in changed),changed)
        self.assertEqual(self.files(),files)

    def test_another_childs_task_a_shared_original_an_unlinked_record_and_a_disabled_agent_never_leave(self):
        plain=self.linked();foreign=self.linked(self.TASK);shared=self.feedback()
        with self.app.connect() as c:
            c.execute('UPDATE records SET linked_task_id=? WHERE id=?',(self.SIBLING,foreign))  # The other child's task.
            c.execute("INSERT INTO records(child,day,category,subject,title,note,source,created,attachments) VALUES('示例乙',?,'学习进展','英语','虚构','虚构','家长网页记录',?,?)",
                      (self.now.date().isoformat(),self.now.isoformat(),c.execute('SELECT attachments FROM records WHERE id=?',(shared,)).fetchone()[0]))
        self.assertEqual(self.tick(),NONE);self.enable(False);allowed=self.feedback();self.assertEqual(self.tick(),NONE)
        self.assertEqual((self.sent,self.probes,self.rows('agent_jobs'),self.rows('record_video_drafts')),([],[],0,0))
        self.assertEqual([self.state(i) for i in (plain,foreign,shared,allowed)],[[],[],['unavailable'],['unavailable']])
        self.assertTrue(self.view(plain)['explanation'] and self.view(foreign)['explanation'])
        # Counter-proof: the same household does call out once the switch is on, so the zeros above are the guards' doing.
        self.enable(True);self.assertEqual(self.tick(),SENT);self.assertEqual((self.state(allowed),self.state(shared),len(self.sent)),(['ready'],['unavailable'],1))

    def test_a_change_before_or_during_the_call_is_neither_saved_nor_shown(self):
        for when in ('during_probe','during_call'):
            for name,change in (('relink',self.relink),('correct',self.correct),('disable',lambda ident:lambda:self.enable(False))):
                with self.subTest(when=when,change=name):
                    self.enable(True);ident=self.linked(self.TASK);sent=len(self.sent);changes=len(self.changes);setattr(self,when,change(ident))
                    try:result=self.tick()
                    finally:setattr(self,when,None)
                    self.assertEqual(len(self.changes),changes+1,'the injected change must succeed, not merely raise inside the job');called=int(when=='during_call');self.assertEqual((result,len(self.sent)-sent),(dict(used=called,failed=1),called))
                    self.assertEqual(self.rows('record_video_drafts'),0);self.assertNotIn('ready',self.state(ident))

    def test_a_note_only_correction_hides_the_ready_draft_and_without_the_last_recheck_a_stale_result_is_stored(self):
        ident=self.linked(self.TASK);self.assertEqual(self.tick(),SENT);self.assertEqual(self.state(ident),['ready'])
        self.correct(ident)();self.assertEqual(self.state(ident),['pending'])
        # Counter-proof: with only the final re-check removed, the same mid-call relink stores the stale draft.
        ident=self.linked(self.TASK);real=tv._current;calls=[]
        def unguarded(app,store,c,value):
            calls.append(1);return real(app,store,c,value) if len(calls)<3 else value
        self.during_call=self.relink(ident)
        with mock.patch.object(tv,'_current',unguarded):self.assertEqual(self.tick(),SENT)
        self.during_call=None;self.assertEqual(self.rows('record_video_drafts'),2);self.assertEqual(self.state(ident),['pending'],'the read still compares the fingerprint')

    def test_three_failures_back_off_and_then_wait_for_the_parents_retry(self):
        ident=self.feedback();self.model_fails=True
        self.assertEqual([self.tick(m) for m in (0,1,5,6,15,16,999)],[FAILED,NONE,FAILED,NONE,FAILED,NONE,NONE])
        video=self.view(ident)['videos'][0];self.assertEqual((video['state'],video['attempts'],video['exhausted'],len(self.sent)),('error',3,True,3))
        self.assertIn('虚构模型失败',video['explanation']);self.assertEqual(self.rows('record_video_drafts'),0)
        self.model_fails=False;self.agent.act(dict(action='retry',id=video['job_id']))
        self.assertEqual((self.tick(999),self.tick(999)),(SENT,NONE));self.assertEqual((self.state(ident),len(self.sent)),(['ready'],4))

    def test_independent_agent_uses_only_remaining_budget_and_does_not_repeat(self):
        ident=self.feedback()
        with mock.patch.object(test_goals.goals.Store,'run',return_value=dict(used=3,created=0,failed=0,children=[])),mock.patch.object(tv,'prepare',wraps=tv.prepare) as prepare:
            agent.run_once(self.app,self.now)
            prepare.assert_not_called()
        self.assertEqual((self.sent,self.state(ident)),([],['pending']))
        self.model.reset_mock()
        result=agent.run_once(self.app,self.now)
        self.assertEqual((result['failed'],len(self.sent),self.state(ident)),(0,1,['ready']))
        self.assertLessEqual(self.model.call_count,3)
        agent.run_once(self.app,self.now)
        self.assertEqual(len(self.sent),1)

    def test_a_webm_without_a_duration_is_refused_as_unsupported_and_is_not_sent(self):
        self.duration='N/A'
        for mime,code in (('video/webm','webm_duration_unsupported'),('video/mp4','duration_invalid')):
            with self.assertRaises(tv.VideoDraftError) as caught:tv.probe(b'synthetic',mime)
            self.assertEqual(caught.exception.code,code)
        ident=self.feedback(self.clip('synthetic-clip.webm'));self.assertEqual(self.tick(),dict(used=0,failed=1));self.assertEqual(self.sent,[])
        video=self.view(ident)['videos'][0];self.assertEqual(video['state'],'error');self.assertIn('无法确定完整时间轴',video['explanation'])

    def test_real_stream_webm_reaches_background_draft_once_and_bad_tail_never_calls_model(self):
        body=REAL_RUN(['ffmpeg','-v','error','-f','lavfi','-i','color=c=blue:s=160x120:r=10:d=4','-c:v','libvpx','-f','webm','pipe:1'],capture_output=True,check=True,timeout=15).stdout
        with mock.patch.object(subprocess,'run',side_effect=REAL_RUN):
            upload=self.app.save_upload(io.BytesIO(body),len(body),'synthetic.webm')['id']
            ident=self.feedback(upload);before=self.lines();files=self.files()
            self.assertEqual([self.tick(),self.tick()],[SENT,NONE])
            self.assertEqual(self.state(ident),['ready']);self.assertEqual(len(self.sent),1)
            self.assertFalse(self.view(ident)['videos'][0]['draft']['audio_assessed'])
            self.assertTrue(all('record_video_drafts' in row or 'agent_jobs' in row for row in before^self.lines()))
            self.assertEqual(self.files(),files)
            for cut in (1,40):
                # Model selection uses exact original bytes/hash; its probe is the shared rejection gate.
                with self.assertRaises(tv.VideoDraftError):tv.probe(body[:-cut],'video/webm')
            self.assertEqual(len(self.sent),1)


class WebMProbeTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not shutil.which('ffmpeg') or not shutil.which('ffprobe'):
            raise unittest.SkipTest('optional local ffmpeg/ffprobe tools unavailable')
        args=['ffmpeg','-v','error','-f','lavfi','-i','color=c=blue:s=160x120:r=10:d=2','-c:v','libvpx']
        cls.pipe=REAL_RUN(args+['-f','webm','pipe:1'],capture_output=True,check=True,timeout=15).stdout
        with tempfile.TemporaryDirectory() as directory:
            path=os.path.join(directory,'synthetic.webm')
            REAL_RUN(args+[path],capture_output=True,check=True,timeout=15)
            with open(path,'rb') as stream:cls.seekable=stream.read()
        cls.audio=REAL_RUN(['ffmpeg','-v','error','-f','lavfi','-i','sine=duration=1','-c:a','libopus','-f','webm','pipe:1'],capture_output=True,check=True,timeout=15).stdout

    def test_real_pipe_seekable_truncated_and_audio_only(self):
        for body in (self.pipe,self.seekable):
            self.assertAlmostEqual(tv.probe(body,'video/webm'),2.0,places=2)
            for cut in (1,40):
                with self.subTest(size=len(body),cut=cut),self.assertRaises(tv.VideoDraftError):
                    tv.probe(body[:-cut],'video/webm')
        with self.assertRaises(tv.VideoDraftError) as caught:tv.probe(self.audio,'video/webm')
        self.assertEqual(caught.exception.code,'no_video_track')

    def run_fake(self,code,limit=.3):
        real=subprocess.Popen;children=[]
        def child(args,**kwargs):
            self.assertEqual(args[args.index('-protocol_whitelist')+1],'pipe')
            p=real([sys.executable,'-c',code],**kwargs);children.append(p);return p
        started=time.monotonic()
        try:
            with mock.patch.object(tv.subprocess,'Popen',side_effect=child):
                return tv._webm_packet_end(b'synthetic',limit)
        finally:
            self.assertTrue(children and all(p.poll() is not None for p in children),'no orphan process')
            self.assertLess(time.monotonic()-started,2)

    def test_exit_zero_errors_hangs_and_excess_output_are_refused(self):
        for code in ("import time;time.sleep(10)",
                     "import sys;sys.stderr.write('File ended prematurely');print('0,2')",
                     r"import sys;sys.stdout.write('0,1\n'*400000)",
                     "import sys;sys.stderr.write('error'*400000)"):
            with self.subTest(code=code),self.assertRaises(tv.VideoDraftError):self.run_fake(code)
        with mock.patch.object(tv,'MAX_PROBE_OUTPUT',3),self.assertRaises(tv.VideoDraftError):
            self.run_fake("print('0,2')")
        self.assertEqual(self.run_fake("print('0,1');print('1,1')"),2)

    def test_invalid_rows_missing_tool_and_shared_deadline(self):
        for row in ('nan,1','0,inf','-1,2','0,N/A','0,0','1,0','0,1,2',''):
            with self.subTest(row=row),self.assertRaises(tv.VideoDraftError):self.run_fake('print('+repr(row)+')')
        with mock.patch.object(tv.subprocess,'Popen',side_effect=FileNotFoundError),self.assertRaises(tv.VideoDraftError) as caught:
            tv._webm_packet_end(b'x',1)
        self.assertEqual(caught.exception.code,'probe_missing')
        header=subprocess.CompletedProcess([],0,stdout=b'{"streams":[{"codec_type":"video"}],"format":{}}',stderr=b'')
        with mock.patch.object(tv,'_run_ffprobe',return_value=header),mock.patch.object(tv.time,'monotonic',side_effect=[0,16]),mock.patch.object(tv,'_webm_packet_end') as fallback:
            # The fallback must reject a nonpositive remainder, rather than get a fresh 15 seconds.
            fallback.side_effect=lambda body,remaining:tv._require(remaining>0,'webm_duration_unsupported')
            with self.assertRaises(tv.VideoDraftError):tv.probe(b'x','video/webm')
            self.assertLess(fallback.call_args.args[1],0)
        for duration in (float('inf'),601,0):
            with mock.patch.object(tv,'_run_ffprobe',return_value=header),mock.patch.object(tv,'_webm_packet_end',return_value=duration),self.assertRaises(tv.VideoDraftError):
                tv.probe(b'x','video/webm')


class TaskVideoHttpTests(unittest.TestCase):
    """#23 over real HTTP: the parent reads the checked draft; a child session, the public anonymous entry and malformed
    requests get nothing; a read calls no model or ffprobe and writes nothing; the retry stays the existing CSRF-checked action."""
    action=TaskVideoTests.action;reply=TaskVideoTests.reply;TASK=TaskVideoTests.TASK;OTHER=TaskVideoTests.OTHER;SIBLING=TaskVideoTests.SIBLING
    ffprobe=TaskVideoTests.ffprobe;chat=TaskVideoTests.chat;enable=TaskVideoTests.enable;clip=TaskVideoTests.clip;feedback=TaskVideoTests.feedback;record=TaskVideoTests.record
    linked=TaskVideoTests.linked;relink=TaskVideoTests.relink;correct=TaskVideoTests.correct;tick=TaskVideoTests.tick;lines=TaskVideoTests.lines;files=TaskVideoTests.files
    PUBLIC='family.example.ts.net';LAN='192.168.50.2:8765';PASSWORD='synthetic-http-parent-password-123'

    def setUp(self):
        TaskVideoTests.setUp(self);self.server=self.app.ThreadingHTTPServer(('127.0.0.1',0),self.app.Handler)
        worker=threading.Thread(target=self.server.serve_forever,daemon=True);worker.start()
        self.addCleanup(lambda:(self.server.shutdown(),self.server.server_close(),worker.join()))

    def request(self,path,body=None,headers=None,host=None):
        client=http.client.HTTPConnection('127.0.0.1',self.server.server_port,timeout=5)
        try:
            client.request('POST' if body is not None else 'GET',path,json.dumps(body) if body is not None else None,
                           {'Content-Type':'application/json',**({'Host':host} if host else {}),**(headers or {})})
            response=client.getresponse();raw=response.read()
            try:value=json.loads(raw)
            except ValueError:value=None  # An original, not JSON.
            return response.status,value,dict(response.getheaders())
        finally:client.close()

    def calls(self):return (self.lines(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent))

    def video(self,ident,headers=None,host=None):
        """Every HTTP read in these tests also proves that reading calls nothing and writes nothing."""
        before=self.calls();status,result,_=self.request('/api/record/video?record_id=%d'%ident,headers=headers,host=host)
        self.assertEqual(self.calls(),before);return status,result

    def entry(self,base):
        path=self.app.DATA/'access.json';path.write_text(json.dumps(self.app.family_access.make_config(base,'parent',self.PASSWORD)),encoding='utf-8');path.chmod(0o600)

    def test_the_parent_reads_the_checked_draft_and_a_child_the_public_entry_and_malformed_requests_get_nothing(self):
        first=self.linked(self.TASK);second=self.linked(self.TASK);self.assertEqual([self.tick(),self.tick()],[SENT,SENT])
        upload=self.uploads[first];text=DRAFT['observations'][0]['text'];status,result=self.video(first)
        self.assertEqual((status,result['record_id'],result['task_id'],result['basis'],result['audience'],result['read_only']),(200,first,self.TASK,'link','parent',True))
        video,=result['videos']
        self.assertEqual((video['state'],video['upload_id'],video['job_id'],video['duration_seconds']),('ready',upload,tv.job_key(first,upload),12.5))
        self.assertEqual(video['draft']['observations'],DRAFT['observations']);self.assertIs(video['draft']['audio_assessed'],False)
        self.assertEqual(self.video(first),(200,result),'a repeated read is the same read')
        for query in ('','?','?record_id=','?record_id=0','?record_id=-1','?record_id=01','?record_id=1.0','?record_id=%2B1','?record_id=abc','?record_id=9223372036854775808',
                      '?record_id=%EF%BC%91','?id=%d'%first,'?record_id=%d&record_id=%d'%(first,first),'?record_id=%d&child=x'%first,'?record_id=%d;record_id=%d'%(first,second)):
            with self.subTest(query=query):
                before=self.calls();status,refused,_=self.request('/api/record/video'+query)
                self.assertEqual((status,set(refused)),(400,{'error'}));self.assertEqual(self.calls(),before)
        before=self.calls();status,refused,_=self.request('/api/record/video?record_id=987654')
        self.assertEqual((status,refused.get('code')),(404,'record_missing'));self.assertEqual(self.calls(),before)
        # The same child's own session: no draft, no retry and no original, on the loopback entry and with the parent token too.
        child=self.app.family_child;child.parent_action(self.app,'study',dict(child_id='child-1',enabled=True))
        status,state,headers=self.request('/child/api/login',dict(invite=child.parent_action(self.app,'invite',dict(child_id='child-1'))['invite']));self.assertEqual(status,200)
        cookie={'Cookie':headers['Set-Cookie'].split(';',1)[0]};kid=cookie|{'X-Child-CSRF':state['csrf']}
        status,state,_=self.request('/child/api/state',headers=kid);self.assertEqual(status,200)
        for hidden in (text,upload):self.assertNotIn(hidden,json.dumps(state,ensure_ascii=False))
        retry=dict(action='retry',id=video['job_id']);token={'X-Family-Token':self.app.TOKEN}
        def refused_everywhere(who,status,host=None):
            before=self.calls();got,body,_=self.request('/api/record/video?record_id=%d'%first,headers=who,host=host)
            self.assertEqual(got,status);self.assertNotIn('videos',body);self.assertNotIn(text,json.dumps(body,ensure_ascii=False))
            self.assertEqual(self.request('/api/agent/action',retry,who|token,host=host)[0],status)
            self.assertEqual(self.request('/upload/'+upload,headers=who,host=host)[0],status);self.assertEqual(self.calls(),before)
        for who in (cookie,kid):refused_everywhere(who,403)
        self.assertEqual(self.request('/child/upload/'+upload,headers=kid)[0],403)
        self.assertEqual(self.request('/upload/'+upload)[0],200,'the same original stays readable for the parent')
        # Public entry: anonymous and child-only requests are not a parent; the signed-in parent reads the same draft.
        self.entry('https://'+self.PUBLIC+'/family');self.addCleanup((self.app.DATA/'access.json').unlink)
        for who in ({},cookie,kid):refused_everywhere(who,401,self.PUBLIC)
        basic={'Authorization':'Basic '+base64.b64encode(('parent:'+self.PASSWORD).encode()).decode('ascii')}
        self.assertEqual(self.video(first,headers=basic,host=self.PUBLIC),(200,result))
        # Home-network entry without login: the parent reads, a child session on the same network still does not.
        self.entry('http://'+self.LAN)
        with mock.patch.dict(os.environ,FAMILY_LAN_NO_LOGIN='1'):
            self.assertEqual(self.video(first,host=self.LAN),(200,result))
            for who in (cookie,kid):refused_everywhere(who,403,self.LAN)
        # Authorization withdrawn, a correction and a moved link: the stored draft is no longer shown.
        self.enable(False);status,off=self.video(first);self.assertEqual((status,[v['state'] for v in off['videos']]),(200,['unavailable']));self.assertNotIn(text,json.dumps(off,ensure_ascii=False))
        self.enable(True);self.assertEqual(self.video(first),(200,result))
        self.correct(first)();self.relink(second)()
        for ident,task in ((first,self.TASK),(second,self.OTHER)):
            status,stale=self.video(ident);self.assertEqual((status,stale['task_id'],[v['state'] for v in stale['videos']]),(200,task,['pending']))
            self.assertNotIn('draft',stale['videos'][0]);self.assertNotIn(text,json.dumps(stale,ensure_ascii=False))

    def test_the_existing_retry_keeps_its_csrf_check_and_only_queues_the_job(self):
        ident=self.feedback();self.model_fails=True;self.assertEqual([self.tick(m) for m in (0,5,15)],[FAILED]*3)
        status,result=self.video(ident);video,=result['videos']
        self.assertEqual((status,video['state'],video['attempts'],video['exhausted']),(200,'error',3,True));self.assertNotIn('draft',video)
        retry=dict(action='retry',id=video['job_id'])
        for headers in ({},{'X-Family-Token':'invalid-token'}):
            before=self.calls();status,refused,_=self.request('/api/agent/action',retry,headers)
            self.assertEqual((status,refused.get('code')),(403,'csrf_expired'));self.assertEqual(self.calls(),before)
        self.assertEqual(self.tick(999),NONE,'an exhausted job waits for the parent')
        before=self.calls();status,done,_=self.request('/api/agent/action',retry,{'X-Family-Token':self.app.TOKEN});after=self.calls()
        self.assertEqual((status,done),(200,dict(ok=True,state='retry_pending')))
        self.assertEqual(after[1:],before[1:],'the retry calls no model or ffprobe and touches no original')
        changed=before[0]^after[0];self.assertTrue(changed and all('agent_jobs' in line for line in changed),changed)
        self.assertEqual([v['state'] for v in self.video(ident)[1]['videos']],['pending'])
        self.model_fails=False;self.assertEqual((self.tick(999),self.tick(999)),(SENT,NONE))
        self.assertEqual(([v['state'] for v in self.video(ident)[1]['videos']],len(self.sent)),(['ready'],4))


TWO=dict(observations=[DRAFT['observations'][0],dict(start_seconds=4,end_seconds=6,text='虚构：翻页后继续书写')],uncertainties=DRAFT['uncertainties'])


class VideoReviewTests(unittest.TestCase):
    """Explicit parent review of listed observations: versioned by token, append-only, shown back only for that version; nothing consumes it."""
    setUp=TaskVideoTests.setUp;enable=TaskVideoTests.enable;ffprobe=TaskVideoTests.ffprobe;chat=TaskVideoTests.chat;clip=TaskVideoTests.clip
    feedback=TaskVideoTests.feedback;record=TaskVideoTests.record;linked=TaskVideoTests.linked;relink=TaskVideoTests.relink;correct=TaskVideoTests.correct
    tick=TaskVideoTests.tick;lines=TaskVideoTests.lines;files=TaskVideoTests.files;rows=TaskVideoTests.rows;view=TaskVideoTests.view;state=TaskVideoTests.state
    action=TaskVideoTests.action;reply=TaskVideoTests.reply;TASK=TaskVideoTests.TASK;OTHER=TaskVideoTests.OTHER;SIBLING=TaskVideoTests.SIBLING

    def ready(self):
        """A synthetic two-observation draft made by the background job; the draft, the job and the reads confirm nothing."""
        ident=self.linked(self.TASK)
        with mock.patch.dict(DRAFT,TWO,clear=True):self.assertEqual(self.tick(),SENT)
        video=self.view(ident)['videos'][0]
        self.assertEqual((video['state'],video['review']['state'],len(video['token']),video['draft']['observations']),('ready','unconfirmed',64,TWO['observations']))
        return ident,video

    def body(self,ident,video,**obj):
        return dict(record_id=ident,upload_id=video['upload_id'],expected_token=video['token'],action='confirm',selected=[0])|obj

    def other(self):return {l for l in self.lines() if 'record_video_reviews' not in l}

    def review(self,body):
        """Every review call also proves that it runs no probe, no model and changes no other table or file."""
        before=(self.other(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent))
        try:return tv.review(self.app,self.agent,body)
        finally:self.assertEqual((self.other(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent)),before)

    def refused(self,body,status,code=None):
        rows=self.rows('record_video_reviews')
        with self.assertRaises(agent.AgentError) as caught:self.review(body)
        self.assertEqual((caught.exception.status,self.rows('record_video_reviews')),(status,rows),body)
        if code:self.assertEqual(caught.exception.code,code)
        return str(caught.exception)

    def test_confirm_retry_view_revoke_and_history_and_nothing_is_confirmed_without_the_parents_action(self):
        ident,video=self.ready();self.assertEqual(self.rows('record_video_reviews'),0)
        statements=[];connect=self.agent.connect
        def traced():
            c=connect();c.set_trace_callback(statements.append);return c
        with mock.patch.object(self.agent,'connect',traced):self.view(ident);self.view(ident)
        self.assertTrue(statements);self.assertEqual([s for s in statements if s.split()[0].upper() in ('INSERT','UPDATE','DELETE','CREATE','DROP','ALTER','REPLACE')],[])
        first=self.review(self.body(ident,video,selected=[1,0]));again=self.review(self.body(ident,video,selected=[0,1]))
        self.assertEqual((first['repeated'],again['repeated'],again['id'],self.rows('record_video_reviews')),(False,True,first['id'],1))
        self.assertEqual({k:v for k,v in again.items() if k!='repeated'},{k:v for k,v in first.items() if k!='repeated'})
        shown=first['review'];self.assertEqual((shown['state'],shown['label'],shown['selected'],shown['observations'],shown['uncertainties'],shown['duration_seconds'],shown['audio_assessed']),
                         ('confirmed',tv.REVIEW_LABEL,[0,1],TWO['observations'],TWO['uncertainties'],12.5,False))
        self.assertIn('未评估声音',shown['explanation']);self.assertIn('不代表完成或掌握',shown['explanation'])
        self.assertEqual((first['token'],first['task_id'],self.view(ident)['videos'][0]['review']),(video['token'],self.TASK,shown))
        revoked=self.review(self.body(ident,video,action='revoke',selected=[]))
        self.assertEqual((revoked['id'],revoked['action'],revoked['review']['state'],revoked['review']['revoked_at'],self.rows('record_video_reviews')),(first['id']+1,'revoke','unconfirmed',revoked['reviewed_at'],2))
        self.assertEqual(self.view(ident)['videos'][0]['review']['state'],'unconfirmed')
        self.assertEqual((self.review(self.body(ident,video,action='revoke',selected=[]))['id'],self.rows('record_video_reviews')),(revoked['id'],2))
        second=self.review(self.body(ident,video,selected=[1]))
        self.assertEqual((second['id'],second['repeated'],second['review']['observations'],self.rows('record_video_reviews')),(first['id']+2,False,[TWO['observations'][1]],3))
        with self.app.connect() as c:history=[(r[0],r[1],json.loads(r[2])['selected'],json.loads(r[2])['observations']) for r in c.execute('SELECT id,action,payload FROM record_video_reviews ORDER BY id')]
        self.assertEqual(history,[(first['id'],'confirm',[0,1],TWO['observations']),(first['id']+1,'revoke',[],[]),(first['id']+2,'confirm',[1],[TWO['observations'][1]])])
        self.assertEqual(self.rows('record_video_drafts'),1)

    def test_malformed_stale_missing_and_unconfirmed_requests_are_refused_without_a_row(self):
        ident,video=self.ready();good=self.body(ident,video)
        for bad in (dict(good,record_id=True),dict(good,record_id=str(ident)),dict(good,record_id=0),dict(good,record_id=-ident),dict(good,record_id=float(ident)),
                    dict(good,upload_id=5),dict(good,upload_id=''),dict(good,expected_token=video['token'][:-1]),dict(good,expected_token=video['token'].upper()),
                    dict(good,action='approve'),dict(good,action='confirm '),dict(good,selected=[]),dict(good,selected=[0,0]),dict(good,selected=['0']),dict(good,selected=[True]),
                    dict(good,selected=[{}]),dict(good,selected=[[0]]),dict(good,selected=[-1]),dict(good,selected=[8]),dict(good,selected=0),dict(good,selected=[2]),dict(good,selected=None),
                    dict(good,text='虚构：家长自己写的观察'),dict(good,observations=TWO['observations']),dict(good,start_seconds=1),dict(good,audio_assessed=True),
                    dict(good,action='revoke',selected=[0]),[good],None):
            self.refused(bad,400)
        other=self.linked(self.TASK)  # a valid token belongs to one record's one draft only
        self.refused(dict(good,record_id=other),409,'original_missing');self.refused(dict(good,expected_token='0'*64),409,'token_stale')
        self.refused(dict(good,action='revoke',selected=[]),409,'review_not_confirmed')
        self.refused(dict(good,upload_id=self.clip()),409,'original_missing');self.refused(dict(good,record_id=ident+1000),409)
        self.assertEqual(self.view(ident)['videos'][0]['review']['state'],'unconfirmed')

    def test_every_source_change_hides_the_confirmation_and_refuses_the_old_token(self):
        def hash_change(ident):
            path=self.data/'uploads'/self.uploads[ident];return lambda:path.write_bytes(b'Y'+path.read_bytes()[1:])  # same size, other bytes
        def draft_replacement(ident):
            def replace():
                with self.app.connect() as c:
                    payload=json.loads(c.execute('SELECT payload FROM record_video_drafts WHERE record_id=?',(ident,)).fetchone()[0])
                    payload['draft']['observations'][0]['text']='虚构：后台重新整理后的观察'
                    c.execute('UPDATE record_video_drafts SET payload=? WHERE record_id=?',(json.dumps(payload,ensure_ascii=False),ident))
            return replace
        def cross_child(ident):
            def share():
                with self.app.connect() as c:
                    c.execute("INSERT INTO records(child,day,category,subject,title,note,source,created,attachments) VALUES('示例乙',?,'学习进展','英语','虚构','虚构','家长网页记录',?,?)",
                              (self.now.date().isoformat(),self.now.isoformat(),json.dumps([self.uploads[ident]])))
            return share
        cases=(('correct',self.correct,('pending',)),('relink',self.relink,('pending','unavailable')),('disable',lambda ident:lambda:self.enable(False),('unavailable',)),
               ('hash',hash_change,('pending',)),('draft',draft_replacement,('ready',)),('cross_child',cross_child,('unavailable',)))
        for name,change,expected in cases:
            with self.subTest(change=name):
                self.enable(True);ident,video=self.ready();first=self.review(self.body(ident,video));self.assertEqual(first['review']['state'],'confirmed')
                rows=self.rows('record_video_reviews');change(ident)();shown=self.view(ident)['videos'][0]
                self.assertIn(shown['state'],expected);self.assertNotEqual(shown.get('review',{}).get('state'),'confirmed')
                if shown['state']=='ready':self.assertNotEqual(shown['token'],video['token']);self.assertEqual(shown['review']['state'],'unconfirmed')
                self.refused(self.body(ident,video),409);self.refused(self.body(ident,video,action='revoke',selected=[]),409)
                self.assertEqual(self.rows('record_video_reviews'),rows)  # the old confirmation stays on disk, hidden, never erased
                if shown['state']=='ready':self.assertEqual(self.review(self.body(ident,shown))['review']['state'],'confirmed')

    def test_a_change_after_the_write_lock_is_taken_is_still_caught_before_the_row_is_written(self):
        ident,video=self.ready();connect=self.agent.connect;injected=[];test=self
        class Injecting:
            def __init__(s,c):object.__setattr__(s,'c',c)
            def __getattr__(s,name):return getattr(s.c,name)
            def __setattr__(s,name,value):setattr(s.c,name,value)
            def execute(s,sql,*args):
                result=s.c.execute(sql,*args)
                if sql=='BEGIN IMMEDIATE':s.c.execute('UPDATE records SET linked_task_id=? WHERE id=?',(test.OTHER,ident));injected.append(1)
                return result
        with mock.patch.object(self.agent,'connect',lambda:Injecting(connect())):self.refused(self.body(ident,video),409)
        self.assertEqual(injected,[1]);self.assertEqual(self.review(self.body(ident,video))['review']['state'],'confirmed')  # the same request passes once nothing moves

    def test_a_database_without_the_review_table_reads_safely_and_only_store_setup_creates_it(self):
        ident,video=self.ready()
        with self.app.connect() as c:c.execute('DROP TABLE record_video_reviews')
        shown=self.view(ident)['videos'][0];self.assertEqual((shown['state'],shown['review']['state'],shown['token']),('ready','unconfirmed',video['token']))
        with self.app.connect() as c:self.assertEqual(c.execute("SELECT COUNT(*) FROM sqlite_master WHERE name='record_video_reviews'").fetchone()[0],0)
        agent.Store(self.app.connect,self.app.profiles,self.app.DATA,app=self.app)
        self.assertEqual(self.review(self.body(ident,video))['review']['state'],'confirmed')


class VideoReviewHttpTests(unittest.TestCase):
    """#23 over real HTTP: only the signed-in parent with the page token confirms or revokes listed observations. Anonymous, child-only
    and token-less requests, malformed bodies and stale versions write no row; every review and every read runs no model and no probe."""
    setUp=TaskVideoHttpTests.setUp;request=TaskVideoHttpTests.request;calls=TaskVideoHttpTests.calls;video=TaskVideoHttpTests.video;entry=TaskVideoHttpTests.entry
    PUBLIC=TaskVideoHttpTests.PUBLIC;LAN=TaskVideoHttpTests.LAN;PASSWORD=TaskVideoHttpTests.PASSWORD;ready=VideoReviewTests.ready;body=VideoReviewTests.body;other=VideoReviewTests.other
    enable=TaskVideoTests.enable;ffprobe=TaskVideoTests.ffprobe;chat=TaskVideoTests.chat;clip=TaskVideoTests.clip;feedback=TaskVideoTests.feedback;record=TaskVideoTests.record
    linked=TaskVideoTests.linked;relink=TaskVideoTests.relink;correct=TaskVideoTests.correct;tick=TaskVideoTests.tick;lines=TaskVideoTests.lines;files=TaskVideoTests.files
    rows=TaskVideoTests.rows;view=TaskVideoTests.view;state=TaskVideoTests.state;action=TaskVideoTests.action;reply=TaskVideoTests.reply
    TASK=TaskVideoTests.TASK;OTHER=TaskVideoTests.OTHER;SIBLING=TaskVideoTests.SIBLING;PATH='/api/record/video/review'

    def post(self,body,headers=None,host=None,token=True):
        """Every HTTP review also proves that it runs no probe, no model and changes no other table or file. The page token is sent
        unless the test omits it (False) or replaces it."""
        sent=({'X-Family-Token':self.app.TOKEN} if token is True else {'X-Family-Token':token} if token else {})|(headers or {})
        before=(self.other(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent))
        status,result,_=self.request(self.PATH,body,sent,host=host)
        self.assertEqual((self.other(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent)),before);return status,result

    def refused(self,body,status,code=None,**how):
        """A refusal writes no review row, returns no review and shows no observation text."""
        rows=self.rows('record_video_reviews');got,result=self.post(body,**how)
        self.assertEqual((got,self.rows('record_video_reviews'),'review' in (result or {}),TWO['observations'][0]['text'] in json.dumps(result,ensure_ascii=False)),(status,rows,False,False),(str(body)[:200],how,result))
        if code:self.assertEqual(result.get('code'),code)
        return result

    def traced_reads(self,ident,count=2):
        """The SQL of the real HTTP reads alone, no snapshot helper inside the trace: a read runs no writing or schema statement,
        and the file, line, model and probe counts taken before and after still match."""
        statements=[];connect=sqlite3.connect
        def traced(*args,**kwargs):
            c=connect(*args,**kwargs);c.set_trace_callback(statements.append);return c
        before=self.calls()
        with mock.patch.object(sqlite3,'connect',traced):reads=[self.request('/api/record/video?record_id=%d'%ident)[:2] for _ in range(count)]
        self.assertEqual(self.calls(),before);self.assertTrue(statements,'the read went to the database')
        self.assertEqual([s for s in statements if s.split()[0].upper() in ('INSERT','UPDATE','DELETE','CREATE','DROP','ALTER','REPLACE')],[],'a read runs no writing or schema SQL')
        return reads,statements

    def tables(self):
        """The table names as the file has them, read without the app's connect() that would create the missing ones."""
        c=sqlite3.connect(self.app.Path(self.app.DB).absolute().as_uri()+'?mode=ro',uri=True)
        try:return sorted(r[0] for r in c.execute("SELECT name FROM sqlite_master WHERE type='table'"))
        finally:c.close()

    def test_a_read_creates_no_table_and_an_old_or_empty_database_answers_without_a_write(self):
        """The GET opens the file read-only: without the review table it reads as unconfirmed, without any table or file it refuses as
        unavailable without the error's text, and no read creates a table or a file."""
        ident,video=self.ready();status,first=self.post(self.body(ident,video));self.assertEqual((status,first['review']['state']),(200,'confirmed'))
        with self.app.connect() as c:c.execute('DROP TABLE record_video_reviews')
        remaining=self.tables();self.assertNotIn('record_video_reviews',remaining);self.assertIn('record_video_drafts',remaining)
        reads,statements=self.traced_reads(ident)
        self.assertEqual([(status,result['videos'][0]['state'],result['videos'][0]['review']['state'],'selected' in result['videos'][0]['review']) for status,result in reads],[(200,'ready','unconfirmed',False)]*2)
        self.assertEqual(self.tables(),remaining,'the read created no table')
        for name,prepare in (('absent',lambda path:None),('empty',lambda path:path.write_bytes(b''))):
            path=self.app.DATA/('synthetic-%s.sqlite3'%name);prepare(path);before=self.calls()
            with self.subTest(database=name),mock.patch.object(self.app,'DB',path):
                status,refused,_=self.request('/api/record/video?record_id=%d'%ident)
            self.assertEqual((status,refused.get('code'),set(refused),self.calls()),(503,'storage_unavailable',{'error','code'},before))
            for leak in ('sqlite','no such table','OperationalError',str(path)):self.assertNotIn(leak,json.dumps(refused,ensure_ascii=False))
            self.assertEqual((path.exists(),path.stat().st_size if path.exists() else None),(name=='empty',0 if name=='empty' else None),'the read created no database file or table')

    def test_the_parent_confirms_retries_revokes_and_reconfirms_and_the_read_shows_only_the_current_version(self):
        ident,video=self.ready();self.assertEqual(self.rows('record_video_reviews'),0)
        reads,statements=self.traced_reads(ident);self.assertEqual([status for status,_ in reads],[200,200]);self.assertEqual(reads[0],reads[1],'a repeated read is the same read')
        self.assertTrue(any('record_video_reviews' in s for s in statements),'the read consults the review table without creating it')
        status,first=self.post(self.body(ident,video,selected=[1,0]));again=self.post(self.body(ident,video,selected=[0,1]))[1]
        self.assertEqual((status,first['repeated'],again['repeated'],again['id'],self.rows('record_video_reviews')),(200,False,True,first['id'],1))
        self.assertEqual({k:v for k,v in again.items() if k!='repeated'},{k:v for k,v in first.items() if k!='repeated'})
        shown=first['review'];self.assertEqual((shown['state'],shown['selected'],shown['observations'],shown['uncertainties'],shown['duration_seconds'],shown['audio_assessed']),
                         ('confirmed',[0,1],TWO['observations'],TWO['uncertainties'],12.5,False))
        self.assertEqual((first['token'],first['task_id'],self.video(ident)[1]['videos'][0]['review']),(video['token'],self.TASK,shown),'the existing read shows the confirmation of this version')
        status,revoked=self.post(self.body(ident,video,action='revoke',selected=[]))
        self.assertEqual((status,revoked['id'],revoked['action'],revoked['review']['state'],self.rows('record_video_reviews')),(200,first['id']+1,'revoke','unconfirmed',2))
        self.assertEqual(self.video(ident)[1]['videos'][0]['review']['state'],'unconfirmed')
        self.assertEqual((self.post(self.body(ident,video,action='revoke',selected=[]))[1]['id'],self.rows('record_video_reviews')),(revoked['id'],2),'the same revocation again adds no row')
        status,second=self.post(self.body(ident,video,selected=[1]))
        self.assertEqual((status,second['id'],second['repeated'],second['review']['observations'],self.rows('record_video_reviews')),(200,first['id']+2,False,[TWO['observations'][1]],3))
        with self.app.connect() as c:history=[(r[0],r[1],json.loads(r[2])['selected']) for r in c.execute('SELECT id,action,payload FROM record_video_reviews ORDER BY id')]
        self.assertEqual(history,[(first['id'],'confirm',[0,1]),(first['id']+1,'revoke',[]),(first['id']+2,'confirm',[1])],'history is appended, never rewritten')
        self.assertEqual(self.rows('record_video_drafts'),1)

    def test_anonymous_child_and_token_less_requests_never_reach_the_review_and_write_nothing(self):
        ident,video=self.ready();good=self.body(ident,video)
        for token in (False,'invalid-token'):self.refused(good,403,'csrf_expired',token=token)
        child=self.app.family_child;child.parent_action(self.app,'study',dict(child_id='child-1',enabled=True))
        status,state,headers=self.request('/child/api/login',dict(invite=child.parent_action(self.app,'invite',dict(child_id='child-1'))['invite']));self.assertEqual(status,200)
        cookie={'Cookie':headers['Set-Cookie'].split(';',1)[0]};kid=cookie|{'X-Child-CSRF':state['csrf']}
        for who in (cookie,kid):self.refused(good,403,headers=who)  # a child's own session is not a parent, even with the page token
        self.entry('https://'+self.PUBLIC+'/family');self.addCleanup((self.app.DATA/'access.json').unlink)
        for who in ({},cookie,kid):
            for token in (True,False):self.refused(good,401,headers=who,host=self.PUBLIC,token=token)
        basic={'Authorization':'Basic '+base64.b64encode(('parent:'+self.PASSWORD).encode()).decode('ascii')}
        self.refused(good,403,'csrf_expired',headers=basic,host=self.PUBLIC,token=False)
        status,done=self.post(good,headers=basic,host=self.PUBLIC);self.assertEqual((status,done['review']['state'],self.rows('record_video_reviews')),(200,'confirmed',1))
        self.assertEqual(self.video(ident,headers=basic,host=self.PUBLIC)[1]['videos'][0]['review']['state'],'confirmed')
        self.entry('http://'+self.LAN);revoke=dict(good,action='revoke',selected=[])
        with mock.patch.dict(os.environ,FAMILY_LAN_NO_LOGIN='1'):
            for who in (cookie,kid):self.refused(revoke,403,headers=who,host=self.LAN)
            self.refused(revoke,403,'csrf_expired',host=self.LAN,token=False)
            status,revoked=self.post(revoke,host=self.LAN);self.assertEqual((status,revoked['action'],self.rows('record_video_reviews')),(200,'revoke',2))
        self.assertEqual(self.video(ident)[1]['videos'][0]['review']['state'],'unconfirmed')

    def test_malformed_bodies_get_400_and_stale_or_missing_versions_409_without_a_row(self):
        ident,video=self.ready();good=self.body(ident,video)
        for bad in (dict(good,selected=[True]),dict(good,selected=[[0]]),dict(good,selected=[{}]),dict(good,selected=['0']),dict(good,selected=[0,0]),dict(good,selected=[2]),dict(good,selected=[-1]),
                    dict(good,selected=[]),dict(good,selected=None),dict(good,selected=0),dict(good,selected=[0]*(tv.MAX_OBSERVATIONS+1)),dict(good,record_id=True),dict(good,record_id=str(ident)),
                    dict(good,record_id=0),dict(good,upload_id=''),dict(good,expected_token=video['token'][:-1]),dict(good,expected_token=video['token'].upper()),dict(good,action='approve'),
                    dict(good,action='revoke',selected=[0]),dict(good,text='虚构：家长自己写的观察'),dict(good,observations=TWO['observations']),dict(good,audio_assessed=True),
                    [good],'null',dict(good,padding='x'*20000)):
            with self.subTest(body=str(bad)[:120]):self.refused(bad,400)
        other=self.linked(self.TASK)  # a valid token belongs to one record's one draft only
        self.refused(dict(good,record_id=other),409,'original_missing');self.refused(dict(good,expected_token='0'*64),409,'token_stale')
        self.refused(dict(good,action='revoke',selected=[]),409,'review_not_confirmed');self.refused(dict(good,upload_id=self.clip()),409,'original_missing');self.refused(dict(good,record_id=ident+1000),409)
        self.assertEqual((self.video(ident)[1]['videos'][0]['review']['state'],self.rows('record_video_reviews')),('unconfirmed',0))

    def test_a_correction_a_moved_link_withdrawn_authorization_or_a_new_draft_hides_the_confirmation_and_refuses_the_old_token(self):
        def replacement(ident):
            def replace():
                with self.app.connect() as c:
                    payload=json.loads(c.execute('SELECT payload FROM record_video_drafts WHERE record_id=?',(ident,)).fetchone()[0])
                    payload['draft']['observations'][0]['text']='虚构：后台重新整理后的观察'
                    c.execute('UPDATE record_video_drafts SET payload=? WHERE record_id=?',(json.dumps(payload,ensure_ascii=False),ident))
            return replace
        for name,change,expected in (('correct',self.correct,('pending',)),('relink',self.relink,('pending','unavailable')),('disable',lambda ident:lambda:self.enable(False),('unavailable',)),('draft',replacement,('ready',))):
            with self.subTest(change=name):
                self.enable(True);ident,video=self.ready();status,first=self.post(self.body(ident,video));self.assertEqual((status,first['review']['state']),(200,'confirmed'))
                rows=self.rows('record_video_reviews');change(ident)();shown=self.video(ident)[1]['videos'][0]
                self.assertIn(shown['state'],expected);self.assertNotEqual(shown.get('review',{}).get('state'),'confirmed')
                if shown['state']=='ready':self.assertNotEqual(shown['token'],video['token']);self.assertEqual(shown['review']['state'],'unconfirmed')
                self.refused(self.body(ident,video),409);self.refused(self.body(ident,video,action='revoke',selected=[]),409)
                self.assertEqual(self.rows('record_video_reviews'),rows,'the old confirmation stays on disk, hidden, never erased')
                if shown['state']=='ready':self.assertEqual(self.post(self.body(ident,shown))[1]['review']['state'],'confirmed')


class AudioTrackTests(unittest.TestCase):
    """audio_track with python one-liners standing in for ffprobe/ffmpeg: no real media, no model, no file, no orphan."""
    STREAMS=dict(streams=[dict(codec_type='video',start_time='0.000000'),dict(codec_type='audio',start_time='0.250000')],format=dict(duration='12.500000'))
    PROBE="import sys,json;sys.stdin.buffer.read();print(json.dumps(%s))"
    PACKETS="import sys;sys.stdin.buffer.read();print('0,1');print('1,1.5')"
    DECODE="import sys;sys.stdin.buffer.read();sys.stdout.buffer.write(bytes(range(256))*%d)"
    ECHO="import sys;d=sys.stdin.buffer.read();sys.stdout.buffer.write(d[:len(d)//2*2])"

    def probe(self,**changes):return self.PROBE%repr(dict(self.STREAMS,**changes))

    def run_fake(self,probe=None,decode=None,body=b'synthetic mp4',mime='video/mp4',timeout=3,packets=None,missing=()):
        real=subprocess.Popen;children=[];self.calls=[]
        def child(args,**kwargs):
            self.calls.append(args);tool=args[0];self.assertIn(tool,('ffprobe','ffmpeg'))
            if tool in missing:raise FileNotFoundError(tool)
            code=(packets or self.PACKETS) if any(a.startswith('packet=') for a in args) else probe if tool=='ffprobe' else decode
            self.assertIsNotNone(code,tool+' was launched although this case must refuse before it')
            p=real([sys.executable,'-c',code],**kwargs);children.append(p);return p
        started=time.monotonic()
        try:
            with mock.patch.object(tv.subprocess,'Popen',side_effect=child):return tv.audio_track(body,mime,timeout)
        finally:
            self.assertTrue(all(p.poll() is not None for p in children),'no orphan process')
            self.assertLess(time.monotonic()-started,timeout+2)

    def refused(self,code,**kwargs):
        with self.assertRaises(tv.VideoDraftError) as caught:self.run_fake(**kwargs)
        self.assertEqual(caught.exception.code,code);return caught.exception

    def test_the_one_track_becomes_wav_with_positions_and_nothing_is_assessed(self):
        result=self.run_fake(self.probe(),self.DECODE%250)
        with wave.open(io.BytesIO(result['wav'])) as w:
            self.assertEqual((w.getnchannels(),w.getsampwidth(),w.getframerate(),w.getnframes()),(1,2,16000,32000))
            self.assertEqual(w.readframes(32000),bytes(range(256))*250)
        self.assertEqual(len(result['wav']),44+64000)
        self.assertEqual({k:v for k,v in result.items() if k!='wav'},dict(mime='audio/wav',sample_rate=16000,channels=1,sample_width=2,
            video_seconds=12.5,audio_start_seconds=0.25,pcm_seconds=2.0,audio_assessed=False,tail_verified=False,note=tv.AUDIO_NOTE))
        self.assertIs(result['audio_assessed'],False);self.assertIs(result['tail_verified'],False)
        for word in ('未转写','未评估发音','不代表完成或掌握','不能证明未提供原录像的尾部'):self.assertIn(word,result['note'])
        self.assertEqual([a[0] for a in self.calls],['ffprobe','ffmpeg'])
        for args in self.calls:
            self.assertEqual(args[args.index('-protocol_whitelist')+1],'pipe');self.assertEqual(args[args.index('-i')+1],'pipe:0')
            self.assertEqual(args[args.index('-f')+1],'mov');self.assertEqual(args[args.index('-v')+1],'error')
            self.assertFalse([a for a in args if '/' in a or '://' in a or a in('-t','-ss','-to','-frames','-fs')],args)
        decode=self.calls[1];self.assertIn('-nostdin',decode);self.assertEqual(decode[-1],'pipe:1')
        self.assertEqual(decode[decode.index('-map')+1],'0:a:0');self.assertEqual(decode[decode.index('-ar')+1:decode.index('-ar')+4],['16000','-c:a','pcm_s16le'])
        self.assertEqual(decode[decode.index('-ac')+1],'1');self.assertEqual(decode[decode.index('-f',decode.index('pipe:0'))+1],'s16le')
        # A multi-MiB original is delivered whole through the non-blocking stdin writer and comes back whole.
        body=bytes(range(256))*12288;result=self.run_fake(self.probe(),self.ECHO,body=body,timeout=10)
        self.assertEqual(result['wav'][44:],body);self.assertEqual(result['pcm_seconds'],len(body)/32000)
        # WebM: matroska demux for all three launches, duration from the scanned video packets, not from the header.
        result=self.run_fake(self.probe(format={}),self.DECODE%250,body=b'synthetic webm',mime='video/webm')
        self.assertEqual((result['video_seconds'],result['pcm_seconds']),(2.5,2.0))
        self.assertEqual([(a[0],a[a.index('-f')+1]) for a in self.calls],[('ffprobe','matroska'),('ffprobe','matroska'),('ffmpeg','matroska')])
        for timeout in (30,30.0,0.5):self.run_fake(self.probe(),self.DECODE%250,timeout=timeout)
        # AAC priming can put the audio start slightly before zero; it is reported, not hidden.
        self.assertEqual(self.run_fake(self.probe(streams=[dict(codec_type='video'),dict(codec_type='audio',start_time='-0.023220')]),self.DECODE%250)['audio_start_seconds'],-0.02322)

    def test_no_audio_several_audio_audio_only_bad_positions_and_bad_headers_are_refused_before_decoding(self):
        video=dict(codec_type='video',start_time='0');audio=dict(codec_type='audio',start_time='0')
        for streams,code in (([video],'audio_track_missing'),([video,audio,audio],'audio_track_ambiguous'),([audio],'no_video_track'),
                             ([video,audio,dict(codec_type='audio')],'audio_track_ambiguous'),([],'probe_failed'),([video]*33+[audio],'probe_failed'),
                             (['video'],'probe_failed'),([video,dict(codec_type='audio',start_time='N/A')],'audio_start_invalid'),
                             ([video,dict(codec_type='audio',start_time='13')],'audio_start_invalid'),([video,dict(codec_type='audio',start_time='-1.5')],'audio_start_invalid'),
                             ([video,dict(codec_type='audio')],'audio_start_invalid')):
            with self.subTest(streams=streams):self.refused(code,probe=self.probe(streams=streams))
        for duration,code in (('601','duration_invalid'),('0','duration_invalid'),('N/A','duration_invalid'),(None,'duration_invalid'),('inf','duration_invalid')):
            with self.subTest(duration=duration):self.refused(code,probe=self.probe(format=dict(duration=duration)))
        self.refused('probe_failed',probe="import sys;sys.stdin.buffer.read();print('not json')")
        self.refused('probe_failed',probe="import sys;sys.stdin.buffer.read();print('[]')")
        self.refused('probe_failed',probe="import sys;sys.stdin.buffer.read();sys.stderr.write('moov atom not found');print(%r)"%json.dumps(self.STREAMS))
        self.refused('probe_failed',probe="import sys;sys.exit(1)")
        self.refused('audio_timeout',probe="import time;time.sleep(10)",timeout=1)
        # WebM without a scannable timeline: the header duration is never used instead.
        self.refused('webm_duration_unsupported',probe=self.probe(),mime='video/webm',packets="import sys;sys.stdin.buffer.read();sys.stderr.write('File ended prematurely');print('0,2')")
        self.assertEqual([a[0] for a in self.calls],['ffprobe','ffprobe'])

    def test_errors_on_exit_zero_bad_exit_odd_empty_partial_and_hanging_decodes_are_refused_without_a_prefix(self):
        for code,decode in (('audio_decode_failed',"import sys;sys.stdin.buffer.read();sys.stderr.write('pipe:0: Invalid data found');sys.stdout.buffer.write(b'\\x00'*64000)"),
                            ('audio_decode_failed',"import sys;sys.stdin.buffer.read();sys.stdout.buffer.write(b'\\x00'*64000);sys.exit(1)"),
                            ('audio_decode_failed',"import sys;sys.stdin.buffer.read();sys.stdout.buffer.write(b'\\x00'*64001)"),
                            ('audio_decode_failed',"import sys;sys.stdin.buffer.read()"),
                            ('audio_timeout',"import sys,time;sys.stdout.buffer.write(b'\\x00'*64000);sys.stdout.flush();time.sleep(10)"),
                            ('audio_timeout',"import time;time.sleep(10)")):
            with self.subTest(decode=decode):
                self.refused(code,probe=self.probe(),decode=decode,body=bytes(range(256))*4096,timeout=1)
                self.assertEqual([a[0] for a in self.calls],['ffprobe','ffmpeg'])

    def test_output_cap_missing_tools_invalid_timeouts_and_bad_inputs_launch_nothing_or_stop_early(self):
        with mock.patch.object(tv,'MAX_PCM',100):
            self.refused('audio_too_large',probe=self.probe(),decode=self.DECODE%250)
            self.refused('audio_too_large',probe=self.probe(),decode="import sys\nwhile True:sys.stdout.buffer.write(b'\\x00'*65536)",timeout=2)
        self.assertEqual(self.refused('probe_missing',probe=self.probe(),decode=self.DECODE%250,missing=('ffprobe',)).args[0],tv.EXPLANATIONS['probe_missing'])
        self.refused('ffmpeg_missing',probe=self.probe(),decode=self.DECODE%250,missing=('ffmpeg',))
        self.assertEqual([a[0] for a in self.calls],['ffprobe','ffmpeg'])
        with mock.patch.object(tv.subprocess,'Popen') as launch:
            for timeout in (True,False,0,-1,31,10**1000,30.000001,float('nan'),float('inf'),float('-inf'),'5',None,[5]):
                with self.subTest(timeout=timeout),self.assertRaises(tv.VideoDraftError) as caught:tv.audio_track(b'x','video/mp4',timeout)
                self.assertEqual(caught.exception.code,'timeout_invalid')
            for body,mime,code in ((b'','video/mp4','original_unavailable'),('text','video/mp4','original_unavailable'),(None,'video/mp4','original_unavailable'),
                                   (b'\x00'*(family_llm.MAX_INPUT+1),'video/mp4','original_too_large'),(b'x','audio/webm','audio_mime_unsupported'),
                                   (b'x','video/x-msvideo','audio_mime_unsupported'),(b'x',None,'audio_mime_unsupported'),(b'x','','audio_mime_unsupported')):
                with self.subTest(mime=mime,code=code),self.assertRaises(tv.VideoDraftError) as caught:tv.audio_track(body,mime)
                self.assertEqual(caught.exception.code,code)
            launch.assert_not_called()
        self.assertEqual(tv.audio_track.__defaults__, (30,))
        self.assertEqual(tv.AUDIO_TIMEOUT,30);self.assertEqual(tv.MAX_PCM+44,family_llm.MAX_INPUT)

    def test_expired_deadline_starts_nothing_and_late_parse_or_wav_is_discarded(self):
        with mock.patch.object(tv.subprocess,'Popen') as launch:
            with self.assertRaises(tv.VideoDraftError) as caught:
                tv._piped(['ffprobe'], b'x', time.monotonic()-1, 100, 'probe_failed', late='audio_timeout')
            self.assertEqual(caught.exception.code,'audio_timeout');launch.assert_not_called()
        # Time spent parsing the probe counts too: it must not start the decoder afterwards.
        clock=[0.0];loads=json.loads
        def late_json(*args,**kwargs):
            result=loads(*args,**kwargs);clock[0]=31.0;return result
        with mock.patch.object(tv.time,'monotonic',side_effect=lambda:clock[0]),mock.patch.object(tv.json,'loads',side_effect=late_json):
            self.refused('audio_timeout',probe=self.probe(),timeout=30)
            self.assertEqual([a[0] for a in self.calls],['ffprobe'])
        clock[0]=0.0;write=wave.Wave_write.writeframes
        def late_wav(w,data):
            result=write(w,data);clock[0]=31.0;return result
        with mock.patch.object(tv.time,'monotonic',side_effect=lambda:clock[0]),mock.patch.object(wave.Wave_write,'writeframes',late_wav):
            self.refused('audio_timeout',probe=self.probe(),decode=self.DECODE%250,timeout=30)
            self.assertEqual([a[0] for a in self.calls],['ffprobe','ffmpeg'])

    def test_pcm_and_offset_have_a_strict_600_second_bound_without_trimming(self):
        for frames,start,valid in ((600*16000,0,True),(600*16000+1,0,False),(600*16000,1,False)):
            header=dict(streams=[dict(codec_type='video'),dict(codec_type='audio',start_time=start)],format=dict(duration=600))
            pcm=b'\0\0'*frames
            with mock.patch.object(tv,'_piped',side_effect=[json.dumps(header).encode(),pcm]):
                if valid:
                    result=tv.audio_track(b'synthetic','video/mp4')
                    self.assertEqual((result['video_seconds'],result['pcm_seconds'],len(result['wav'])),(600,600,len(pcm)+44))
                else:
                    with self.assertRaises(tv.VideoDraftError) as caught:tv.audio_track(b'synthetic','video/mp4')
                    self.assertEqual(caught.exception.code,'duration_invalid')


class RealAudioTrackTests(unittest.TestCase):
    """Optional: synthetic sine + colour clips through the installed ffmpeg/ffprobe. No household media, no model."""
    @classmethod
    def setUpClass(cls):
        if not shutil.which('ffmpeg') or not shutil.which('ffprobe'):
            raise unittest.SkipTest('optional local ffmpeg/ffprobe tools unavailable')
        video=['-f','lavfi','-i','color=c=blue:s=160x120:r=10:d=2'];tone=['-f','lavfi','-i','sine=frequency=440:duration=2']
        def run(args):return REAL_RUN(['ffmpeg','-v','error']+args,capture_output=True,check=True,timeout=30).stdout
        with tempfile.TemporaryDirectory() as directory:
            for name,codec in (('clip.mp4','mpeg4'),('clip.mov','mpeg4')):
                path=os.path.join(directory,name);run(video+tone+['-c:v',codec,'-c:a','aac','-movflags','+faststart',path])
                with open(path,'rb') as stream:setattr(cls,name.split('.')[1],stream.read())
        cls.webm=run(video+tone+['-c:v','libvpx','-c:a','libopus','-f','webm','pipe:1'])
        cls.silent=run(video+['-c:v','libvpx','-f','webm','pipe:1'])
        cls.two=run(video+tone+['-map','0:v','-map','1:a','-map','1:a','-c:v','libvpx','-c:a','libopus','-f','webm','pipe:1'])
        cls.audio=run(tone+['-c:a','libopus','-f','webm','pipe:1'])

    def test_real_mp4_mov_and_pipe_webm_decode_and_bad_variants_are_refused(self):
        for body,mime in ((self.mp4,'video/mp4'),(self.mov,'video/quicktime'),(self.webm,'video/webm')):
            with self.subTest(mime=mime):
                started=time.monotonic();result=tv.audio_track(body,mime);elapsed=time.monotonic()-started
                self.assertLess(elapsed,30)
                with wave.open(io.BytesIO(result['wav'])) as w:
                    self.assertEqual((w.getnchannels(),w.getsampwidth(),w.getframerate()),(1,2,16000));frames=w.readframes(w.getnframes())
                self.assertEqual(len(frames),len(result['wav'])-44)
                self.assertAlmostEqual(result['video_seconds'],2.0,delta=0.15);self.assertAlmostEqual(result['pcm_seconds'],2.0,delta=0.15)
                self.assertTrue(-0.1<=result['audio_start_seconds']<=0.5,result['audio_start_seconds'])
                self.assertGreater(max(abs(int.from_bytes(frames[i:i+2],'little',signed=True)) for i in range(0,len(frames),2)),3000,'a 440Hz tone is not silence')
                self.assertEqual((result['audio_assessed'],result['tail_verified']),(False,False))
        for body,mime,code in ((self.silent,'video/webm','audio_track_missing'),(self.two,'video/webm','audio_track_ambiguous'),(self.audio,'video/webm','no_video_track')):
            with self.subTest(code=code),self.assertRaises(tv.VideoDraftError) as caught:tv.audio_track(body,mime)
            self.assertEqual(caught.exception.code,code)
        for body,mime in ((self.mp4,'video/mp4'),(self.webm,'video/webm')):
            for cut in (1,40,len(body)//3):
                with self.subTest(mime=mime,cut=cut),self.assertRaises(tv.VideoDraftError):tv.audio_track(body[:-cut],mime)
        with self.assertRaises(tv.VideoDraftError) as caught:tv.audio_track(self.mp4,'video/webm')
        self.assertIn(caught.exception.code,('probe_failed','webm_duration_unsupported'))

    def test_audio_tail_and_offset_count_towards_the_whole_media_bound(self):
        def clip(seconds,offset=0):
            return REAL_RUN(['ffmpeg','-v','error','-f','lavfi','-i','color=c=blue:s=16x16:r=1:d=2',
                '-itsoffset',str(offset),'-f','lavfi','-i',f'anullsrc=r=16000:cl=mono:d={seconds}',
                '-c:v','libvpx','-c:a','libopus','-f','webm','pipe:1'],capture_output=True,check=True,timeout=30).stdout
        for seconds,offset in ((4,0),(1,5)):
            result=tv.audio_track(clip(seconds,offset),'video/webm')
            self.assertAlmostEqual(result['pcm_seconds'],seconds,delta=0.05)
            self.assertAlmostEqual(result['audio_start_seconds'],offset,delta=0.05)
            self.assertAlmostEqual(result['video_seconds'],offset+seconds,delta=0.05)
        for seconds,offset in ((601,0),(2,599)):
            with self.subTest(seconds=seconds,offset=offset):
                body=clip(seconds,offset);piped=tv._piped;calls=[]
                def track(args,*a,**kw):
                    calls.append(args[0]);return piped(args,*a,**kw)
                with mock.patch.object(tv,'_piped',side_effect=track),self.assertRaises(tv.VideoDraftError) as caught:
                    tv.audio_track(body,'video/webm')
                self.assertEqual(caught.exception.code,'duration_invalid')
                self.assertNotIn('ffmpeg',calls,'refuse before decoding an overlong supplied timeline')


if __name__=='__main__':unittest.main()


class VideoEvidenceTests(unittest.TestCase):
    """#23: the parent's effective confirmation of listed observations joins the linked goal's one record item; nothing else of the video does."""
    enable=TaskVideoTests.enable;ffprobe=TaskVideoTests.ffprobe;chat=TaskVideoTests.chat;clip=TaskVideoTests.clip
    feedback=TaskVideoTests.feedback;record=TaskVideoTests.record;linked=TaskVideoTests.linked;relink=TaskVideoTests.relink;correct=TaskVideoTests.correct
    tick=TaskVideoTests.tick;lines=TaskVideoTests.lines;files=TaskVideoTests.files;rows=TaskVideoTests.rows;view=TaskVideoTests.view;state=TaskVideoTests.state
    action=TaskVideoTests.action;reply=TaskVideoTests.reply;TASK=TaskVideoTests.TASK;OTHER=TaskVideoTests.OTHER;SIBLING=TaskVideoTests.SIBLING
    ready=VideoReviewTests.ready;body=VideoReviewTests.body;other=VideoReviewTests.other;review=VideoReviewTests.review;goal=test_goals.GoalTests.goal

    def setUp(self):
        TaskVideoTests.setUp(self);self.store=goals.Store(self.app,self.agent);self.inputs=[];self.replies=[]  # the goal store reads the resolved data path

    def ctx(self):
        """Every goal read also proves that it writes nothing, probes nothing and calls no model."""
        before=(self.lines(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent))
        with self.agent._db() as c:result=self.store._context(c,self.store._get(c,self.ident))
        self.assertEqual((self.lines(),self.files(),subprocess.run.call_count,self.model.call_count,len(self.probes),len(self.sent)),before);return result

    def text(self,ctx):return agent._json(ctx['evidence'])
    def rec(self,ctx,ident):return next(r for r in ctx['records'] if r['id']==ident)
    def obs(self,i):return TWO['observations'][i]['text']

    def item(self,ctx,ident):
        items=[e for e in ctx['evidence'] if e['ref']=='record:%d'%ident];self.assertEqual(len(items),1);return items[0]

    def plan(self,during=None,cite=None):
        """The goal's model: records its input, runs `during` while in flight and answers a legal plan, quoting `cite` (ref, quote) if given."""
        def reply(messages,schema,name,timeout,**kwargs):
            if name=='family_video_feedback_draft':return self.chat(messages,schema,name,timeout,**kwargs)
            value=json.loads(messages[-1]['content']);self.inputs.append(value)
            if during:during()
            result=test_goals.synthetic_plan(value)
            if cite:result['proposal']['evidence']=[dict(ref=cite[0],quote=cite[1])]
            self.replies.append(result);return result
        self.model.side_effect=reply

    def replace_draft(self,ident):
        """The background job re-saving a different draft for the same fingerprint: a new token the parent never reviewed."""
        def replace():
            with self.app.connect() as c:
                payload=json.loads(c.execute('SELECT payload FROM record_video_drafts WHERE record_id=?',(ident,)).fetchone()[0])
                payload['draft']['observations'][0]['text']='虚构：后台重新整理后的观察'
                c.execute('UPDATE record_video_drafts SET payload=? WHERE record_id=?',(json.dumps(payload,ensure_ascii=False),ident))
        return replace

    def stored(self,ident):
        with self.app.connect() as c:
            return tuple(tuple(c.execute(sql,arg).fetchone()) for sql,arg in (('SELECT * FROM records WHERE id=?',(ident,)),
                ('SELECT * FROM manual_tasks WHERE id=?',(self.TASK,)),('SELECT plan,state,task_id FROM agent_items WHERE id=?',(self.ident,))))

    def test_only_the_parents_selected_observations_join_the_records_one_item_and_leave_with_a_revocation(self):
        ident,video=self.ready();empty=self.ctx();plain=self.rec(empty,ident);before=self.stored(ident)
        self.assertNotIn('video_observations',plain);self.assertNotIn('media_unread',self.item(empty,ident))
        for i in (0,1):self.assertNotIn(self.obs(i),self.text(empty))
        first=self.review(self.body(ident,video,selected=[1]));ctx=self.ctx();shown=self.rec(ctx,ident)
        self.assertEqual((len(ctx['records']),[e['ref'] for e in ctx['evidence']]),(len(empty['records']),[e['ref'] for e in empty['evidence']]))
        self.assertEqual(shown['video_observations'],[dict(kind='parent_checked_video',label=tv.REVIEW_LABEL,upload_id=video['upload_id'],review_id=first['id'],token=video['token'],
            reviewed_at=first['reviewed_at'],selected=[1],observations=[TWO['observations'][1]],uncertainties=TWO['uncertainties'],duration_seconds=12.5,audio_assessed=False)])
        self.assertEqual((shown['video_observations_label'],shown['audio_assessed']),(goals.family_learner_memory.VIDEO_CHECKED,False))
        self.assertEqual({k:v for k,v in shown.items() if k in plain},plain)  # the record's own fields read exactly as before
        for key in ('media_unread','other_media_unread'):self.assertNotIn(key,shown);self.assertNotIn(key,self.item(ctx,ident))
        self.assertIn(self.obs(1),self.text(ctx));self.assertNotIn(self.obs(0),self.text(ctx));self.assertNotIn('ftypisom',self.text(ctx))
        self.assertEqual(self.stored(ident),before)  # confirmation changes no record, task or goal plan
        self.assertNotEqual(empty['evidence_hash'],ctx['evidence_hash']);self.assertEqual(self.ctx()['evidence_hash'],ctx['evidence_hash'])
        self.review(self.body(ident,video,action='revoke',selected=[]));revoked=self.ctx()
        self.assertEqual(revoked['evidence_hash'],empty['evidence_hash']);self.assertNotIn(self.obs(1),self.text(revoked));self.assertNotIn('video_observations',self.rec(revoked,ident))
        second=self.review(self.body(ident,video,selected=[0]));again=self.ctx()
        self.assertIn(self.obs(0),self.text(again));self.assertNotIn(self.obs(1),self.text(again));self.assertNotEqual(again['evidence_hash'],ctx['evidence_hash'])
        self.assertEqual(self.rec(again,ident)['video_observations'][0]['review_id'],second['id']);self.assertEqual(self.stored(ident),before)

    def test_the_goal_read_runs_no_write_no_probe_and_no_model_even_with_a_confirmation(self):
        ident,video=self.ready();self.review(self.body(ident,video));statements=[];connect=self.agent.connect
        def traced():
            c=connect();c.set_trace_callback(statements.append);return c
        with mock.patch.object(self.agent,'connect',traced):ctx=self.ctx();self.ctx()
        self.assertIn(self.obs(0),self.text(ctx));self.assertTrue(statements)
        self.assertEqual([s for s in statements if s.split()[0].upper() in ('INSERT','UPDATE','DELETE','CREATE','DROP','ALTER','REPLACE')],[])
        with self.app.connect() as c:c.execute('DROP TABLE record_video_reviews')
        self.assertNotIn(self.obs(0),self.text(self.ctx()))  # an older database without the table reads as unconfirmed

    def test_a_correction_relink_changed_bytes_new_draft_shared_original_or_withdrawn_switch_removes_it_and_moves_the_hash(self):
        def hash_change(ident):
            path=self.data/'uploads'/self.uploads[ident];return lambda:path.write_bytes(b'Y'+path.read_bytes()[1:])
        def draft_replacement(ident):
            def replace():
                with self.app.connect() as c:
                    payload=json.loads(c.execute('SELECT payload FROM record_video_drafts WHERE record_id=?',(ident,)).fetchone()[0])
                    payload['draft']['observations'][0]['text']='虚构：后台重新整理后的观察'
                    c.execute('UPDATE record_video_drafts SET payload=? WHERE record_id=?',(json.dumps(payload,ensure_ascii=False),ident))
            return replace
        def cross_child(ident):
            def share():
                with self.app.connect() as c:
                    c.execute("INSERT INTO records(child,day,category,subject,title,note,source,created,attachments) VALUES('示例乙',?,'学习进展','英语','虚构','虚构','家长网页记录',?,?)",
                              (self.now.date().isoformat(),self.now.isoformat(),json.dumps([self.uploads[ident]])))
            return share
        for name,change in (('correct',self.correct),('relink',self.relink),('hash',hash_change),('draft',draft_replacement),('cross_child',cross_child),('disable',lambda ident:lambda:self.enable(False))):
            with self.subTest(change=name):
                ident,video=self.ready();self.review(self.body(ident,video));confirmed=self.ctx()
                self.assertEqual(self.rec(confirmed,ident)['video_observations'][0]['token'],video['token']);rows=self.rows('record_video_reviews')
                change(ident)();changed=self.ctx();self.assertNotEqual(changed['evidence_hash'],confirmed['evidence_hash'])
                items=[e for e in changed['evidence'] if e['ref']=='record:%d'%ident];self.assertLessEqual(len(items),1)
                for e in items:self.assertNotIn(self.obs(0),e['text']);self.assertNotIn(video['token'],e['text'])
                self.assertFalse([r for r in changed['records'] if r['id']==ident and r.get('video_observations')])
                self.assertNotIn('后台重新整理',self.text(changed));self.assertEqual(self.rows('record_video_reviews'),rows)

    def test_an_unrelated_goal_of_the_same_subject_gets_nothing_while_an_explicitly_linked_record_does(self):
        ident,video=self.ready();self.review(self.body(ident,video))
        self.ident=self.action('create',child_id='child-1',title='虚构同科无关目标',subject='英语',baseline='虚构背景')['id'];unrelated=self.ctx()
        self.assertFalse([e for e in unrelated['evidence'] if e['ref'].startswith('record:')]);self.assertNotIn(self.obs(0),self.text(unrelated))
        self.ident=self.action('create',child_id='child-1',title='虚构明确关联记录',subject='数学',baseline='虚构背景',record_ids=[ident])['id'];explicit=self.ctx()
        self.assertEqual(self.rec(explicit,ident)['video_observations'][0]['token'],video['token']);self.assertIn(self.obs(0),self.text(explicit))

    def test_a_bare_video_feedback_becomes_readable_only_through_the_parents_confirmation(self):
        rid=self.feedback();ref='record:%d'%rid
        with mock.patch.dict(DRAFT,TWO,clear=True):self.assertEqual(self.tick(),SENT)
        video=self.view(rid)['videos'][0]
        def cite(ctx):
            result=test_goals.synthetic_plan(dict(evidence=ctx['evidence'],as_of=self.now.date().isoformat()))
            result['proposal']['hypotheses']=[dict(reason='虚构原因',support=[ref],against=[],test='请核对本次帮助条件',status='有支持')];return result
        unread=self.ctx();self.assertTrue(self.rec(unread,rid)['media_unread']);self.assertTrue(self.item(unread,rid)['media_unread'])
        with self.assertRaisesRegex(agent.AgentError,'未核对的原件或转写'):self.store._proposal(cite(unread),unread,self.now)
        self.review(self.body(rid,video));checked=self.ctx();shown=self.rec(checked,rid)
        for key in ('media_unread','other_media_unread'):self.assertNotIn(key,shown);self.assertNotIn(key,self.item(checked,rid))
        self.assertEqual(self.store._proposal(cite(checked),checked,self.now)['hypotheses'][0]['support'],[ref])

    def test_a_revocation_during_the_call_drops_the_result_and_acceptance_still_needs_the_parent_with_the_current_evidence(self):
        ident,video=self.ready();self.review(self.body(ident,video));ref='record:%d'%ident
        # An explicitly linked goal: its approval creates its own task and leaves the record's task, hence the draft's context, as it is.
        self.ident=self.action('create',child_id='child-1',title='虚构明确关联记录',subject='英语',baseline='虚构背景',record_ids=[ident])['id']
        self.assertFalse(self.goal()['task_id']);self.assertIn(self.obs(0),self.text(self.ctx()))
        self.plan(during=lambda:self.review(self.body(ident,video,action='revoke',selected=[])))
        calls=self.model.call_count;result=self.store.process(self.ident,self.now,explicit=True)
        self.assertEqual((self.model.call_count,len(self.replies),result),(calls+1,1,dict(state='stale',created=0,used=1)))  # a legal reply, dropped for the evidence
        sent=agent._json(self.inputs[-1]);self.assertIn(self.obs(0),sent);self.assertNotIn(self.obs(1),sent);self.assertIn(video['token'],sent)
        goal=self.goal();self.assertEqual((goal['pending'],goal['current_plan']),(None,None))
        with self.app.connect() as c:self.assertEqual(c.execute("SELECT COUNT(*) FROM agent_items WHERE job_id=? AND state='pending'",('goal:'+self.ident,)).fetchone()[0],0)
        self.plan();self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready');goal=self.goal()
        self.assertEqual((goal['pending']['context_hash'],goal['current_plan']),(self.ctx()['evidence_hash'],None));self.assertNotIn(self.obs(0),agent._json(self.inputs[-1]))
        old=(goal['pending']['id'],goal['context_hash'],goal['version'])
        self.review(self.body(ident,video,selected=[1]));goal=self.goal();self.assertEqual((goal['pending_stale'],goal['pending']),(True,None))
        with self.assertRaises(agent.AgentError) as caught:self.action('approve',id=self.ident,expected_version=old[2],proposal_id=old[0],context_hash=old[1])
        self.assertEqual((caught.exception.status,caught.exception.code,self.goal()['current_plan']),(409,'goal_evidence_changed',None))
        self.plan(cite=(ref,self.obs(1)));calls=self.model.call_count;self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready');goal=self.goal()
        self.assertEqual((self.model.call_count,goal['pending']['context_hash'],goal['current_plan']),(calls+1,goal['context_hash'],None));self.assertIn(self.obs(1),agent._json(self.inputs[-1]))
        self.action('approve',id=self.ident,expected_version=goal['version'],proposal_id=goal['pending']['id'],context_hash=goal['context_hash']);goal=self.goal()
        self.assertEqual((goal['current_plan']['title'],goal['evidence_changed'],goal['pending']),('先核对一个判断过程',False,None))
        self.assertTrue(goal['task_id'].startswith('AGENT-'))  # the goal's own new task; the record's task and the confirmation are untouched
        calls=self.model.call_count;self.assertEqual(self.store.process(self.ident,self.now)['state'],'current');self.assertEqual(self.model.call_count,calls)  # same confirmation: no second call
        with self.app.connect() as c:plan=c.execute('SELECT plan FROM agent_items WHERE id=?',(self.ident,)).fetchone()[0]
        self.review(self.body(ident,video,action='revoke',selected=[]));goal=self.goal()
        self.assertEqual((goal['evidence_changed'],goal['current_plan']['title']),(True,'先核对一个判断过程'))
        with self.app.connect() as c:
            self.assertEqual(c.execute('SELECT plan FROM agent_items WHERE id=?',(self.ident,)).fetchone()[0],plan)
            self.assertEqual(tuple(c.execute('SELECT note,score,linked_task_id FROM records WHERE id=?',(ident,)).fetchone()),('虚构说明',None,self.TASK))
        # Invalid video evidence withholds the old judgment/method from the model; the saved parent plan remains intact.
        self.plan();self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready');sent=self.inputs[-1]
        self.assertEqual((sent['previous_assessment_stale'],sent['previous_context_unavailable'],sent['current_plan']),(True,True,None))
        self.assertNotIn(self.obs(1),agent._json(sent));self.assertNotIn(video['token'],agent._json(sent))

    def test_approving_a_plan_that_rewrites_the_records_own_task_is_a_real_context_change_that_retires_the_confirmation(self):
        ident,video=self.ready();self.review(self.body(ident,video));confirmed=self.ctx();reviews=self.rows('record_video_reviews')
        self.assertEqual(self.goal()['task_id'],self.TASK)  # the goal of setUp owns the record's task, and approval rewrites that task
        def task():
            with self.app.connect() as c:return tuple(c.execute('SELECT title,action FROM manual_tasks WHERE id=?',(self.TASK,)).fetchone())
        def context():
            with self.agent._db() as c:return tv._attribution(self.app,self.agent,c,ident)['task']
        before_task,before=task(),context();self.assertEqual((before['title'],before['requirement']),before_task)
        self.plan();self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready');goal=self.goal()
        self.action('approve',id=self.ident,expected_version=goal['version'],proposal_id=goal['pending']['id'],context_hash=goal['context_hash']);goal=self.goal()
        after_task,after=task(),context()
        self.assertEqual((after_task[0],after['title'],after['requirement']),('先核对一个判断过程',after_task[0],after_task[1]));self.assertNotEqual(after_task,before_task)
        self.assertEqual({k:v for k,v in after.items() if k not in ('title','requirement')},{k:v for k,v in before.items() if k not in ('title','requirement')})
        changed=self.ctx();self.assertTrue(goal['evidence_changed']);self.assertNotEqual(changed['evidence_hash'],confirmed['evidence_hash'])
        self.assertFalse([r for r in changed['records'] if r['id']==ident and r.get('video_observations')])
        self.assertNotIn(self.obs(0),self.text(changed));self.assertNotIn(video['token'],self.text(changed))
        with self.agent._db() as c:self.assertEqual(tv.confirmed(self.app,self.agent,c,ident),[])
        with self.app.connect() as c:self.assertEqual(tuple(c.execute('SELECT note,score,linked_task_id FROM records WHERE id=?',(ident,)).fetchone()),('虚构说明',None,self.TASK))
        with mock.patch.dict(DRAFT,TWO,clear=True):self.tick()  # a draft for the rewritten task is a new version the parent has not reviewed
        fresh=self.view(ident)['videos'][0];self.assertEqual((fresh['state'],fresh['review']['state']),('ready','unconfirmed'));self.assertNotEqual(fresh['token'],video['token'])
        self.assertEqual(self.rows('record_video_reviews'),reviews);self.assertNotIn(self.obs(0),self.text(self.ctx()))

    def test_a_correction_relink_new_draft_or_withdrawn_switch_during_the_call_also_drops_the_legal_reply(self):
        for name,change in (('correct',self.correct),('relink',self.relink),('draft',self.replace_draft),('disable',lambda ident:lambda:self.enable(False))):
            with self.subTest(change=name):
                self.enable(True);ident,video=self.ready();self.review(self.body(ident,video));effect=change(ident);fired=[]
                self.ident=self.action('create',child_id='child-1',title='虚构独立变更检查',subject='英语',baseline='虚构背景',record_ids=[ident])['id']
                self.plan(during=lambda:(effect(),fired.append(name)));calls=self.model.call_count;replies=len(self.replies)
                result=self.store.process(self.ident,self.now,explicit=True)
                self.assertEqual((fired,self.model.call_count,len(self.replies),result),([name],calls+1,replies+1,dict(state='stale',created=0,used=1)))
                self.assertIn(self.obs(0),agent._json(self.inputs[-1]))  # the call itself carried the then-current confirmation
                goal=self.goal();self.assertEqual((goal['pending'],goal['current_plan']),(None,None))
                with self.app.connect() as c:
                    self.assertEqual(c.execute("SELECT COUNT(*) FROM agent_items WHERE job_id=? AND state='pending'",('goal:'+self.ident,)).fetchone()[0],0)
                    self.assertEqual(c.execute('SELECT error FROM agent_jobs WHERE id=?',('goal:'+self.ident,)).fetchone()[0],'')  # dropped, not failed
                self.plan();calls=self.model.call_count;self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready')
                self.assertEqual(self.model.call_count,calls+1);self.assertNotIn(self.obs(0),agent._json(self.inputs[-1]))

    def test_revoked_picture_cannot_return_through_an_accepted_judgment_or_method_history(self):
        ident,video=self.ready();self.review(self.body(ident,video));ref='record:%d'%ident
        self.ident=self.action('create',child_id='child-1',title='虚构明确关联目标',subject='英语',baseline='虚构背景',record_ids=[ident])['id']
        marker=self.obs(0)
        self.plan(cite=(ref,marker));reply=self.model.side_effect
        def copied(*args,**kwargs):
            result=reply(*args,**kwargs);result['proposal'].update(assessment=marker,action=marker)
            result['proposal']['hypotheses'][0].update(reason=marker,support=[ref],status='有支持')
            return result
        self.model.side_effect=copied
        self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready');goal=self.goal()
        self.action('approve',id=self.ident,expected_version=goal['version'],proposal_id=goal['pending']['id'],context_hash=goal['context_hash'])
        self.review(self.body(ident,video,action='revoke',selected=[]));self.plan()
        self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready')
        self.assertNotIn(marker,agent._json(self.inputs[-1]))
        goal=self.goal();self.action('approve',id=self.ident,expected_version=goal['version'],proposal_id=goal['pending']['id'],context_hash=goal['context_hash'])
        self.review(self.body(ident,video,selected=[1]));self.plan()
        self.assertEqual(self.store.process(self.ident,self.now,explicit=True)['state'],'ready')
        self.assertNotIn(marker,agent._json(self.inputs[-1]))
        self.assertIn(self.obs(1),agent._json(self.inputs[-1]))
