// Synthetic real-HTTP parent journey. PLAYWRIGHT_MODULE / PLAYWRIGHT_CHANNEL supported.
const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events'),net=require('node:net'),fs=require('node:fs/promises'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let server,browser;try{
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 server=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['-c',`import sys,json,runpy,family_llm,app,family_agent,tempfile
from pathlib import Path
from test_goals import synthetic_plan
def model(messages,schema,name,*args,**kwargs):
 value=json.loads(messages[-1]['content'])
 if name=='family_agent_selection':
  e=value['evidence'][0]
  return dict(proposals=[dict(title_quote=e['text'],focus='school',due='',learning_subject='语文',learning_goal_id='',evidence=[dict(ref=e['ref'])])])
 if name=='family_agent_plan':return dict(proposal=None)
 return synthetic_plan(value)
family_llm._chat_json=model
prepare=app.prepare_assets
def seed():
 prepare()
 (app.DATA/'agent.json').write_text(json.dumps(dict(enabled=True,sources=[dict(id='synthetic-ui-class',platform='wechat',child_id='child-2',name='虚构课堂',cursor='0',enabled=True)])))
 stamp=family_agent._now().isoformat()
 app.agent_store().ingest(dict(source_id='synthetic-ui-class',expected_cursor='0',cursor='1',checked_at=stamp,last_message_time=stamp,error='',messages=[dict(id='1',time=stamp,kind='text',sender='虚构发布者',text='语文观察：任选一种顺序介绍文具，说出用途和真实细节。',unread=False)]))
 original=app.ROOT
 with tempfile.TemporaryDirectory(prefix='synthetic-ui-worker-') as folder:
  app.ROOT=Path(folder)
  try:
   for name in ('家庭运行规则.md','消息来源.md','学习与成长.md','跟踪台账.md'):(app.ROOT/name).write_text(app.read(name))
   family_agent.run_once(app)
  finally:app.ROOT=original
app.prepare_assets=seed
sys.argv=['demo.py','--port','${port}']
runpy.run_path('demo.py',run_name='__main__')`],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});server.stdout.resume();server.stderr.resume();
 const url='http://127.0.0.1:'+port+'/';let ready=false;for(let i=0;i<100;i++){try{if((await fetch(url)).ok){ready=true;break}}catch{}await wait(80)}assert(ready,'demo started');
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});let checks=0;
 for(const width of [360,1440]){
  const p=await browser.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error('browser error',e.message)});await p.goto(url);await p.locator('.today-dashboard').waitFor();await p.locator('.today-shortcuts [data-page="goals"]').click();await p.locator('[data-goal-form="create"]').waitFor({state:'attached'});
  const create=p.locator('[data-goal-form="create"]');await create.locator('xpath=ancestor::details').evaluate(e=>e.open=true);
  await create.getByLabel('阶段目标',{exact:true}).fill('虚构英语目标 '+width);await create.getByLabel('科目',{exact:true}).fill('英语');await create.getByLabel('目前实际表现',{exact:true}).fill('家长观察：有时猜答案，尚未核对原因。');await create.getByText('补充学校要求或已有材料 · 可选',{exact:true}).click();await create.getByLabel('学校要求 / 考试范围',{exact:true}).fill('虚构老师要求：任选一种说明顺序，介绍文具的用途；未给截止。');await create.getByLabel('家里已有的材料、App、设备',{exact:true}).fill('已有课本和学习机，具体题目待核对');let createLost=false;await p.route('**/api/goals/action',async route=>{if(route.request().postDataJSON().action==='create'&&!createLost){createLost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await create.getByRole('button',{name:'保存学习目标'}).click();await p.getByText(/结果未确认，请点原按钮重试/).waitFor();assert(await p.locator('[data-goal-child-select="child-2"]').isDisabled());await p.locator('[data-goal-retry]').click();await p.unroute('**/api/goals/action');
  await p.locator('[data-goal-form="feedback"]').waitFor();assert(await p.getByText('记下原话或作答就可以，不需要判断原因。保存后，Agent会结合反馈提出下一步。',{exact:true}).isVisible());await p.getByRole('heading',{name:'虚构英语目标 '+width,exact:true}).waitFor();await p.locator('#goal-school-requirement summary').click();assert.match(await p.locator('#goal-school-requirement').innerText(),/任选一种说明顺序/);checks++;
  await p.locator('[data-goal-action="evaluate"]').click();await p.locator('[data-goal-form="approve"]').waitFor();await p.getByText('为什么这样安排 · 判断与依据',{exact:true}).click();await p.getByText('本次引用原文',{exact:true}).click();await p.getByRole('link',{name:'本次学校要求',exact:true}).click();assert(await p.locator('#goal-school-requirement').evaluate(e=>e.open));checks++;
  const manual=p.locator('[data-goal-form="manual"]');await manual.locator('xpath=ancestor::details').evaluate(e=>e.open=true);await manual.getByLabel('家长怎么带着做、怎么问孩子').fill('用已有课本的一道题，听孩子说出选择的理由；困了就结束。');await manual.getByLabel('怎样核对独立掌握').fill('下次用相近题观察能否独立解释，不用完成次数代替掌握。');await manual.getByLabel('一次预计分钟').fill('8');await manual.getByRole('button',{name:'确认计划并安排'}).click();
  await p.locator('[data-goal-task]').waitFor();const original=await p.locator('[data-goal-task]').getAttribute('data-goal-task');assert(original);checks++;
  const feedback=p.locator('[data-goal-form="feedback"]');await feedback.getByLabel('孩子怎么答的、用了什么帮助、用时和感受').fill('虚构反馈：练了八分钟，需要少量提示；孩子愿意口头讲。');await feedback.getByLabel('信息来源').selectOption('家长转述孩子');await feedback.getByLabel('获得的帮助').locator('xpath=ancestor::details').evaluate(e=>e.open=true);await feedback.getByLabel('获得的帮助').selectOption('少量提示');await feedback.locator('input[type="file"]').setInputFiles({name:'synthetic-evidence.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQ0AAAAASUVORK5CYII=','base64')});
  // Simulate a lost response after the server has saved the exact request.
  let intercepted=false;await p.route('**/api/goals/action',async route=>{const body=route.request().postDataJSON();if(body.action==='feedback'&&!intercepted){intercepted=true;await route.fetch();if(width===360)await route.abort('failed');else await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Synthetic failure after save'})})}else await route.continue()});
  await feedback.getByRole('button',{name:'保存反馈'}).click();await p.getByText(/结果未确认，请点原按钮重试/).waitFor();assert(await feedback.getByLabel('孩子怎么答的、用了什么帮助、用时和感受').isDisabled());await feedback.getByRole('button',{name:'保存反馈'}).click();await p.getByText('虚构反馈：练了八分钟，需要少量提示；孩子愿意口头讲。',{exact:true}).waitFor();assert.equal(await p.locator('[data-goal-record]').filter({hasText:'查看'}).count(),1);assert.equal(await p.getByRole('link',{name:'查看原件',exact:true}).count(),1);const originalURL=await p.getByRole('link',{name:'查看原件',exact:true}).getAttribute('href');assert.equal((await p.request.get(new URL(originalURL,url).href)).status(),200);checks++;
  await p.locator('[data-goal-record]').click();await p.locator('#recordDialog[open]').waitFor();assert.match(await p.locator('#recordForm [name="note"]').inputValue(),/虚构反馈/);await p.locator('#recordDialog').evaluate(d=>d.close());checks++;
  const manual2=p.locator('[data-goal-form="manual"]');await manual2.locator('xpath=ancestor::details').evaluate(e=>e.open=true);await manual2.getByLabel('家长怎么带着做、怎么问孩子').fill('保留口头解释，缩为五分钟，先问孩子想从哪一道开始。');await manual2.getByRole('button',{name:'确认并更新原计划'}).click();await p.getByText('保留口头解释，缩为五分钟，先问孩子想从哪一道开始。',{exact:true}).first().waitFor();assert.equal(await p.locator('[data-goal-task]').getAttribute('data-goal-task'),original);checks++;
  await p.locator('[data-goal-action="evaluate"]').click();await p.locator('[data-goal-form="approve"]').waitFor();assert(await p.locator('[data-goal-next-step]').isVisible());
  if(process.env.GOALS_UI_PROOF_DIR){await fs.mkdir(process.env.GOALS_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.GOALS_UI_PROOF_DIR,'next-step-'+width+'.png'),fullPage:true})}await p.getByText('调整这份建议 · 可选',{exact:true}).click();await p.locator('[data-goal-form="approve"]').getByLabel('家长怎么带着做、怎么问孩子').fill('旧建议的修改不能混入新建议');await feedback.getByLabel('孩子怎么答的、用了什么帮助、用时和感受').fill('补充一条改变依据的反馈');await feedback.getByRole('button',{name:'保存反馈'}).click();await p.locator('[data-goal-form="approve"]').waitFor({state:'detached'});await p.locator('[data-goal-action="evaluate"]').click();await p.locator('[data-goal-form="approve"]').waitFor();assert.doesNotMatch(await p.locator('[data-goal-form="approve"]').getByLabel('家长怎么带着做、怎么问孩子').inputValue(),/旧建议的修改/);await p.getByText('为什么这样安排 · 判断与依据',{exact:true}).click();assert.match(await p.locator('[data-goal-proposal]').innerText(),/待验证/);await p.locator('[data-goal-form="approve"]').getByRole('button',{name:'确认并更新原计划'}).click();await p.locator('[data-goal-proposal]').getByText('没有新的待审核建议。',{exact:true}).waitFor();assert.equal(await p.locator('[data-goal-task]').getAttribute('data-goal-task'),original);checks++;
  await p.locator('[data-goal-action="pause"]').click();await p.getByText('已暂缓自动分析，反馈仍可保存。').waitFor();const pausedManual=p.locator('[data-goal-form="manual"]');await pausedManual.locator('xpath=ancestor::details').evaluate(e=>e.open=true);await pausedManual.getByLabel('家长怎么带着做、怎么问孩子').fill('暂缓期间只整理下次可能怎么做');await pausedManual.getByRole('button',{name:'确认并更新原计划'}).click();await p.getByText('已暂缓自动分析，反馈仍可保存。').waitFor();await p.locator('[data-goal-action="resume"]').click();await p.locator('[data-goal-action="pause"]').waitFor();checks++;
  await p.locator('[data-word-check] summary').click();const wordForm=p.locator('[data-goal-form="word"]');await wordForm.getByLabel('本次单词',{exact:true}).fill('pen');await wordForm.getByLabel('本次中文义或语境',{exact:true}).fill('用于写字的笔');await wordForm.getByLabel('本次条件',{exact:true}).selectOption({label:'首次核对'});await wordForm.locator('[name="word_result_hear_meaning"]').selectOption({label:'答错'});await wordForm.locator('[name="word_result_read_meaning"]').selectOption({label:'本次独立答对'});await wordForm.getByLabel('原始作答、选项、用时和感受 · 可选',{exact:true}).fill('虚构核对：只听选择书，看到词形选择笔。');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(process.env.GOALS_UI_PROOF_DIR)await p.screenshot({path:path.join(process.env.GOALS_UI_PROOF_DIR,'word-check-'+width+'.png'),fullPage:true});let wordLost=false;await p.route('**/api/goals/action',async route=>{const body=route.request().postDataJSON();if(body.word_check&&!wordLost){wordLost=true;await route.fetch();await route.abort('failed')}else await route.continue()});await wordForm.getByRole('button',{name:'保存本词核对'}).click();await p.getByText(/结果未确认，请点原按钮重试/).waitFor();assert(await p.locator('[data-goal-child-select="child-2"]').isDisabled());await p.locator('[data-goal-retry]').click();await p.unroute('**/api/goals/action');await p.getByText(/听英文 → 选中文：答错/).waitFor();const wordSnapshot=(await(await p.request.get(url+'api/goals')).json()).goals.find(g=>g.task_id===original);assert.equal(wordSnapshot.records.filter(r=>r.note.includes('【单词分项核对')).length,1);assert.match(wordSnapshot.records.at(-1).note,/看中文 → 说英文：未测/);assert.equal(wordSnapshot.task_id,original);checks++;
  const edit=p.locator('[data-goal-form="edit"]');await edit.getByLabel('目前实际表现').evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true});await edit.getByLabel('目前实际表现').fill('家长保留的修改内容');
  const live=await(await p.request.get(url+'api/goals')).json(),target=live.goals.find(g=>g.task_id===original),auth=await(await p.request.get(url+'api/state')).json();const other=await p.request.post(url+'api/goals/action',{headers:{'X-Family-Token':auth.token},data:{action:'edit',id:target.id,expected_version:target.version,request_key:'synthetic-other-parent-'+width,curriculum:'另一位家长刚核对的教材'}});assert.equal(other.status(),200);
  await edit.getByRole('button',{name:'保存背景更正'}).click();await edit.locator('[data-goal-rebase]').waitFor();assert.equal(await edit.getByLabel('目前实际表现').inputValue(),'家长保留的修改内容');await edit.locator('[data-goal-rebase]').click();assert.equal(await edit.getByLabel('年级与教材版本').inputValue(),'另一位家长刚核对的教材');await edit.getByRole('button',{name:'保存背景更正'}).click();await edit.locator('[data-goal-rebase]').waitFor({state:'detached'});checks++;
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal overflow');assert.deepEqual(errors,[]);
  await p.locator('[data-goal-child-select="child-2"]').click();const autoGoal=(await(await p.request.get(url+'api/goals')).json()).goals.find(g=>g.school_messages?.length);assert(autoGoal);const autoSelect=p.locator(`[data-goal-select="${autoGoal.id}"]`);if(await autoSelect.count())await autoSelect.click();await p.getByRole('heading',{name:autoGoal.title,exact:true}).waitFor();await p.locator('#goal-school-requirement summary').click();assert(await p.getByText('Agent从群消息自动关联 · 适用性待核对',{exact:true}).isVisible());assert.match(await p.locator('#goal-school-requirement').innerText(),/任选一种顺序介绍文具/);await p.getByRole('button',{name:'查看原消息与原件',exact:true}).click();await p.locator('#schoolOriginalDialog[open] blockquote').waitFor();assert.match(await p.locator('#schoolOriginalDialog').innerText(),/虚构发布者/);await p.locator('[data-school-original-close]').click();checks++;
  const schoolItem=autoGoal.school_messages[0].item_id;await p.locator('nav [data-page="more"]').click();await p.locator('[data-page="agent"]').click();for(const attr of ['data-agent-accept','data-school-record-agent','data-agent-dismiss'])assert(await p.locator(`[${attr}="${schoolItem}"]`).isVisible());await p.locator(`[data-agent-accept="${schoolItem}"]`).click();await p.locator('#agentDialog[open]').waitFor();await p.locator('[data-close="agentDialog"]').click();await p.locator(`[data-goal-id="${autoGoal.id}"]`).first().click();await p.getByRole('heading',{name:autoGoal.title,exact:true}).waitFor();checks++;
  if(process.env.GOALS_UI_PROOF_DIR){await fs.mkdir(process.env.GOALS_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.GOALS_UI_PROOF_DIR,'goals-'+width+'.png'),fullPage:true})}
  await p.locator('[data-goal-child-select="child-2"]').click();assert.equal(await p.locator('[data-goal-task]').count(),0);checks++;
  await p.close();
 }
 console.log(JSON.stringify({passed:true,checks,viewports:[360,1440],synthetic_only:true}));
}finally{if(browser)await browser.close();if(server){server.kill('SIGINT');await Promise.race([once(server,'exit'),wait(2000)]);if(server.exitCode===null)server.kill('SIGKILL')}}})().catch(e=>{console.error(e);process.exitCode=1});
