// Synthetic demo only. Requires PLAYWRIGHT_MODULE / PLAYWRIGHT_CHANNEL as in test_startup_ui.cjs.
// Optional CARE_UI_PROOF_DIR saves synthetic screenshots and proof, never family records.
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const net=require('node:net');
const {setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(check,label,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await delay(40)}throw Error('Timed out: '+label)}
async function demoServer(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 const proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let failure;proc.on('error',e=>failure=e);proc.stdout.resume();proc.stderr.resume();
 const stop=async()=>{if(failure||proc.exitCode!==null||proc.signalCode!==null)return;const done=once(proc,'exit');proc.kill('SIGINT');await Promise.race([done,delay(2500)]);if(proc.exitCode===null&&proc.signalCode===null){proc.kill('SIGKILL');await done}};
 const url='http://127.0.0.1:'+port+'/';try{await eventually(async()=>{if(failure)throw failure;if(proc.exitCode!==null)throw Error('Synthetic demo exited');try{return(await fetch(url+'api/state')).ok}catch{return false}},'demo');return{url,stop}}catch(e){await stop();throw e}
}
async function checkWidth(p,width){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'page width '+width);assert.equal(await p.locator('dialog[open]').evaluateAll(ds=>ds.some(d=>d.scrollWidth>d.clientWidth)),false,'dialog width '+width)}
(async()=>{
 let browser;const checks=[],proofDir=process.env.CARE_UI_PROOF_DIR;
 try{
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  for(const width of [360,1440]){
   let server,p;
   try{
    server=await demoServer();const read=async()=>await(await fetch(server.url+'api/state')).json();let state=await read();const originalCount=state.records.length,suggestion=state.care.items[0];
    const post=async(route,body)=>{state=await read();const r=await fetch(server.url+route,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,200,result.error);return result};
    p=await browser.newPage({viewport:{width,height:1000}});const errors=[],bodies=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/care/feedback')bodies.push(r.postDataJSON())});
    await p.emulateMedia({reducedMotion:'reduce'});await p.goto(server.url);await eventually(async()=>await p.locator('#content').getAttribute('data-ready')==='true','home ready');
    const morePage=async page=>{await p.locator('nav [data-page="more"]').click();await p.locator('#content [data-page="'+page+'"]').click()};
    const carePage=async()=>{await morePage('care');await eventually(()=>p.locator('[data-care="'+suggestion.id+'"]').isVisible(),'care history')};
    const open=async()=>{await carePage();await p.locator('[data-care="'+suggestion.id+'"]').click();await eventually(()=>p.locator('#careChoiceFields').isVisible(),'care choices')};
    const choose=async value=>{await p.locator('#careChoiceFields input[value="'+value+'"]').check()};
    const submit=()=>p.locator('#recordForm [type="submit"]');
    const saved=async()=>{await eventually(()=>p.locator('#recordDialog').isHidden(),'saved dialog');await eventually(async()=>await p.locator('#recordForm').getAttribute('data-saving')===null,'save refresh finished')};
    await open();assert.equal(await p.locator('#careChoiceFields input:checked').inputValue(),'');await submit().click();assert.equal(bodies.length,0);assert.equal(await p.locator('#recordForm [name="note"]').evaluate(el=>el===document.activeElement),true);
    // Actual keyboard radio selection and Enter save; native select popups are not involved.
    await p.locator('#careChoiceFields input[value=""]').focus();await p.keyboard.press('ArrowDown');assert.equal(await p.locator('#careChoiceFields input:checked').inputValue(),'愿意试试');
    assert.equal(await p.locator('#recordAudio').isVisible(),true);assert.equal(await p.locator('#fileInput').isVisible(),true);await checkWidth(p,width);
    let releaseFirst,held=0;const firstGate=new Promise(resolve=>releaseFirst=resolve);await p.route('**/api/care/feedback',async route=>{held++;if(held===1)await firstGate;await route.continue()});await submit().focus();await p.keyboard.press('Enter');await eventually(()=>held===1,'held explicit choice');await p.keyboard.press('Enter');await delay(50);assert.equal(bodies.length,1,'busy save refuses duplicate POST');releaseFirst();await saved();await p.unroute('**/api/care/feedback');state=await read();assert.equal(state.care.items[0].review_status,'accepted');assert.equal(state.records.length,originalCount+1);assert.match(await p.locator('[data-query-target="care:'+suggestion.id+'"]').innerText(),/不代表已经尝试或完成/);
    checks.push(width+': keyboard explicit choice saves immediately without inventing completion');
    await open();await choose('改天回看');await submit().click();assert.equal(await p.locator('[name="care_review_on"]').evaluate(el=>el===document.activeElement),true);const future=new Date(Date.parse(state.today+'T12:00:00Z')+2*86400000).toISOString().slice(0,10);
    await p.locator('[name="care_review_on"]').fill(state.today);await submit().click();assert.equal(bodies.length,1,'today cannot defer');await p.locator('[name="care_review_on"]').fill(future);await p.locator('#recordForm [name="note"]').fill('虚构家长：改天一起回看。');
    if(proofDir){await fs.mkdir(proofDir,{recursive:true});await eventually(()=>p.locator('#toast').isHidden(),'toast gone before synthetic screenshot',5000);await p.screenshot({path:path.join(proofDir,'synthetic-care-form-'+width+'.png')})}
    let attempt=0;await p.route('**/api/care/feedback',async route=>{attempt++;if(attempt===1)return route.fulfill({status:400,json:{error:'虚构校验失败',not_saved:true,request_known:false}});if(attempt===2){await route.fetch();return route.abort('failed')}if(attempt===3)return route.fulfill({status:409,json:{error:'虚构当前来源待核对',not_saved:false,request_known:true}});if(attempt===4)return route.fulfill({status:200,json:{ok:true,record_id:999,replayed:true,record:{id:999,child:'错误归属'},care:null,care_error:''}});return route.continue()});
    await submit().click();await eventually(async()=>/虚构校验失败/.test(await p.locator('#recordError').innerText()),'definite failure');assert.equal(await p.locator('[name="care_review_on"]').inputValue(),future);assert.equal(await p.locator('[name="care_review_on"]').isEnabled(),true);
    await submit().click();await eventually(async()=>/保存结果尚未核对/.test(await p.locator('#recordError').innerText()),'lost response');assert.equal(await p.locator('[name="care_review_on"]').isDisabled(),true);assert.equal(await p.locator('#recordForm [name="note"]').inputValue(),'虚构家长：改天一起回看。');state=await read();assert.equal(state.care.items[0].review_status,'deferred');
    const delayed=state.records.find(r=>r.care_choice==='改天回看');assert.ok(delayed);const frozen=bodies.at(-1);
    const profile=state.children.find(c=>c.name===frozen.child);await post('api/profile',{child_id:profile.id,version:profile.version||0,name:'虚构新称呼 '+width,grade:profile.grade,classroom:profile.classroom,reason:'虚构另一设备更正称呼'});
    // A newer explicit choice must survive replay of the prior, response-lost request.
    await post('api/care/feedback',{...frozen,care_choice:'暂不考虑',care_review_on:'',note:'虚构家长的更新选择',request_key:'newer_choice_'+width});
    await submit().click();await eventually(async()=>/虚构当前来源待核对/.test(await p.locator('#recordError').innerText()),'known request remains unresolved');assert.equal(await p.locator('[name="care_review_on"]').isDisabled(),true);assert.deepEqual(bodies.at(-1),frozen);await submit().click();await eventually(async()=>/保存回执与本次反馈不一致/.test(await p.locator('#recordError').innerText()),'mismatched success receipt rejected');assert.equal(await p.locator('[name="care_review_on"]').isDisabled(),true);assert.deepEqual(bodies.at(-1),frozen);await submit().click();await saved();await p.unroute('**/api/care/feedback');assert.deepEqual(bodies.at(-1),frozen,'retry uses identical body and key');state=await read();assert.equal(state.care.items[0].review_status,'declined');assert.equal(state.records.filter(r=>r.care_choice==='改天回看').length,1);assert.match(await p.locator('#toast').innerText(),/已有更新选择/);assert.match(await p.locator('[data-query-target="care:'+suggestion.id+'"]').innerText(),/已停止推荐/);
    checks.push(width+': date validation, failed-input retention, unresolved/mismatched receipt guards, stable-child rename replay and newer-choice preservation');
    await morePage('growth');await p.locator('[data-record="'+delayed.id+'"]').first().click();assert.match(await p.locator('#careSavedChoice').innerText(),/改天回看/);assert.equal(await p.locator('#careChoiceFields').isHidden(),true);let edited;
    await p.route('**/api/record',async route=>{edited=route.request().postDataJSON();await route.continue()});await p.locator('#recordForm [name="note"]').fill('虚构更正：只是更正文句。');await submit().click();await saved();await p.unroute('**/api/record');assert.equal(Object.hasOwn(edited,'care_choice'),false);assert.equal(Object.hasOwn(edited,'care_review_on'),false);state=await read();assert.equal(state.care.items[0].review_status,'declined');assert.equal(state.records.find(r=>r.id===delayed.id).care_choice,'改天回看');
    await open();await p.locator('#fileInput').setInputFiles({name:'synthetic-observation.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic observation only.')});await eventually(()=>p.locator('#pendingUploads [data-detach]').isVisible(),'care original uploaded');assert.equal(await p.locator('#recordForm [name="note"]').getAttribute('required'),null);await p.route('**/api/care/feedback',async route=>{const response=await route.fetch(),receipt=await response.json();await route.fulfill({response,json:{...receipt,care:null,care_error:'虚构当前安排暂时无法读取'}})});await submit().click();await saved();await p.unroute('**/api/care/feedback');assert.match(await p.locator('#toast').innerText(),/当前安排待核对/);state=await read();assert.equal(state.care.items[0].review_status,'declined');assert.ok(state.records.some(r=>r.source==='陪伴建议:'+suggestion.id&&!r.care_choice&&r.attachments.length===1));
    await p.locator('#add').click();assert.equal(await p.locator('#careChoiceFields').isHidden(),true);assert.equal(await p.locator('#recordForm [name="source"]').inputValue(),'家长观察');assert.equal(await p.locator('#recordForm [name="care_review_on"]').inputValue(),'');assert.equal(await p.locator('#recordForm [name="note"]').getAttribute('required'),null);assert.equal(await p.locator('#careSavedChoice').isHidden(),true);await p.locator('#recordForm [name="title"]').fill('虚构普通记录 '+width);await submit().click();await saved();state=await read();assert.equal(state.records.find(r=>r.title==='虚构普通记录 '+width).source,'家长观察');
    checks.push(width+': old feedback edits retain choice; attachment-only feedback retains stop; ordinary form clears source and care fields');
    const agreement=await post('api/reading/create',{request_key:'reading_fixture_'+width,child_id:state.children[0].id,book:'虚构阅读任务',edition:'',scope:'第一段',method:'讲讲发现',criteria:'分享一个细节',stamps:1,planned_on:''});state=await read();const reading=state.reading.tasks.find(r=>r.book==='虚构阅读任务');assert.ok(agreement&&reading);await post('api/reading/start',{request_key:'reading_start_'+width,id:reading.id,child_id:reading.child_id,version:reading.version,note:'虚构约定：已经商量好'});
    await p.locator('#refresh').click();await eventually(async()=>await p.locator('#toast').innerText()==='已读取最新保存结果','refresh fixture');await morePage('reading');await p.locator('[data-reading-work="'+reading.id+'"]').click();assert.equal(await p.locator('#careChoiceFields').isHidden(),true);assert.equal(await p.locator('#careSavedChoice').isHidden(),true);assert.equal(await p.locator('#recordForm [name="note"]').getAttribute('required'),null);await p.keyboard.press('Escape');
    // Broken schedule metadata must not revive a suggestion as a confirmed current action.
    let broken={...await read()};broken.care={...broken.care,error:'虚构安排文件无法读取',items:broken.care.items.map(c=>({...c,review_status:''}))};await p.route('**/api/state',r=>r.fulfill({json:broken}));await p.locator('nav [data-page="home"]').click();await p.locator('#refresh').click();await eventually(async()=>await p.locator('#toast').innerText()==='已读取最新保存结果','refresh broken care fixture');assert.equal(await p.locator('[data-care]').count(),0);await morePage('care');await eventually(async()=>/虚构安排文件/.test(await p.locator('#content').innerText()),'care read error');assert.match(await p.locator('[data-query-target="care:'+suggestion.id+'"]').innerText(),/当前安排待核对/);await p.unroute('**/api/state');await checkWidth(p,width);assert.deepEqual(errors,[]);
    checks.push(width+': reading reuse is clean; unknown care state stays historical; no errors or overflow');
   }finally{await p?.close();await server?.stop()}
  }
  const proof={checkedAt:new Date().toISOString(),passed:checks.length,checks,syntheticOnly:true,realPhoneTested:false};if(proofDir)await fs.writeFile(path.join(proofDir,'ui-proof.json'),JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify(proof,null,2));
 }finally{await browser?.close()}
})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
