// Disposable synthetic family only: one saved answer photo -> explicit AI draft -> reviewed feedback.
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const net=require('node:net');
const {setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(fn,label){for(let n=0;n<250;n++){if(await fn())return;await delay(40)}throw Error('Timed out: '+label)}
async function server(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 const proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:'ignore'}),url='http://127.0.0.1:'+port+'/';
 await eventually(async()=>{try{return(await fetch(url,{signal:AbortSignal.timeout(400)})).ok}catch{return false}},'demo startup');
 return {url,stop:async()=>{if(proc.exitCode!==null)return;const done=once(proc,'exit');proc.kill('SIGINT');await Promise.race([done,delay(2000)]);if(proc.exitCode===null){proc.kill('SIGKILL');await done}}};
}
(async()=>{let host,browser;try{
 host=await server();browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWF8AAAAASUVORK5CYII=','base64');
 for(const width of [360,1440]){
  let state=await(await fetch(host.url+'api/state')).json();const child=state.children[0].name,title='虚构作业核对 '+width;
  const p=await browser.newPage({viewport:{width,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.route('**/api/state',async route=>{const response=await route.fetch(),value=await response.json();value.printing={...value.printing,printers:[{name:'Synthetic_Printer',label:'虚构打印机',color:false,duplex:false}]};await route.fulfill({response,json:value})});
  await p.goto(host.url);
  await p.locator('[data-homework-new]').first().click();const entry=p.locator('#homeworkInputDialog');await entry.waitFor();assert.match(await entry.innerText(),/记作业/);
  const item=entry.locator('[data-homework-item="0"]');assert.equal(await item.locator('[name=title]').isVisible(),true,'parent can enter one homework directly');assert.equal(await entry.locator('[data-homework-original]').evaluate(x=>x.open),false,'source capture stays optional');await entry.locator('[data-homework-original] > summary').click();await entry.locator('[name=text]').fill('虚构老师原话：核对一页阅读题');
  if(process.env.HOMEWORK_QUICK_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.HOMEWORK_QUICK_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.HOMEWORK_QUICK_PROOF_DIR,'quick-entry-'+width+'.png')})}
  let draftCalls=0;await p.route('**/api/study/draft',r=>{draftCalls++;return r.fulfill({status:503,json:{error:'虚构模型不可用'}})});
  await item.locator('[name=title]').fill(title);await entry.locator('[data-homework-close]').click();await p.locator('[data-homework-new]').first().click();assert.equal(await item.locator('[name=title]').inputValue(),title,'quick entry survives closing and reopening');await item.locator('[name=goal]').fill('先作答再核对');assert.equal(await item.locator('[name=reviewed]').count(),0,'parent save is the explicit confirmation without a duplicate checkbox');await item.locator('[type=submit]').click();await entry.locator('.homework-saved').waitFor();assert.equal(draftCalls,0,'manual entry does not require the model');await p.unroute('**/api/study/draft');await entry.locator('[data-homework-manual]').click();assert.equal(await entry.locator('[data-homework-item]').count(),1,'unused empty candidate is visible');await entry.locator('[data-homework-close]').click();await p.locator('[data-homework-new]').first().click();assert.equal(await entry.locator('.homework-saved').count(),0,'a later capture starts a new session');assert.equal(await entry.locator('[data-homework-item="0"] [name=title]').isVisible(),true);assert.equal(await entry.locator('[name=text]').inputValue(),'','a new task does not inherit the previous original');assert.equal(await entry.locator('[data-homework-original]').evaluate(x=>x.open),false);await entry.locator('[data-homework-close]').click();
  state=await(await fetch(host.url+'api/state')).json();const id=state.tasks.find(t=>t.title===title)?.id;assert(id,'homework entry creates the task');await p.locator('[data-query-target="task:'+id+'"]').waitFor();
  assert.match(await p.locator('[data-query-target="task:'+id+'"] [data-task="'+id+'"]:visible').first().innerText(),/提交作业反馈/);
  await p.locator('[data-task="'+id+'"]').first().click();await p.locator('#taskDialog[open]').waitFor();
  assert.equal(await p.locator('#taskStatusDetails').evaluate(x=>x.open),false,'status update stays secondary');
  await p.locator('#taskForm [name=note]').fill('虚构未保存反馈');
  p.once('dialog',d=>d.dismiss());await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'close dismissal keeps unsaved feedback');
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'虚构未保存反馈');
  await p.locator('#taskForm [name=note]').fill('');
  await p.locator('#cameraInput').setInputFiles({name:'synthetic-answer.png',mimeType:'image/png',buffer:png});await p.locator('#pendingUploads img').waitFor();
  p.once('dialog',d=>d.dismiss());await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'close dismissal keeps unsaved photo');
  assert.equal(await p.locator('#pendingUploads img').count(),1);
  await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'photo feedback saved');
  assert.match(await p.locator('[data-query-target="task:'+id+'"] [data-task="'+id+'"]:visible').first().innerText(),/查看\/补充反馈/,'today confirms saved feedback in the same task');
  assert(await p.locator('[data-query-target="task:'+id+'"] [data-homework-print]').isVisible(),'separate question/reference printing is directly visible');
  const preparation={id:'b'.repeat(32),pdf_sha256:'c'.repeat(64),page_count:1,preview_url:'/api/print/preview/'+'b'.repeat(32)},keysPrint=[];
  await p.route('**/api/print/prepare',r=>r.fulfill({json:{preparation}}));
  await p.route('**/api/print/enqueue',r=>{keysPrint.push(r.request().postDataJSON().idempotency_key);return keysPrint.length===1?r.fulfill({status:503,json:{error:'虚构打印回执丢失'}}):r.fulfill({json:{job:{id:'d'.repeat(32),status:'queued'}}})});
  const printButton=p.locator('#taskFeedbackHistory [data-print-upload]').first();
  await p.locator('#taskForm [name=note]').fill('打印时保留的未保存反馈');
  await printButton.click();await eventually(async()=>await printButton.isEnabled(),'print failure releases button');assert.equal(keysPrint.length,1);
  await printButton.click();await eventually(async()=>/已提交打印/.test(await printButton.innerText()),'one original print retry acknowledged');
  assert.equal(keysPrint[0],keysPrint[1],'print retry keeps its request number');assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'打印时保留的未保存反馈');
  await printButton.click();assert.equal(keysPrint.length,2,'repeated click does not enqueue twice');
  await p.unroute('**/api/print/prepare');await p.unroute('**/api/print/enqueue');await p.locator('#taskForm [name=note]').fill('');

  const wrong=p.locator('#taskFeedbackHistory [data-task-wrong-form]').first();await wrong.locator(':scope > summary').click();
  await wrong.locator('[data-wrong-field="label"]').fill('第2题');await wrong.locator('[data-wrong-field="answer"]').fill('C');await wrong.locator('[data-wrong-field="correction"]').fill('B');
  p.once('dialog',d=>d.dismiss());await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'unsaved wrong answer stays with homework');
  let wrongCalls=0;await p.route('**/api/wrong/save',r=>{wrongCalls++;return wrongCalls===1?r.fulfill({status:503,json:{error:'虚构保存失败'}}):r.continue()});
  await wrong.locator('[data-task-wrong-save]').click();await eventually(async()=>/结果尚未核对/.test(await wrong.innerText()),'unknown wrong-item result retained');
  assert.equal(await wrong.locator('[data-wrong-field="answer"]').inputValue(),'C');
  await wrong.locator('[data-task-wrong-save]').click();await eventually(async()=>/错题已保存在这份作业下/.test(await p.locator('#taskFeedbackStatus').innerText()),'wrong-item retry saved');await p.unroute('**/api/wrong/save');
  state=await(await fetch(host.url+'api/state')).json();const wrongRecords=state.records.filter(r=>r.source==='错题照片核对'&&r.linked_task_id===id);assert.equal(wrongRecords.length,1,'retry creates one wrong item');
  assert.equal(wrongRecords[0].related_record_id,state.records.find(r=>r.source==='事项:'+id).id,'wrong item points to the original answer');
  assert.equal(wrongRecords[0].attachments[0],state.records.find(r=>r.source==='事项:'+id).attachments[0],'saved photo is reused');
  assert.equal(state.tasks.find(t=>t.id===id).update,null,'recording a wrong answer does not complete homework');
  assert.equal(await p.locator('#taskFeedbackHistory [data-homework-review]').count(),1,'wrong-item record does not start a second AI review');
  await p.keyboard.press('Escape');await p.locator('[data-task="'+id+'"]').first().click();await p.locator('#taskFeedbackHistory').getByText('作业错题', {exact:false}).first().waitFor();
  const wrongCard=p.locator('#taskFeedbackHistory .task-feedback-record').filter({has:p.locator('[data-record="'+wrongRecords[0].id+'"]')});
  await p.locator('#taskForm [name=note]').fill('虚构未保存的新反馈');p.once('dialog',d=>d.dismiss());
  await wrongCard.locator('[data-followup]').click();assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'correction does not discard unsaved feedback');
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'虚构未保存的新反馈');await p.locator('#taskForm [name=note]').fill('');
  await wrongCard.locator('[data-followup]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),false,'correction opens from the original homework');
  const correctionForm=p.locator('#recordForm');assert.equal(await correctionForm.locator('[name=followup_kind]').inputValue(),'订正');
  await correctionForm.locator('[name=note]').fill('虚构：孩子独立订正后仍需换题核对');
  let discardPrompts=0;const keepDraft=d=>{discardPrompts++;d.dismiss()};p.on('dialog',keepDraft);
  await p.locator('#recordDialog [data-close="recordDialog"]').click();assert.equal(await p.locator('#recordDialog').evaluate(x=>x.open),true,'cancel keeps unsaved correction');
  await p.keyboard.press('Escape');assert.equal(await p.locator('#recordDialog').evaluate(x=>x.open),true,'Escape keeps unsaved correction');
  assert.equal(discardPrompts,2,'both exits ask before discarding correction');p.off('dialog',keepDraft);
  assert.equal(await correctionForm.locator('[name=note]').inputValue(),'虚构：孩子独立订正后仍需换题核对');
  assert(await p.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented}),'refresh protects unsaved correction');
  let releaseReceipt;const heldReceipt=new Promise(resolve=>releaseReceipt=resolve);
  const keys=[];await p.route('**/api/record',async route=>{const body=route.request().postDataJSON();keys.push(body.request_key);if(keys.length===1){await route.fetch();await heldReceipt;await route.fulfill({status:503,json:{error:'虚构回执丢失'}})}else await route.continue()});
  await correctionForm.locator('[type=submit]').click();await eventually(async()=>await correctionForm.getAttribute('data-saving')==='yes','correction save in flight');
  await p.locator('#recordDialog [data-close="recordDialog"]').click();assert.equal(await p.locator('#recordDialog').evaluate(x=>x.open),true,'unknown save result cannot be discarded');
  await p.keyboard.press('Escape');assert.equal(await p.locator('#recordDialog').evaluate(x=>x.open),true,'Escape cannot discard an in-flight correction');
  releaseReceipt();await eventually(async()=>/虚构回执丢失/.test(await p.locator('#recordError').innerText()),'correction receipt lost');
  await correctionForm.locator('[type=submit]').click();await eventually(async()=>!(await p.locator('#recordDialog').evaluate(x=>x.open)),'same correction retry saved');await p.unroute('**/api/record');
  assert.equal(keys.length,2);assert(keys[0]&&keys[0]===keys[1],'retry reuses one request key');
  state=await(await fetch(host.url+'api/state')).json();const corrected=state.records.filter(r=>r.related_record_id===wrongRecords[0].id&&r.followup_kind==='订正');
  assert.equal(corrected.length,1,'lost receipt does not duplicate correction');assert.equal(corrected[0].linked_task_id,id,'correction stays on original homework');
  assert.equal(state.tasks.find(t=>t.id===id).update,null,'correction does not complete homework');
  await p.locator('[data-task="'+id+'"]').first().click();await p.locator('#taskFeedbackHistory').getByText('孩子独立订正后仍需换题核对').waitFor();
  const panel=p.locator('#taskFeedbackHistory [data-homework-review]').first(),firstAnswerId=Number(await panel.getAttribute('data-homework-review'));await panel.locator(':scope > details > summary').click();assert.equal(await panel.locator(':scope > details').evaluate(x=>x.open),true,'saved photo exposes review');assert.equal(await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').count(),1);
  let calls=0;await p.route('**/api/print/homework/draft',r=>{calls++;const body=r.request().postDataJSON();assert.equal(body.question_sources.length,1);return calls===1?r.fulfill({status:503,json:{error:'虚构模型暂不可用'}}):r.fulfill({json:{draft:{text:'虚构第1题：卷面C，参考B；先找原文依据。',items:1,wrong_items:1,unknown_items:0,coverage:'仅此一页'},question_sha256:'a'.repeat(64)}})});
  assert.match(await p.locator('#taskTitle').innerText(),new RegExp(state.tasks.find(t=>t.id===id).child),'feedback keeps child context');assert.equal(await p.locator('#taskRequirement').innerText(),state.tasks.find(t=>t.id===id).action||'具体要求尚未填写');
  assert.ok((await p.locator('#taskFeedbackHistory h3').boundingBox()).y<(await p.locator('#taskFeedbackFormHeading').boundingBox()).y,'saved work appears before a new blank feedback');assert.equal(await p.locator('.task-saved-originals details').count(),0);assert.equal(await p.locator('.task-saved-originals').first().evaluate(x=>x.open),false,'large originals are available without burying check controls');
  assert.equal(calls,0,'opening saved feedback must not call model');await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').check();await panel.locator('[data-homework-review-run]').click();await eventually(async()=>/虚构模型暂不可用/.test(await panel.innerText()),'model failure retained');
  await panel.locator('[data-homework-review-run]').click();await panel.locator('[data-homework-review-result] textarea').waitFor();assert.equal(calls,2);
  await panel.locator('[data-homework-review-result] textarea').fill('家长核对：第1题卷面C，依据原文应选B。先自己定位关键词，再独立重答。');
  let rerunPrompted=false;const dismissRerun=d=>{rerunPrompted=true;d.dismiss()};p.on('dialog',dismissRerun);
  await panel.locator('[data-homework-review-run]').click();p.off('dialog',dismissRerun);
  assert.equal(rerunPrompted,true,'recheck asks before keeping an edited previous opinion');assert.equal(calls,2,'declined regeneration does not call model');
  assert.match(await panel.locator('[data-homework-review-result] textarea').inputValue(),/家长核对：第1题/);
  p.once('dialog',d=>d.accept());await panel.locator('[data-homework-review-run]').click();await eventually(async()=>calls===3&&await panel.locator('[data-homework-review-previous] textarea').count()===1,'explicit regeneration retains the previous opinion');
  await panel.locator('[data-homework-review-result] textarea').fill('家长核对：第1题卷面C，依据原文应选B。先自己定位关键词，再独立重答。');
  await panel.locator('[data-homework-review-apply]').click();assert.match(await panel.innerText(),/请对照原题核对/);
  await panel.locator('[data-homework-review-confirm]').check();await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').uncheck();
  await panel.locator('[data-homework-review-apply]').click();assert.match(await panel.innerText(),/所选资料、用途、页码或补充已变化/);
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'','changed photo selection cannot stage an old review');
  await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').check();
  let releaseUpload,uploadCalls=0;await p.route('**/api/upload',async route=>{if(++uploadCalls===1)return route.fulfill({status:503,json:{error:'虚构上传失败'}});await new Promise(resolve=>releaseUpload=resolve);await route.continue()});
  await panel.locator('[data-homework-review-apply]').click();await eventually(async()=>/虚构上传失败/.test(await panel.innerText()),'review text upload failure');
  assert.equal(await panel.locator('[data-homework-review-result] textarea').isEnabled(),true,'failed upload restores editable draft');
  assert.equal(await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').isEnabled(),true,'failed upload restores photo choice');
  const applying=panel.locator('[data-homework-review-apply]').click();await eventually(async()=>!!releaseUpload,'review text upload pending');
  assert.equal(await panel.locator('[data-homework-review-result] textarea').isDisabled(),true,'review text cannot change during upload');
  assert.equal(await panel.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').isDisabled(),true,'review photo selection cannot change during upload');
  await p.locator('#taskForm [name=note]').fill('虚构：上传期间补写的观察');
  releaseUpload();await applying;await p.unroute('**/api/upload');
  await eventually(async()=>/请点下方|反馈输入.*变化/.test(await panel.innerText()),'concurrent review upload settled');
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'虚构：上传期间补写的观察','upload completion keeps concurrent parent input');
  assert.match(await panel.innerText(),/反馈输入.*变化/);
  await p.locator('#taskForm [name=note]').fill('');
  await panel.locator('[data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await panel.innerText()),'review staged after explicit retry');
  assert.match(await p.locator('#taskForm [name=note]').inputValue(),/家长核对的作业批改参考/);
  p.once('dialog',d=>d.dismiss());await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'review draft stays after declining discard');
  await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'review feedback saved');
  state=await(await fetch(host.url+'api/state')).json();const records=state.records.filter(r=>r.source==='事项:'+id);assert.equal(records.length,2);assert.equal(state.tasks.find(t=>t.id===id).update,null,'grading must not complete homework');
  const photo=records.find(r=>r.id===firstAnswerId).attachments[0],review=records.find(r=>r.note.includes('批改参考'));assert(review.attachments.includes(photo));const report=review.attachments.find(a=>a!==photo);assert.equal(state.uploads.find(a=>a.id===report).mime,'text/plain; charset=utf-8');
  const secondAnswer=await fetch(host.url+'api/task/feedback',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify({task_id:id,child,day:state.today,request_key:'synthetic-second-answer-'+width,attachments:[photo],note:'虚构第二份独立作答'})});assert.equal(secondAnswer.status,200);const secondAnswerId=(await secondAnswer.json()).record_id;state=await(await fetch(host.url+'api/state')).json();records.push(state.records.find(r=>r.id===secondAnswerId));
  await p.keyboard.press('Escape');await p.reload();await p.locator('[data-task="'+id+'"]').first().click();assert.equal(await p.locator('#taskFeedbackHistory [data-feedback-kind=check] .task-record-files > summary').count(),0,'saved check originals are direct, without another disclosure');await p.locator('#taskFeedbackHistory [data-feedback-kind=check]').first().getByText('作业批改参考', {exact:false}).first().waitFor();
  const firstReview=p.locator('#taskFeedbackHistory [data-homework-review]').nth(0),otherReview=p.locator('#taskFeedbackHistory [data-homework-review]').nth(1);assert.equal(await p.locator('#taskFeedbackHistory [data-homework-review]').count(),2);
  await firstReview.locator(':scope > details').evaluate(x=>x.open=true);await firstReview.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first().check();await firstReview.locator('[data-homework-review-run]').click();await firstReview.locator('[data-homework-review-result] textarea').waitFor();await firstReview.locator('[data-homework-review-result] textarea').fill('');
  await otherReview.locator(':scope > details').evaluate(x=>x.open=true);await otherReview.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first().check();await otherReview.locator('[data-homework-review-run]').click();await otherReview.locator('[data-homework-review-result] textarea').waitFor();
  await otherReview.locator('[data-homework-review-result] textarea').fill('另一份尚未保存的批改意见');
  await p.locator('#taskForm [name=note]').fill('另一条独立反馈');
  let savePrompted=false;const dismissSave=d=>{savePrompted=true;d.dismiss()};p.on('dialog',dismissSave);
  await p.locator('#saveTaskFeedback').click();p.off('dialog',dismissSave);
  assert.equal(savePrompted,true,'saving another feedback asks before discarding a separate AI draft');
  assert.equal(await otherReview.locator('[data-homework-review-result] textarea').inputValue(),'另一份尚未保存的批改意见');
  state=await(await fetch(host.url+'api/state')).json();assert.equal(state.records.filter(r=>r.source==='事项:'+id).length,3,'declined save changes neither answer nor saved opinion');
  await p.locator('#taskForm [name=note]').fill('');
  p.once('dialog',d=>d.dismiss());await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'every feedback review draft requires discard confirmation');
  p.once('dialog',d=>d.dismiss());await p.locator('[data-task-feedback-edit]').first().click();
  assert.equal(await otherReview.locator('[data-homework-review-result] textarea').inputValue(),'另一份尚未保存的批改意见','switch dismissal keeps the other review draft');
  p.once('dialog',d=>d.accept());await p.locator('[data-task-feedback-edit]').first().click();
  await p.locator('#taskForm [name=note]').fill('另一条尚未保存的反馈更正');
  p.once('dialog',d=>d.dismiss());await p.locator('[data-task-feedback-edit]').last().click();
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'另一条尚未保存的反馈更正','switch dismissal keeps edited feedback');
  const switchedId=Number(await p.locator('[data-task-feedback-edit]').last().getAttribute('data-task-feedback-edit'));
  p.once('dialog',d=>d.accept());await p.locator('[data-task-feedback-edit]').last().click();
  assert.equal(await p.locator('#taskForm [name=note]').inputValue(),records.find(r=>r.id===switchedId).note,'explicit discard switches to another saved feedback');
  await p.locator('#taskDialog [data-close="taskDialog"]').click();
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),false,'unchanged feedback closes without warning');
  await p.locator('[data-task="'+id+'"]').first().click();await p.locator('[data-task-feedback-edit]').first().click();
  await p.locator('#taskForm [name=note]').fill('虚构更正但未保存');
  p.once('dialog',d=>d.dismiss());await p.keyboard.press('Escape');
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),true,'Escape dismissal keeps edited feedback');
  p.once('dialog',d=>d.accept());await p.keyboard.press('Escape');
  assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),false,'explicit discard closes');
  await p.locator('[data-task="'+id+'"]').first().click();
  const finalReview=p.locator('#taskFeedbackHistory [data-homework-review]').first();await finalReview.locator(':scope > details').evaluate(x=>x.open=true);
  await finalReview.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first().check();await finalReview.locator('[data-homework-review-run]').click();
  await finalReview.locator('[data-homework-review-result] textarea').waitFor();
  await finalReview.locator('[data-homework-review-result] textarea').fill('家长尚未采纳的独立批改草稿');
  await p.locator('#taskForm [name=note]').fill('虚构另一条实际反馈');
  let acceptedPrompt=false;p.once('dialog',d=>{acceptedPrompt=true;d.accept()});await p.locator('#saveTaskFeedback').click();
  assert.equal(acceptedPrompt,true,'explicit approval allows saving separate feedback');
  await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'separate feedback saved');
  state=await(await fetch(host.url+'api/state')).json();assert.equal(state.records.filter(r=>r.source==='事项:'+id).length,4);
  assert.equal(await finalReview.locator('[data-homework-review-result] textarea').inputValue(),'家长尚未采纳的独立批改草稿','saving separate feedback retains the current unsaved answer review draft');
  assert.equal(state.records.find(r=>r.note==='虚构另一条实际反馈')?.child,child);assert.equal(state.tasks.find(t=>t.id===id).update,null);
  const source=state.records.find(r=>r.id===firstAnswerId);await p.locator('#taskFeedbackHistory [data-homework-review="'+source.id+'"] > details').evaluate(x=>x.open=true);
  const stale=p.locator('#taskFeedbackHistory [data-homework-review="'+source.id+'"]');await stale.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first().check();if(await stale.locator('[data-homework-review-result] textarea:not(:disabled)').count()&&await stale.locator('[data-homework-review-result] textarea').inputValue())p.once('dialog',d=>d.accept());await stale.locator('[data-homework-review-run]').click();await stale.locator('[data-homework-review-result] textarea').waitFor();await stale.locator('[data-homework-review-confirm]').check();await stale.locator('[data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await stale.innerText()),'review staged before concurrent correction');
  const correction=await fetch(host.url+'api/task/feedback',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify({task_id:id,child,record_id:source.id,expected_created:source.created,note:'虚构最终作答后来更正'})});assert.equal(correction.status,200);
  p.once('dialog',d=>d.accept());await p.locator('#saveTaskFeedback').click();await eventually(async()=>/原作答已在别处更正/.test(await p.locator('#taskError').innerText()),'stale review rejected');
  state=await(await fetch(host.url+'api/state')).json();assert.equal(state.records.filter(r=>r.source==='事项:'+id).length,4,'rejected review leaves no new record');
  p.once('dialog',d=>d.accept());await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.reload();await p.locator('[data-task="'+id+'"]').first().click();
  const fresh=p.locator('#taskFeedbackHistory [data-homework-review="'+source.id+'"]');await fresh.locator(':scope > details').evaluate(x=>x.open=true);await fresh.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first().check();await fresh.locator('[data-homework-review-run]').click();await fresh.locator('[data-homework-review-result] textarea').waitFor();await fresh.locator('[data-homework-review-confirm]').check();await fresh.locator('[data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await fresh.innerText()),'fresh review staged');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'fresh review saved');
  state=await(await fetch(host.url+'api/state')).json();assert.equal(state.records.filter(r=>r.source==='事项:'+id).length,5,'fresh review links to corrected answer');
  const textOnly=state.records.find(r=>r.note==='虚构另一条实际反馈'),textWrong=p.locator('#taskFeedbackHistory [data-task-wrong-form="'+textOnly.id+'"]');
  await textWrong.locator(':scope > summary').click();assert.equal(await textWrong.locator('[data-task-wrong-photo]').count(),0,'written feedback does not require a photo');
  await textWrong.locator('[data-wrong-field="label"]').fill('第3个词');await textWrong.locator('[data-wrong-field="answer"]').fill('窗处');await textWrong.locator('[data-wrong-field="correction"]').fill('窗外');
  const otherWrong=p.locator('#taskFeedbackHistory [data-task-wrong-form="'+source.id+'"]');await otherWrong.locator(':scope > summary').click();await otherWrong.locator('[data-wrong-field="label"]').fill('另一份未保存草稿');
  await textWrong.locator('[data-task-wrong-save]').click();assert.match(await textWrong.innerText(),/另一份作答还有未保存的错题/);
  await otherWrong.locator('[data-wrong-field="label"]').fill('');
  await textWrong.locator('[data-task-wrong-save]').click();await eventually(async()=>/错题已保存在这份作业下/.test(await p.locator('#taskFeedbackStatus').innerText()),'manual text-only wrong item saved');
  state=await(await fetch(host.url+'api/state')).json();assert.equal(state.records.filter(r=>r.source==='错题照片核对'&&r.linked_task_id===id).length,2);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('#taskDialog').evaluate(x=>x.scrollWidth>x.clientWidth),false);await p.reload();
  assert.match(await p.locator('[data-query-target="task:'+id+'"] [data-task="'+id+'"]:visible').first().innerText(),/查看\/补充反馈/,'reopened today retains saved-feedback state');assert.deepEqual(errors,[]);
  await p.unroute('**/api/print/homework/draft');
  const photos=[];for(let n=0;n<5;n++){const r=await fetch(host.url+'api/upload',{method:'POST',headers:{'X-Family-Token':state.token,'X-File-Name':'synthetic-complete-'+n+'.png','Content-Type':'application/octet-stream'},body:png});assert.equal(r.status,200);photos.push((await r.json()).attachment.id)}
  const pdf=Buffer.from(await(await fetch(host.url+'attachment/'+encodeURIComponent('演示练习.pdf'))).arrayBuffer());
  const pdfUpload=await fetch(host.url+'api/upload',{method:'POST',headers:{'X-Family-Token':state.token,'X-File-Name':'synthetic-teacher-reference.pdf','Content-Type':'application/octet-stream'},body:pdf});assert.equal(pdfUpload.status,200);const reference=(await pdfUpload.json()).attachment.id;
  const original=await fetch(host.url+'api/task/feedback',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify({task_id:id,child,day:state.today,request_key:'synthetic-complete-review-'+width,attachments:[...photos,reference],note:'虚构完整题目与独立作答'})});assert.equal(original.status,200);const originalRecord=(await original.json()).record_id;
  await p.reload();await p.locator('[data-task="'+id+'"]').first().click();
  const whole=p.locator('#taskFeedbackHistory [data-homework-review="'+originalRecord+'"]');await whole.locator(':scope > details > summary').click();
  assert.equal(await whole.locator(' :scope > details > .homework-review-material [data-homework-review-photo]').count(),6);assert.equal(await whole.locator('[data-homework-review-pages]').count(),1,'saved teacher PDF supports explicit page selection');
  for(const photo of photos)await whole.locator(' :scope > details > .homework-review-material [data-homework-review-photo][value="'+photo+'"]').check();
  // Display-contract reply only: the fixture PDF stays unselected, so this request did not read 11 pages.
  // Actual 11-page selection is checked in test_homework_review.py and the separate private UI audit.
  const partialCoverage='题目/孩子作答《虚构显示契约.pdf》：共11页，本次第1-7页；未读取页：8-11。';
  const completeReviewText='虚构：第1题表达不完整，缺少题目要求的具体特点；参考PDF未参与。\n实际读取范围（程序核对）：\n'+partialCoverage;
  let completeCalls=0;await p.route('**/api/print/homework/draft',r=>{const body=r.request().postDataJSON();assert.equal(body.purpose,'review');assert.deepEqual(body.question_sources.map(x=>x.id),photos);completeCalls++;return completeCalls===1?r.fulfill({status:503,json:{error:'虚构完整批改暂不可用'}}):r.fulfill({json:{draft:{text:completeReviewText,items:1,wrong_items:1,unknown_items:0,coverage:'五张所选照片；参考PDF未参与\n实际读取范围：'+partialCoverage,questions:[{label:'第1题',judgment:'incorrect',student_answer:'很好',answer:'写出具体特点',error_reason:'缺少题目要求的具体特点'}]},question_sha256:'b'.repeat(64)}})});
  await whole.locator('[data-homework-review-run]').click();await eventually(async()=>/虚构完整批改暂不可用/.test(await whole.innerText()),'five-image review failure keeps originals');
  assert.equal(await whole.locator(' :scope > details > .homework-review-material [data-homework-review-photo]:checked').count(),5);
  await whole.locator('[data-homework-review-run]').click();await whole.locator('[data-homework-review-result] textarea').waitFor({state:'attached'});assert.equal(completeCalls,2);
  const visibleCoverage=whole.locator('[data-homework-review-coverage]');assert.equal(await visibleCoverage.isVisible(),true);assert.ok((await visibleCoverage.innerText()).includes(partialCoverage),'known total, selected and unread PDF pages are visible without opening the full opinion');
  assert.equal(await whole.locator('[data-homework-review-result] textarea').evaluate(x=>x.closest('details').open),false,'structured questions keep the complete opinion collapsed');assert.equal(await whole.locator('[data-homework-review-result] textarea').isVisible(),false);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('#taskDialog').evaluate(x=>x.scrollWidth>x.clientWidth),false);
  if(process.env.HOMEWORK_QUICK_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await whole.locator('[data-homework-review-result]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(process.env.HOMEWORK_QUICK_PROOF_DIR,'complete-review-'+width+'.png')})}
  await whole.locator('[data-homework-review-confirm]').check();await whole.locator('[data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await whole.innerText()),'five-image review staged');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'five-image basis feedback saved');
  state=await(await fetch(host.url+'api/state')).json();const full=state.records.find(r=>r.note.includes('原作答反馈 #'+originalRecord+'。'));assert(full&&photos.every(x=>full.attachments.includes(x)));assert(!full.attachments.includes(reference),'unused teacher PDF is not claimed as grading basis');assert.equal(state.printing.jobs.length,0,'checking homework never prints');
  await p.reload();await p.locator('[data-task="'+id+'"]').first().click();await eventually(async()=>await p.locator('[data-saved-homework-review="'+full.id+'"] [data-saved-review-text]').innerText()===completeReviewText,'saved five-image opinion and partial range reopen as visible text');assert.equal(await p.locator('[data-saved-homework-review="'+full.id+'"] [data-saved-review-text]').isVisible(),true);assert.equal(await p.locator('#taskDialog').evaluate(x=>x.scrollWidth>x.clientWidth),false);assert.deepEqual(errors,[]);
  await p.unroute('**/api/print/homework/draft');
  // Reuse saved synthetic answers and their sibling PDF; no extra records affect the checks above.
  const delayedRecords=[source.id,secondAnswerId],sourcesPattern='**/api/print/homework/sources?**';
  for(const outcome of ['failure','success']){
   const sourceGates=new Map();let releaseDraft,releaseUpload,lateCalls=0,uploadPending=false;
   const draftGate=new Promise(resolve=>releaseDraft=resolve),uploadGate=new Promise(resolve=>releaseUpload=resolve);
   await p.route(sourcesPattern,async route=>{
    const recordId=Number(new URL(route.request().url()).searchParams.get('record_id'));
    if(!delayedRecords.includes(recordId))return route.continue();
    const response=await route.fetch(),value=await response.json();
    assert(value.sources.some(a=>a.id===reference),'both saved answers can reuse the sibling teacher PDF');
    await new Promise(resolve=>sourceGates.set(recordId,resolve));await route.fulfill({response,json:value});
   });
   await p.route('**/api/print/homework/draft',async route=>{
    const body=route.request().postDataJSON();assert.equal(body.record_id,source.id);assert.equal(body.question_sources.length,1);assert.deepEqual(body.reference_sources,[]);lateCalls++;
    await draftGate;
    return outcome==='failure'?route.fulfill({status:503,json:{error:'虚构迟到资料检查失败'}}):route.fulfill({json:{draft:{text:'虚构迟到资料检查成功；本次仅核对原作答。',items:1,wrong_items:0,unknown_items:1,coverage:'仅此一页'},question_sha256:'e'.repeat(64)}});
   });
   if(outcome==='success')await p.route('**/api/upload',async route=>{uploadPending=true;await uploadGate;await route.continue()});
   try{
    await p.reload();await p.locator('[data-task="'+id+'"]').first().click();
    const latePanels=delayedRecords.map(recordId=>p.locator('#taskFeedbackHistory [data-homework-review="'+recordId+'"]'));
    for(const latePanel of latePanels){await latePanel.locator(':scope > details').evaluate(x=>x.open=true);await latePanel.locator('[data-homework-review-sources]').evaluate(x=>x.parentElement.open=true)}
    await eventually(async()=>sourceGates.size===2,'both source responses held before generation');
    const originalChoice=latePanels[0].locator(' :scope > details > .homework-review-material [data-homework-review-photo]').first();
    await originalChoice.check();await latePanels[0].locator('[data-homework-review-run]').click();await eventually(async()=>lateCalls===1,'generation started before sources return');
    sourceGates.get(source.id)();if(outcome==='failure')sourceGates.get(secondAnswerId)();
    const returnedPanels=outcome==='failure'?latePanels:[latePanels[0]];
    for(const latePanel of returnedPanels)await latePanel.locator('[data-homework-review-sources] [data-review-source="'+reference+'"]').waitFor();
    assert.equal(await latePanels[0].locator('[data-homework-review-run]').isDisabled(),true,'source responses arrive while generation is still pending');
    releaseDraft();await eventually(async()=>await latePanels[0].locator('[data-homework-review-run]').isEnabled(),'generation releases busy controls after '+outcome);
    const reviewText=latePanels[0].locator('[data-homework-review-result] textarea');
    if(outcome==='failure'){assert.match(await latePanels[0].innerText(),/虚构迟到资料检查失败/);assert.equal(await reviewText.count(),0)}else{await reviewText.waitFor();await reviewText.fill('虚构：迟到资料恢复后仍保留已编辑批改草稿')}
    const checkEditable=async latePanel=>{
     const material=latePanel.locator('[data-homework-review-sources] [data-review-source="'+reference+'"]'),choice=material.locator('[data-homework-review-photo]'),role=material.locator('[data-homework-review-role]'),pages=material.locator('[data-homework-review-pages]');
     for(const control of [choice,role,pages])assert.equal(await control.isEnabled(),true,'late source controls restored after '+outcome);
     await choice.check();await material.locator('details').evaluate(x=>x.open=true);await role.selectOption('reference');await pages.fill('1');
     assert.equal(await choice.isChecked(),true);assert.equal(await role.inputValue(),'reference');assert.equal(await pages.inputValue(),'1');await choice.uncheck();
    };
    for(const latePanel of returnedPanels)await checkEditable(latePanel);
    if(outcome==='success'){
     await latePanels[0].locator('[data-homework-review-confirm]').check();await latePanels[0].locator('[data-homework-review-apply]').click();await eventually(async()=>uploadPending,'review text upload started before sibling sources return');
     sourceGates.get(secondAnswerId)();const siblingMaterial=latePanels[1].locator('[data-homework-review-sources] [data-review-source="'+reference+'"]');await siblingMaterial.waitFor();
     assert.equal(await siblingMaterial.locator('[data-homework-review-photo]').isDisabled(),true,'sibling source freezes during review text upload');
     releaseUpload();await eventually(async()=>/请点下方/.test(await latePanels[0].innerText()),'review text upload completed');await checkEditable(latePanels[1]);
    }
    assert.equal(await originalChoice.isChecked(),true,'late sources keep the selected original answer');
    if(outcome==='success'){assert.equal(await reviewText.inputValue(),'虚构：迟到资料恢复后仍保留已编辑批改草稿');p.once('dialog',d=>d.accept())}
    await p.locator('#taskDialog [data-close="taskDialog"]').click();assert.equal(await p.locator('#taskDialog').evaluate(x=>x.open),false);
   }finally{releaseDraft();releaseUpload();for(const release of sourceGates.values())release();await p.unroute(sourcesPattern);await p.unroute('**/api/print/homework/draft');if(outcome==='success')await p.unroute('**/api/upload')}
  }
  assert.deepEqual(errors,[]);await p.close();
 }
 console.log('Homework feedback AI review: 360/1440 save, retry, reopen, task status and source preserved');
}finally{try{if(browser){let closed=false;await Promise.race([browser.close().then(()=>closed=true),delay(5000)]);if(!closed)console.error('Synthetic browser cleanup timed out; server cleanup still runs')}}finally{await host?.stop()}}})().catch(e=>{console.error(e);process.exitCode=1});
