// Isolated synthetic family and model responses. Calendar writes use a disposable app.
const assert=require('node:assert/strict'),net=require('node:net');
const {spawn}=require('node:child_process'),{once}=require('node:events');
const {setTimeout:delay}=require('node:timers/promises'),{randomUUID}=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(check,label,timeout=12000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await delay(40)}throw Error('Timed out: '+label)}
async function server(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const key of Object.keys(env))if(key.startsWith('FAMILY_'))delete env[key];
 const proc=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['demo.py','--port',String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let error='';proc.stdout.resume();proc.stderr.on('data',x=>error+=String(x));proc.on('error',e=>error=e.message);
 const url='http://127.0.0.1:'+port+'/',stop=async()=>{if(proc.exitCode!==null||proc.signalCode!==null)return;const ended=once(proc,'exit');proc.kill('SIGINT');await Promise.race([ended,delay(2500)]);if(proc.exitCode===null&&proc.signalCode===null){proc.kill('SIGKILL');await ended}};
 try{await eventually(async()=>{if(proc.exitCode!==null)throw Error(error||'Demo exited');try{return(await fetch(url,{signal:AbortSignal.timeout(500)})).ok}catch{return false}},'demo ready');return{url,stop}}catch(e){await stop();throw e}
}
const add=(day,n)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
async function fit(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'page fits');assert.equal(await p.locator('dialog[open]').evaluateAll(xs=>xs.some(x=>x.scrollWidth>x.clientWidth)),false,'form fits');assert.equal(await p.locator('#askForm button:visible,#calendarForm button:visible,#askForm summary:visible,#calendarDraftDetails summary:visible').evaluateAll(xs=>xs.some(x=>x.getBoundingClientRect().height<44)),false,'44px controls')}
async function proof(p,name){if(process.env.CALENDAR_DRAFT_UI_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.CALENDAR_DRAFT_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.CALENDAR_DRAFT_UI_PROOF_DIR,name+'.png'),fullPage:false})}}
(async()=>{let browser;const results=[];try{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
 for(const width of [360,1440]){
  const service=await server(),p=await browser.newPage({viewport:{width,height:900}}),errors=[],asks=[],drafts=[],saves=[];let failDraft=false,dropSave=false,dropped=false;
  p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
  const read=async()=>await(await fetch(service.url+'api/state')).json(),post=async(path,body)=>{const state=await read(),response=await fetch(service.url+path,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify(body)}),data=await response.json();assert.equal(response.ok,true,JSON.stringify(data));return data};
  const home=()=>eventually(()=>p.locator('.today-dashboard').isVisible(),'home ready'),ask=async()=>{await p.locator('[data-page="ask"]').first().click();await eventually(()=>p.locator('#askForm').isVisible(),'ask page')},calendar=async()=>{await p.locator('[data-page="calendar"]').first().click();await eventually(()=>p.locator('[data-calendar-ask]').isVisible(),'calendar page')};
  const form=p.locator('#calendarForm'),input=p.locator('#askForm [name="question"]'),draft=()=>p.locator('#askCalendarDraft').click(),close=()=>p.locator('#calendarCancel').click(),save=()=>p.locator('#calendarSave').click();
  const opened=()=>eventually(()=>p.locator('#calendarDialog').isVisible(),'calendar form open'),saved=()=>eventually(async()=>!(await p.locator('#calendarDialog').isVisible()),'saved');
  try{
   const initial=await read(),first=initial.children[0],second=initial.children[1],monday=add(initial.today,-((new Date(initial.today+'T12:00:00Z').getUTCDay()+6)%7)),day=add(monday,12),tableID='synthetic-timetable';
   const base={id:randomUUID().replaceAll('-',''),version:0,child_ids:[first.id],title:'虚构周末自然观察',category:'activity',day,start_time:'15:00',end_time:'16:00',location:'示例公园',note:'带上观察本',status:'confirmed',repeat:'none',until:''};
   const firstEvent=(await post('api/calendar/save',base)).event;await post('api/calendar/save',{...base,id:randomUUID().replaceAll('-',''),child_ids:[second.id],title:'另一位孩子的虚构活动'});
   const events=async()=>await(await fetch(service.url+'api/calendar?start='+initial.today+'&end='+add(initial.today,30))).json();
   const baseline=(await events()).events.length;
   await p.route('**/api/calendar?*',async route=>{const response=await route.fetch(),body=await response.json();body.timetables.push({id:tableID,day,child_id:first.id,title:'虚构课表',sessions:[{slot:'第一节',title:'自然观察'}],note:'仅作隔离测试',source:'虚构班级课表',attachment:''});await route.fulfill({response,json:body})});
   await p.route('**/api/ask',async route=>{const body=route.request().postDataJSON();asks.push(body);await route.fulfill({json:{answer:'这位孩子下周六有自然观察；第一节为自然观察。',coverage:'仅这位孩子与所示日期范围的虚构资料',calendar_range:{start:body.start||day,end:body.end||add(day,1),defaulted:false},citations:[{id:'CAL01',kind:'calendar',target_id:firstEvent.id,child:first.name,title:firstEvent.title,day,detail:'15:00，带上观察本。'},{id:'TABLE01',kind:'timetable',target_id:tableID,child:first.name,title:'虚构课表',day,detail:'第一节：自然观察'}]}})});
   await p.route('**/api/calendar/draft',async route=>{
    const body=route.request().postDataJSON();drafts.push(body);if(failDraft){failDraft=false;await route.fulfill({status:503,json:{error:'虚构整理服务暂不可用'}});return}
    const uncertain=body.text.includes('不定哪天'),edit=body.text.includes('改期'),both=body.text.includes('两个孩子');
    await route.fulfill({json:{intent:edit?'edit':'create',reference_date:initial.today,needs_review:edit?['请先打开原安排，再修改日期。']:uncertain?['请明确参加的孩子。','请确认是周六还是周日。','尚未提供开始时间。','尚未提供结束时间。','请核对地点。','请确认活动内容。','日期仍需商量。','可以和孩子一起决定。','补充其他准备事项。']:['请核对地点和结束时间。'],draft:edit?null:{child_ids:uncertain?[]:both?(body.child_ids.length?body.child_ids:[first.id,second.id]):body.child_ids,title:uncertain?'虚构待商量活动':body.text,category:'activity',day:uncertain?'':day,start_time:uncertain?'':'15:00',end_time:'',location:'',note:'先和孩子商量',status:'tentative',repeat:'none',until:''}}});
   });
   await p.route('**/api/calendar/save',async route=>{saves.push(route.request().postDataJSON());if(dropSave&&!dropped){dropped=true;const response=await route.fetch();assert.equal(response.ok(),true);await route.abort('failed')}else await route.continue()});
   await p.goto(service.url);await home();await calendar();await p.locator('[data-calendar-ask]').click();assert.equal(await p.locator('#askForm [name="child"]').inputValue(),'','all-family entry does not silently choose first child');
   await input.fill('下周末有什么安排？');await p.locator('#askForm [type="submit"]').click();assert.equal(asks.length,0);assert.match(await p.locator('#askError').innerText(),/先选一位孩子/);
   await p.locator('#askForm [name="child"]').selectOption(first.name);await p.locator('#askForm [type="submit"]').click();await eventually(()=>p.locator('#askCalendarRange').isVisible(),'dated answer');assert.equal(asks[0].child,first.name);assert.equal(Object.hasOwn(asks[0],'start'),false);assert.equal(Object.hasOwn(asks[0],'end'),false);assert.match(await p.locator('#askCalendarRange').innerText(),new RegExp(day));assert.equal(await p.locator('.ask-answer').evaluate(x=>document.activeElement===x),true,'answer receives keyboard focus');assert.equal(await p.locator('.ask-answer h2').evaluate(x=>{const r=x.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}),true,'answer heading is in viewport after query');await fit(p);await proof(p,'query-'+width);
   await p.locator('.ask-answer .ask-citation').first().locator('summary').click();await p.locator('[data-ask-citation="0"]').click();await eventually(()=>p.locator('[data-query-target="calendar:'+firstEvent.id+':'+day+'"]').isVisible(),'calendar citation date');assert.equal(await p.locator('[data-calendar-child="'+first.id+'"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('[data-calendar-day="'+day+'"]').getAttribute('aria-pressed'),'true');assert.equal(await p.getByText('另一位孩子的虚构活动',{exact:true}).count(),0);
   await ask();await p.locator('.ask-answer .ask-citation').nth(1).locator('summary').click();await p.locator('[data-ask-citation="1"]').click();await eventually(async()=>await p.locator('[data-query-target="timetable:'+tableID+':'+day+'"]').getAttribute('open')!==null,'timetable citation opens exact day');
   await ask();await p.locator('#askForm details>summary').click();await p.clock.setFixedTime(new Date(add(initial.today,7)+'T04:00:00Z'));await p.locator('[data-ask-range="weekend"]').click();await fit(p);await input.fill('请核对这两天');await p.locator('#askForm [type="submit"]').click();await eventually(()=>asks.length===2,'explicit dates sent');assert.equal(asks[1].start,add(monday,12),'preset uses current Beijing date after week rollover');assert.equal(asks[1].end,add(monday,13));await p.clock.setFixedTime(new Date());await eventually(()=>p.locator('#askCalendarDraft').isEnabled(),'query complete');await p.locator('[data-ask-range="clear"]').click();
   await p.locator('#askForm [name="child"]').selectOption('');await p.locator('#askForm details>summary').click();await p.locator('#askForm [name="start"]').fill(day);await p.locator('#askForm [name="end"]').fill(add(day,-1));await input.fill('周六下午三点带两个孩子去虚构公园');await draft();await opened();assert.deepEqual(drafts.at(-1).child_ids,[],'group draft does not silently inherit first child');assert.equal(Object.hasOwn(drafts.at(-1),'start'),false,'query filters do not affect draft');assert.equal(saves.length,0);assert.equal((await events()).events.length,baseline,'draft did not write');assert.equal(await form.locator('[name="child_ids"]:checked').count(),2);assert.equal(await form.locator('[name="day"]').inputValue(),day);assert.match(await p.locator('#calendarEditNote').innerText(),/核对/);await form.locator('[name="title"]').fill('已商量：虚构公园观察');await form.locator('[name="end_time"]').fill('16:30');const draftID=await form.locator('[name="id"]').inputValue();await fit(p);await p.locator('#calendarDialog').evaluate(x=>x.scrollTop=0);await proof(p,'review-'+width);
   await close();assert.equal(await input.inputValue(),'周六下午三点带两个孩子去虚构公园');await p.locator('[data-ask-open-draft]').click();await opened();assert.equal(await form.locator('[name="title"]').inputValue(),'已商量：虚构公园观察');assert.equal(await form.locator('[name="id"]').inputValue(),draftID);await save();await saved();assert.equal(saves.length,1);assert.equal((await events()).events.filter(e=>e.id===draftID).length,1);assert.match(await p.locator('#askCalendarResult').innerText(),/已保存/);
   await p.locator('#askForm [name="child"]').selectOption('');await input.fill('不定哪天，也没说哪个孩子，安排一项活动');await draft();await opened();assert.deepEqual(drafts.at(-1).child_ids,[]);assert.equal(await form.locator('[name="child_ids"]:checked').count(),0);assert.equal(await form.locator('[name="day"]').inputValue(),'');assert.match(await p.locator('#calendarEditNote').innerText(),/待核对：孩子、日期/);assert.ok((await p.locator('#calendarEditNote').innerText()).length<100);assert.equal(await p.locator('#calendarDraftDetails').getAttribute('open'),null);assert.equal(await p.locator('#calendarDraftDetails li').count(),9,'full review retained behind disclosure');await p.locator('#calendarDialog').evaluate(x=>x.scrollTop=0);await fit(p);await proof(p,'ambiguous-'+width);await save();assert.equal(saves.length,1,'incomplete draft cannot save');await close();
   await input.fill('给孩子安排一个虚构活动');failDraft=true;await draft();await eventually(async()=>/虚构整理服务暂不可用/.test(await p.locator('#askError').innerText()),'draft failure displayed');assert.equal(await input.inputValue(),'给孩子安排一个虚构活动');assert.match(await p.locator('#askCalendarResult').textContent(),/不定哪天/,'previous draft retained');await input.fill('把原来的活动改期到周日');await draft();await eventually(async()=>/先核对你的意图/.test(await p.locator('#askCalendarResult').innerText()),'edit intent is not create');assert.equal(await p.locator('#calendarDialog').isVisible(),false);assert.equal(await p.locator('[data-ask-open-draft]').count(),0);assert.equal(saves.length,1);
   await p.locator('#askForm [name="child"]').selectOption(first.name);await input.fill('旧安排：周六三点虚构散步');await draft();await opened();dropSave=true;await save();await eventually(async()=>dropped&&(await p.locator('#calendarSave').isEnabled())&&/保留了/.test(await p.locator('#calendarRetryNote').innerText()),'lost save keeps old receipt');const old=saves.at(-1);await close();await input.fill('新草稿：周六四点虚构阅读');await draft();await eventually(async()=>/上一次保存结果还未核对/.test(await p.locator('#askError').innerText()),'new draft cannot masquerade as old pending');assert.equal(await p.locator('#calendarDialog').isVisible(),false);assert.match(await p.locator('#askCalendarResult').textContent(),/新草稿/);await p.locator('[data-calendar-resume]').click();await opened();assert.equal(await form.locator('[name="title"]').inputValue(),old.title);assert.equal(await form.locator('[name="id"]').inputValue(),old.id);await save();await saved();assert.deepEqual(saves.at(-1),old);assert.equal((await events()).events.filter(e=>e.id===old.id).length,1);await p.locator('[data-ask-open-draft]').click();await opened();assert.match(await form.locator('[name="title"]').inputValue(),/新草稿/);assert.notEqual(await form.locator('[name="id"]').inputValue(),old.id);await fit(p);await proof(p,'pending-separated-'+width);await close();
   // Real original upload and a synthetic transcription, without a microphone or live model.
   await p.route('**/api/state',async route=>{const response=await route.fetch(),body=await response.json();body.asr={...body.asr,configured:true};await route.fulfill({response,json:body})});
   await p.route('**/api/transcribe',route=>route.fulfill({json:{text:'周末带孩子去虚构公园'}}));
   await p.reload();await home();const beforeVoice=await read(),wav=Buffer.alloc(46);wav.write('RIFF');wav.writeUInt32LE(38,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(2,40);
   const uploadVoice=async()=>{await p.locator('#fileInput').setInputFiles({name:'synthetic-silence.wav',mimeType:'audio/wav',buffer:wav});await eventually(()=>p.locator('#transcribeButton').isEnabled(),'audio original uploaded');await p.locator('#transcribeButton').click();await eventually(()=>p.locator('#askTranscript').isEnabled(),'transcript can be used')};
   await p.locator('#add').click();await uploadVoice();await p.locator('#transcriptText').fill('周六三点去虚构图书馆');await p.locator('#askTranscript').click();assert.equal(await input.inputValue(),'周六三点去虚构图书馆');assert.equal(await p.locator('#askForm [name="child"]').inputValue(),'','default record child is not treated as explicit');assert.equal((await read()).records.length,beforeVoice.records.length);
   await p.locator('#add').click();await p.locator('#recordForm [name="child"]').selectOption(second.name);await uploadVoice();await p.locator('#transcriptText').fill('周日四点去虚构公园');await p.locator('#recordForm [name="title"]').fill('虚构尚未保存原稿');let heldRecord=null;await p.route('**/api/record',route=>{heldRecord=route});await p.locator('#recordForm [type="submit"]').click();await eventually(()=>!!heldRecord,'record save awaiting response');await p.locator('#askTranscript').click();assert.equal(await p.locator('#recordDialog').isVisible(),true,'bridge cannot close an in-flight original save');assert.match(await p.locator('#toast').innerText(),/保存结果尚未核对/);await heldRecord.fulfill({status:400,json:{error:'虚构校验拒绝，未保存'}});await eventually(async()=>await p.locator('#recordForm').getAttribute('data-saving')===null,'definitive save rejection');await p.locator('#askTranscript').click();assert.equal(await input.inputValue(),'周日四点去虚构公园');assert.equal(await p.locator('#askForm [name="child"]').inputValue(),second.name,'explicitly selected child is carried');assert.equal((await read()).records.length,beforeVoice.records.length,'transcript bridge does not save a growth record');assert.equal((await read()).uploads.length,beforeVoice.uploads.length+2,'audio originals remain stored');
   await p.locator('[data-page="home"]').first().click();await p.locator('[data-page="care"]').click();await p.locator('[data-care="'+beforeVoice.care.items[0].id+'"]').click();await uploadVoice();await p.route('**/api/care/feedback',route=>route.abort('failed'));await p.locator('#recordForm [type="submit"]').click();await eventually(async()=>/核对并重试/.test(await p.locator('#recordForm [type="submit"]').innerText()),'unknown care save preserved');assert.equal(await p.locator('#askTranscript').isDisabled(),true,'unknown saved result cannot be abandoned through transcript bridge');assert.equal(await p.locator('#recordDialog').isVisible(),true);assert.equal((await read()).records.length,beforeVoice.records.length);
   assert.deepEqual(errors,[]);results.push({width,voiceTranscriptBridge:true,voicePendingSavePreserved:true,explicitChildScope:true,optionalDateRange:true,answerVisibleAfterQuery:true,currentDatePreset:true,queryFiltersDoNotBlockDraft:true,compactReview:true,calendarAndTimetableCitations:true,draftNoWrite:true,missingFieldsStayEmpty:true,cancelRetainsEdits:true,modelFailureRetainsText:true,editIntentNotCreate:true,pendingSaveSeparate:true,retryIdempotent:true,pageErrors:0});
  }finally{await p.close();await service.stop()}
 }
 console.log(JSON.stringify({passed:results.length,results,syntheticOnly:true,modelResponsesStubbed:true,calendarPersistenceReal:true,phoneHardwareTested:false},null,2));
}finally{await browser?.close()}})().catch(e=>{console.error(e.stack||e.message);process.exitCode=1});
