// Disposable synthetic family; no household data, external model, collection or printer.
// Optional PLAYWRIGHT_MODULE, PLAYWRIGHT_CHANNEL, FAMILY_TEST_PYTHON, SCENARIOS_UI_PROOF_DIR.
const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events'),net=require('node:net');
const {setTimeout:delay}=require('node:timers/promises'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs/promises'),path=require('node:path');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEUlEQVR4nGOQs4n6D8IMMAYAN7wGzYgpkEMAAAAASUVORK5CYII=','base64');
async function eventually(check,label){const until=Date.now()+12000;while(Date.now()<until){if(await check())return;await delay(40)}throw Error('Timed out: '+label)}
async function server(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
 const env={...process.env};for(const key of Object.keys(env))if(key.startsWith('FAMILY_'))delete env[key];
 const launch=`import app,runpy,sys
review_count=0
def model(messages,*args,**kwargs):
    global review_count
    review_count+=1
    teacher=any('synthetic-teacher' in str(m.get('content','')) for m in messages)
    item=dict(label='第1题',question='虚构第1题：选择A、B或C',student_answer='C',answer='教师参考：B' if teacher else 'AI推导：C',judgment='incorrect' if teacher else 'correct',error_reason='与教师参考不同' if teacher else '',possible_cause='原因待孩子解释' if teacher else '',steps='先独立重答，再核对参考' if teacher else '',uncertainty='')
    note=next((x.get('text','') for m in messages if isinstance(m.get('content'),list) for x in m['content'] if x.get('type')=='text' and x.get('text','').startswith('原作答家长说明')), '')
    if '虚构甲卷' in note or '虚构乙卷' in note:
        paper='甲' if '虚构甲卷' in note else '乙'
        assert ('synthetic-teacher-'+paper+'.txt') in str(messages), 'matching teacher required'
        assert ('synthetic-teacher-'+('乙' if paper=='甲' else '甲')+'.txt') not in str(messages), 'other teacher must not mix'
        assert sum(x.get('type')=='image_url' for m in messages if isinstance(m.get('content'),list) for x in m['content'])==6, 'six selected answer pages'
        return dict(items=[item],coverage=paper+'卷第1题；第2、3题未检查，不能称整卷已核对',comparison='仅此卷教师参考，不影响另一卷')
    return dict(items=[item],coverage='虚构检查第%d轮；仅按明确题号比较，原题要求仍待核对'%review_count,comparison='补充老师参考后，第1题需订正；初检缺少老师依据。' if teacher else '初检尚无教师依据。')
app.family_llm._chat_json=model
sys.argv=['demo.py','--port',sys.argv[1]]
runpy.run_path('demo.py',run_name='__main__')`;
 const child=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['-c',launch,String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let error='';child.stdout.resume();child.stderr.on('data',b=>error+=b);
 const url='http://127.0.0.1:'+port+'/',stop=async()=>{if(child.exitCode!==null||child.signalCode!==null)return;const exited=once(child,'exit');child.kill('SIGINT');await Promise.race([exited,delay(2500)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await exited}};
 try{await eventually(async()=>{if(child.exitCode!==null)throw Error(error||'Demo exited');try{return(await fetch(url,{signal:AbortSignal.timeout(400)})).ok}catch{return false}},'synthetic server');return{url,stop}}catch(e){await stop();throw e}
}
async function ready(p){await p.locator('#task-group-homework').waitFor();await eventually(async()=>await p.locator('#content').getAttribute('data-ready')==='true','home ready')}
async function selectedChild(p,children,selected){assert.equal(await p.locator('[data-child-filter=""]').count(),0,'there is no all-children choice');assert.equal(await p.locator('.child-filters [data-child-filter]').count(),children.length);assert.deepEqual(await p.locator('.child-filters [aria-pressed="true"]').evaluateAll(xs=>xs.map(x=>x.dataset.childFilter)),[selected.id],'exactly the selected child is active')}
async function fit(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('dialog[open]').evaluateAll(xs=>xs.some(x=>x.scrollWidth>x.clientWidth)),false)}
async function proof(p,name){if(process.env.SCENARIOS_UI_PROOF_DIR){await fs.mkdir(process.env.SCENARIOS_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.SCENARIOS_UI_PROOF_DIR,name+'.png')})}}
async function multiplePapers(browser,host,base,width,checks){
 const p=await browser.newPage({viewport:{width,height:850}}),errors=[],read=async()=>await(await fetch(host.url+'api/state')).json();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 try{
  await p.goto(host.url);await ready(p);await p.locator('[data-homework-new="'+base.children[0].id+'"]').click();
  const entry=p.locator('#homeworkInputDialog');await entry.locator('[name=title]').fill('虚构两份同号试卷 '+width);await entry.locator('[data-homework-item] [type=submit]').click();await entry.locator('.homework-saved').waitFor();await entry.locator('[data-homework-close]').click();
  let state=await read();const task=state.tasks.find(t=>t.title==='虚构两份同号试卷 '+width),open=async()=>p.locator('[data-query-target="task:'+task.id+'"] [data-task]').click();await open();
  let uploads=0;await p.route('**/api/upload',r=>++uploads===4?r.fulfill({status:503,json:{error:'虚构第4张上传失败'}}):r.continue());
  await p.locator('#fileInput').setInputFiles(Array.from({length:12},(_,i)=>({name:(i<6?'甲':'乙')+'卷第'+(i%6+1)+'页.png',mimeType:'image/png',buffer:png})));
  await eventually(async()=>/虚构第4张上传失败/.test(await p.locator('#uploadStatus').innerText()),'one of twelve upload failed');assert.equal(await p.locator('[data-task-feedback-file]').count(),11);
  await p.locator('#saveTaskFeedback').click();assert.match(await p.locator('#taskError').innerText(),/未上传成功/);await p.locator('#retryUpload').click();await eventually(async()=>await p.locator('[data-task-feedback-file]').count()===12&&await p.locator('#saveTaskFeedback').isEnabled(),'all twelve original images uploaded and unlocked');await p.unroute('**/api/upload');
  const names=await p.locator('[data-task-feedback-file]').evaluateAll(xs=>xs.map(x=>({id:x.dataset.taskFeedbackFile,name:x.parentElement.textContent}))),idsA=names.filter(x=>x.name.includes('甲')).map(x=>x.id),idsB=names.filter(x=>x.name.includes('乙')).map(x=>x.id);assert.equal(idsA.length,6);assert.equal(idsB.length,6);
  for(const id of idsB)await p.locator('[data-task-feedback-file="'+id+'"]').uncheck();await p.locator('#saveTaskFeedback').click();assert.match(await p.locator('#taskError').innerText(),/卷的名称或范围/);
  await p.locator('#taskForm [name=note]').fill('虚构甲卷，第1—6页；题号1、2、3');const keys=[];let lost=true;
  await p.route('**/api/task/feedback',async r=>{keys.push(r.request().postDataJSON().request_key);if(lost){lost=false;await r.fetch();return r.fulfill({status:503,json:{error:'虚构甲卷保存回执丢失'}})}return r.continue()});
  await p.locator('#saveTaskFeedback').click();await eventually(async()=>/回执丢失/.test(await p.locator('#taskError').innerText()),'partial save reply lost');let releaseRefresh;await p.route('**/api/state',async r=>{await new Promise(resolve=>releaseRefresh=resolve);await r.continue()});await p.locator('#saveTaskFeedback').click();await eventually(async()=>!!releaseRefresh,'partial save succeeds while refresh waits');assert.equal(await p.locator('#saveTaskFeedback').isDisabled(),true,'acknowledged save stays locked until old inputs are replaced');assert.equal(await p.locator('#fileInput').isDisabled(),true,'no new upload may be overwritten by refresh');await p.locator('#saveTaskFeedback').evaluate(x=>x.click());assert.equal(keys.length,2,'waiting refresh cannot create a duplicate paper');releaseRefresh();await p.unroute('**/api/state');await eventually(async()=>/其余6份材料/.test(await p.locator('#taskFeedbackStatus').innerText()),'retry retains all six unsaved second-paper photos');await p.unroute('**/api/task/feedback');assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);
  assert.equal(await p.locator('[data-task-feedback-file]').count(),6);assert.deepEqual(await p.locator('[data-task-feedback-file]').evaluateAll(xs=>xs.map(x=>x.dataset.taskFeedbackFile)),idsB);
  await p.locator('#taskForm [name=note]').fill('虚构乙卷，第1—6页；题号1、2、3');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'second paper saved');state=await read();
  const answers=['甲','乙'].map(n=>state.records.find(r=>r.source==='事项:'+task.id&&r.note.startsWith('虚构'+n+'卷')));assert(answers.every(Boolean));assert.deepEqual(answers[0].attachments,idsA);assert.deepEqual(answers[1].attachments,idsB);assert.equal(state.records.filter(r=>r.source==='事项:'+task.id).length,2,'retry made no duplicate answer');
  const teacherIds=[];
  for(const n of ['甲','乙']){const wait=p.waitForResponse(r=>r.url().endsWith('/api/upload'));await p.locator('#fileInput').setInputFiles({name:'synthetic-teacher-'+n+'.txt',mimeType:'text/plain',buffer:Buffer.from(n+'卷，第1题B，第2题C，第3题A')});teacherIds.push((await(await wait).json()).attachment.id);await eventually(async()=>await p.locator('#saveTaskFeedback').isEnabled(),'teacher uploaded');await p.locator('#taskForm [name=note]').fill(n+'卷老师参考');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'teacher saved');}
  await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.reload();await ready(p);await open();
  const bodies=[];let failModel=true;await p.route('**/api/print/homework/draft',r=>{const b=r.request().postDataJSON();bodies.push(b);return failModel?(failModel=false,r.fulfill({status:503,json:{error:'虚构逐卷检查失败'}})):r.continue()});
  for(const [n,answer] of answers.entries()){
   let panel=p.locator('[data-homework-review="'+answer.id+'"]');await panel.locator(':scope > details').evaluate(x=>x.open=true);await eventually(async()=>await panel.locator('[data-review-source="'+teacherIds[n]+'"]').count()===1,'own teacher available');
   for(const id of answer.attachments)await panel.locator('[data-homework-review-photo][value="'+id+'"]').check();await panel.locator('details:has(> [data-homework-review-sources])').evaluate(x=>x.open=true);const teacher=panel.locator('[data-review-source="'+teacherIds[n]+'"]');await teacher.locator('[data-homework-review-photo]').check();
   const others=answers[1-n].attachments;assert.equal(await panel.locator('[data-review-source="'+teacherIds[1-n]+'"] [data-homework-review-photo]').isChecked(),false,'other paper teacher never auto-selected');
   if(n===0){for(const id of others)await panel.locator('[data-homework-review-photo][value="'+id+'"]').check();const calls=bodies.length;await panel.locator('[data-homework-review-run]').click();assert.equal(bodies.length,calls,'twelve pages cannot silently exceed a batch');assert.match(await panel.locator('[data-homework-review-status]').innerText(),/最多8页/);for(const id of others)await panel.locator('[data-homework-review-photo][value="'+id+'"]').uncheck();await panel.locator('[data-homework-review-run]').click();await eventually(async()=>/虚构逐卷检查失败/.test(await panel.innerText()),'first paper model retry');}
   const reply=p.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'));await panel.locator('[data-homework-review-run]').click();assert.equal((await reply).status(),200);await panel.locator('[data-homework-review-result] textarea').waitFor({state:'attached'});assert.deepEqual(bodies.at(-1).question_sources.map(x=>x.id),answer.attachments);assert.deepEqual(bodies.at(-1).reference_sources,[{type:'upload',id:teacherIds[n]}]);assert.equal(bodies.at(-1).record_id,answer.id);assert.match(await panel.locator('[data-homework-review-coverage]').innerText(),/本次检查范围[\s\S]*未检查部分/);await fit(p);await proof(p,'paper-'+n+'-'+width);
   await panel.locator('[data-homework-review-confirm]').check();await panel.locator('[data-homework-review-apply]').click();await eventually(async()=>/已填入待保存/.test(await panel.innerText()),'paper check staged');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'paper check saved');
   const wrong=p.locator('[data-task-wrong-form="'+answer.id+'"]');await wrong.locator(':scope > summary').click();await wrong.locator('[data-wrong-field="label"]').fill('第1题');await wrong.locator('[data-wrong-field="answer"]').fill('C');await wrong.locator('[data-wrong-field="correction"]').fill('B');await wrong.locator('[data-task-wrong-save]').click();await eventually(async()=>/错题已保存在这份作业下/.test(await p.locator('#taskFeedbackStatus').innerText()),'same numbered wrong item follows this original answer');
  }
  await p.unroute('**/api/print/homework/draft');state=await read();const wrongs=answers.map(a=>state.records.find(r=>r.source==='错题照片核对'&&r.related_record_id===a.id));assert(wrongs.every(Boolean));assert.notEqual(wrongs[0].id,wrongs[1].id);
  for(const [n,wrong] of wrongs.entries()){await p.locator('[data-followup="'+wrong.id+'"]').click();const form=p.locator('#recordForm');await form.locator('[name=note]').fill((n?'乙':'甲')+'卷第1题订正，仅此原答');await form.locator('[type=submit]').click();await eventually(async()=>!await p.locator('#recordDialog').evaluate(x=>x.open),'paper-specific correction saved');await open();}
  await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.reload();await ready(p);await open();state=await read();
  for(const [n,a] of answers.entries()){assert.equal(state.records.filter(r=>r.followup_kind==='作业检查'&&r.related_record_id===a.id).length,1);const correction=state.records.find(r=>r.followup_kind==='订正'&&r.related_record_id===wrongs[n].id);assert(correction);assert.equal(correction.linked_task_id,task.id);assert.equal(await p.locator('[data-homework-review="'+a.id+'"]').locator(':scope > details > .homework-review-material').count(),6);assert.match(await p.locator('#taskFeedbackHistory').innerText(),new RegExp((n?'乙':'甲')+'卷第1题订正'));assert.match(await p.locator('#taskFeedbackHistory .note').filter({has:p.locator('[data-record="'+correction.id+'"]')}).innerText(),new RegExp('来自作答：虚构'+(n?'乙':'甲')+'卷'));}assert.notEqual(state.tasks.find(t=>t.id===task.id).update?.status,'已完成');assert.deepEqual(errors,[]);await fit(p);await proof(p,'two-paper-reopen-'+width);
  checks.push({width,twelvePhotos:true,twoOriginalAnswers:true,perPaperTeacher:true,sameQuestionNumbersIsolated:true,partialReplyRetry:true,checkFailureRetry:true,coverageVisible:true,wrongAndCorrectionReopened:true,syntheticModel:true});
 }catch(e){await proof(p,'two-paper-failure-'+width);throw e}finally{await p.close()}
}
async function stagedRecheck(browser,host,base,width,checks){
 const p=await browser.newPage({viewport:{width,height:850}}),errors=[],read=async()=>await(await fetch(host.url+'api/state')).json();p.on('pageerror',e=>errors.push(e.message));let rejectNext=false;const dialogs=[];p.on('dialog',d=>{dialogs.push(d.message());if(rejectNext){rejectNext=false;d.dismiss()}else d.accept()});
 try{
  const owner=base.children[0],title='虚构已填入检查后继续复核 '+width;await p.goto(host.url);await ready(p);await p.locator('[data-homework-new="'+owner.id+'"]').click();const entry=p.locator('#homeworkInputDialog');await entry.locator('[name=title]').fill(title);await entry.locator('[data-homework-item] [type=submit]').click();await entry.locator('.homework-saved').waitFor();await entry.locator('[data-homework-close]').click();
  const task=(await read()).tasks.find(t=>t.title===title),open=async()=>p.locator('[data-query-target="task:'+task.id+'"] [data-task="'+task.id+'"]').click();assert.equal(task.child,owner.name);await open();await p.locator('#cameraInput').setInputFiles({name:'synthetic-staged-answer.png',mimeType:'image/png',buffer:png});await p.locator('#pendingUploads img').waitFor();await p.locator('#taskForm [name=note]').fill('虚构原作答，初检与复核都回这一份');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'staged-recheck answer saved');
  const answer=(await read()).records.find(r=>r.source==='事项:'+task.id),teacherUpload=p.waitForResponse(r=>r.url().endsWith('/api/upload'));await p.locator('#fileInput').setInputFiles({name:'synthetic-staged-teacher.txt',mimeType:'text/plain',buffer:Buffer.from('虚构教师参考：第1题B，必须核对是否漏答。')});const teacherResponse=await teacherUpload;assert.equal(teacherResponse.status(),200);const teacher=(await teacherResponse.json()).attachment;assert.ok(teacher?.id);await eventually(async()=>/synthetic-staged-teacher\.txt/.test(await p.locator('#pendingUploads').innerText()),'staged-recheck teacher uploaded');await p.locator('#taskForm [name=note]').fill('虚构后补老师参考');await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'staged-recheck teacher saved');
  const panel=p.locator('[data-homework-review="'+answer.id+'"]'),instruction=panel.locator('[data-homework-review-instruction]');await panel.locator(':scope > details').evaluate(x=>x.open=true);await panel.locator(':scope > details > .homework-review-material [data-homework-review-photo]').check();await panel.locator('details:has(> [data-homework-review-sources])').evaluate(x=>x.open=true);const teacherRow=panel.locator('[data-review-source="'+teacher.id+'"]');await teacherRow.waitFor();await teacherRow.locator('details').evaluate(x=>x.open=true);await teacherRow.locator('[data-homework-review-role]').selectOption('reference');await teacherRow.locator('[data-homework-review-photo]').check();await instruction.fill('虚构补充：请核对第1题是否漏答。');
  const reviewBodies=[];await p.route('**/api/print/homework/draft',r=>{reviewBodies.push(r.request().postDataJSON());return r.continue()});await panel.locator('[data-homework-review-run]').click();await panel.locator('[data-homework-review-result] textarea').waitFor({state:'attached'});await panel.locator('[data-homework-review-result] > details').evaluate(x=>x.open=true);const firstText='虚构初轮核对：尚未确认漏答。\n'+await panel.locator('[data-homework-review-result] textarea').inputValue();await panel.locator('[data-homework-review-result] textarea').fill(firstText);await panel.locator('[data-homework-review-confirm]').check();const firstUpload=p.waitForResponse(r=>r.url().endsWith('/api/upload'));await panel.locator('[data-homework-review-apply]').click();const firstUploadResponse=await firstUpload;assert.equal(firstUploadResponse.status(),200);const firstAttachment=(await firstUploadResponse.json()).attachment;assert.ok(firstAttachment?.id);await eventually(async()=>/请点下方/.test(await panel.innerText()),'first round staged before another recheck');const firstFiles=[...answer.attachments,teacher.id,firstAttachment.id];assert.equal(await panel.locator('[data-homework-review-result] textarea').isDisabled(),true,'staged first round stays distinct from a new draft');assert.equal(await instruction.isEnabled(),true,'parent can clarify an omission before the next recheck');await instruction.fill('');await instruction.fill('虚构新增补充：第2题还有一小问，请重新核对。');
  const secondResponse=p.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'));await panel.locator('[data-homework-review-run]').click();assert.equal((await secondResponse).status(),200);await eventually(async()=>await panel.locator('[data-homework-review-result] textarea').inputValue()!==firstText,'new round generated while first round awaits save');const secondText=await panel.locator('[data-homework-review-result] textarea').inputValue();assert.equal(reviewBodies.length,2);assert.equal(reviewBodies[1].record_id,answer.id);assert.equal(reviewBodies[1].previous_text,firstText);assert.equal(reviewBodies[1].review_instruction,'虚构新增补充：第2题还有一小问，请重新核对。');assert.deepEqual(reviewBodies[1].question_sources,reviewBodies[0].question_sources);assert.deepEqual(reviewBodies[1].reference_sources,[{type:'upload',id:teacher.id}]);assert.equal(await panel.locator('[data-homework-review-result] textarea').isEnabled(),true);assert.equal(await panel.locator('[data-homework-review-previous] textarea').inputValue(),firstText);assert.equal(await panel.locator('[data-homework-review-previous] textarea').isDisabled(),true);
  const saveBodies=[];let lost=true;await p.route('**/api/task/feedback',async r=>{saveBodies.push(r.request().postDataJSON());if(lost){lost=false;const response=await r.fetch();assert.equal(response.status(),200);assert.ok((await response.json()).record_id);return r.fulfill({status:503,json:{error:'虚构初轮保存回执丢失'}})}return r.continue()});await p.locator('#saveTaskFeedback').click();await eventually(async()=>/虚构初轮保存回执丢失/.test(await p.locator('#taskError').innerText()),'staged first round save reply lost');assert.equal(await panel.locator('[data-homework-review-result] textarea').inputValue(),secondText,'failed first-round save retains the newer draft');assert.equal(await panel.locator('[data-homework-review-result] textarea').isDisabled(),true,'unknown save result locks the newer draft until retry');assert.equal(await panel.locator('[data-homework-review-result] textarea').getAttribute('data-feedback-lock'),'enabled','retry lock remembers the newer draft was editable');assert.equal(await panel.locator('[data-homework-review-previous] textarea').inputValue(),firstText);assert.equal(await panel.locator('[data-homework-review-previous] textarea').getAttribute('data-feedback-lock'),'disabled','retry lock keeps archived first round distinct');assert.deepEqual(saveBodies[0].attachments,firstFiles,'saving first round uses its staged TXT, not the newer draft');
  let sourceRefreshes=0;await p.route('**/api/print/homework/sources**',r=>{const url=new URL(r.request().url());if(url.searchParams.get('task_id')===task.id&&url.searchParams.get('record_id')===String(answer.id)&&++sourceRefreshes===2)return r.fulfill({status:503,json:{error:'虚构保存后老师资料刷新失败'}});return r.continue()});await p.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'first round retry acknowledged');assert.equal(await panel.locator('[data-homework-review-result] textarea').count(),1,'saved first round must not delete the newer same-answer draft');await eventually(async()=>/虚构保存后老师资料刷新失败/.test(await panel.locator('[data-homework-review-status]').innerText()),'retained panel source refresh fails once');assert.equal(sourceRefreshes,2);await p.unroute('**/api/print/homework/sources**');assert.equal(saveBodies.length,2);assert.deepEqual(saveBodies[1],saveBodies[0],'lost-receipt retry uses the original first-round body');assert.equal(await panel.locator('[data-homework-review-result] textarea').count(),1,'saving the staged first round retains the newer round on the same original answer');assert.equal(await panel.locator('[data-homework-review-result] textarea').inputValue(),secondText);assert.equal(await panel.locator('[data-homework-review-result] textarea').isEnabled(),true);assert.equal(await panel.locator('[data-homework-review-previous] textarea').inputValue(),firstText);assert.equal(await panel.locator('[data-homework-review-previous] textarea').isDisabled(),true,'saved first round remains locked in the comparison');assert.equal(await instruction.isEnabled(),true,'newer round can still receive parent clarification after first-round save');await panel.scrollIntoViewIfNeeded();await proof(p,'staged-recheck-retained-'+width);assert.equal(await teacherRow.count(),1,'failed source refresh retains the original teacher control');assert.equal(await teacherRow.locator('[data-homework-review-photo]').isChecked(),true);assert.equal(await teacherRow.locator('[data-homework-review-role]').inputValue(),'reference');assert.deepEqual(await panel.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value)),[...answer.attachments,teacher.id],'failed source refresh retains the exact selected IDs');
  const firstState=await read(),firstRecord=firstState.records.find(r=>r.followup_kind==='作业检查'&&r.related_record_id===answer.id);assert(firstRecord);assert.deepEqual(firstRecord.attachments,firstFiles);assert.equal(firstRecord.comparison_note,'虚构补充：请核对第1题是否漏答。','new clarification does not rewrite the staged first round');assert.equal(firstState.records.filter(r=>r.followup_kind==='作业检查'&&r.related_record_id===answer.id).length,1,'lost first-round reply creates one saved check');await panel.locator('[data-homework-review-result] [data-homework-review-confirm]').check();await panel.locator('[data-homework-review-result] [data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await panel.innerText()),'retained newer round can be staged');const stagedInstruction=await instruction.inputValue();await instruction.fill('');rejectNext=true;await p.locator('#saveTaskFeedback').click();assert.equal(rejectNext,false,'clearing the old clarification triggers the shared unsaved-review warning');assert.match(dialogs.at(-1),/未保存的 AI 检查意见/);assert.equal(saveBodies.length,2,'declining the warning makes no save request');assert.equal(await instruction.inputValue(),'','declining retains the cleared instruction');await instruction.fill(stagedInstruction);const beforeUnchangedSave=dialogs.length;await p.locator('#saveTaskFeedback').click();assert.equal(dialogs.length,beforeUnchangedSave,'unchanged staged instruction does not cause a false extra warning');await eventually(async()=>/反馈已保存/.test(await p.locator('#taskFeedbackStatus').innerText()),'newer round saved separately');await p.unroute('**/api/task/feedback');assert.equal(saveBodies.length,3);assert.notEqual(saveBodies[2].request_key,saveBodies[0].request_key);
  await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.reload();await ready(p);await open();const state=await read(),reviews=state.records.filter(r=>r.followup_kind==='作业检查'&&r.related_record_id===answer.id);assert.equal(reviews.length,2,'reopening retains exactly two separately saved rounds');assert.notEqual(reviews[0].id,reviews[1].id);assert.deepEqual(state.records.find(r=>r.id===answer.id),answer,'checks leave the original answer unchanged');assert.deepEqual(state.tasks.find(t=>t.id===task.id).update,task.update,'checks leave homework state unchanged');assert(reviews.every(r=>r.child===owner.name&&r.source==='事项:'+task.id&&r.related_record_id===answer.id));assert.equal(await p.locator('[data-homework-review="'+answer.id+'"]').count(),1,'both checks reopen under the same original answer');assert.deepEqual(state.records.find(r=>r.id===firstRecord.id),firstRecord,'saving the newer round keeps the first saved record intact');
  const newerRecord=reviews.find(r=>r.id!==firstRecord.id),firstTXT=firstAttachment.id,secondTXT=newerRecord.attachments.find(id=>id!==teacher.id&&!answer.attachments.includes(id));assert(firstTXT&&secondTXT&&firstTXT!==secondTXT);const firstDownload=await fetch(host.url+'upload/'+firstTXT),secondDownload=await fetch(host.url+'upload/'+secondTXT);assert.equal(firstDownload.status,200);assert.equal(secondDownload.status,200);const firstSavedText=await firstDownload.text(),secondSavedText=await secondDownload.text();assert(firstSavedText.includes(firstText),'first TXT retains the complete first round');assert(!firstSavedText.includes(secondText),'first TXT is not overwritten by the subsequently generated round');assert(secondSavedText.includes(secondText),'second TXT retains the complete newer round');assert(secondSavedText.includes(firstText),'second TXT retains the complete earlier comparison');assert.equal(await p.locator('#taskFeedbackHistory a[href$="/upload/'+firstTXT+'"]').count(),1);assert.equal(await p.locator('#taskFeedbackHistory a[href$="/upload/'+secondTXT+'"]').count(),1);
  assert.equal((await fetch(host.url+'api/print/homework/saved-review?task_id='+task.id+'&record_id='+newerRecord.id,{headers:{'X-Child-CSRF':'synthetic-child'}})).status,403,'child credentials cannot read parent saved-check opinions');
  const latestView=p.locator('[data-saved-homework-review="'+newerRecord.id+'"]'),oldView=p.locator('[data-saved-homework-review="'+firstRecord.id+'"]');await eventually(async()=>await latestView.locator('[data-saved-review-text]').innerText()===secondText,'saved latest authoritative text is visible in the homework');assert.equal(await latestView.evaluate(x=>x.open),true);assert.equal(await oldView.evaluate(x=>x.open),false,'old saved check stays concise until requested');let previewFailed=false;await p.route('**/api/print/homework/saved-review**',r=>{if(new URL(r.request().url()).searchParams.get('record_id')===String(firstRecord.id)&&!previewFailed){previewFailed=true;return r.fulfill({status:503,json:{error:'虚构已保存检查读取失败'}})}return r.continue()});await oldView.locator(':scope > summary').click();await eventually(async()=>/虚构已保存检查读取失败/.test(await oldView.innerText()),'old saved preview fails safely');assert.equal(await oldView.locator('[data-saved-review-text]').innerText(),'');await oldView.getByRole('button',{name:'重试读取检查'}).click();await eventually(async()=>await oldView.locator('[data-saved-review-text]').innerText()===firstText,'saved first check retries without download or model');await p.unroute('**/api/print/homework/saved-review**');assert.equal(reviewBodies.length,2,'reading saved opinions never calls a model');assert.equal(await latestView.locator('[data-saved-review-text]').innerText(),secondText,'archive is not mixed into the latest authoritative check');assert.match(await latestView.locator('[data-saved-review-status]').innerText(),/较早.*草稿/);await fit(p);await latestView.scrollIntoViewIfNeeded();await proof(p,'saved-check-inline-'+width);
  await p.locator('#taskDialog [data-close="taskDialog"]').click();let releasePreview,heldPreview;await p.route('**/api/print/homework/saved-review**',async r=>{const response=await r.fetch();if(new URL(r.request().url()).searchParams.get('record_id')===String(newerRecord.id)){heldPreview=true;await new Promise(resolve=>releasePreview=resolve)}return r.fulfill({response})});await open();await eventually(async()=>!!heldPreview,'saved review response held');await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.locator('[data-child-filter="'+base.children[1].id+'"]').click();await p.locator('[data-homework-new="'+base.children[1].id+'"]').click();const otherEntry=p.locator('#homeworkInputDialog');await otherEntry.locator('[name=title]').fill('虚构另一孩子预览隔离 '+width);await otherEntry.locator('[data-homework-item] [type=submit]').click();await otherEntry.locator('.homework-saved').waitFor();await otherEntry.locator('[data-homework-close]').click();const otherId=(await read()).tasks.find(t=>t.title==='虚构另一孩子预览隔离 '+width).id;await p.locator('[data-task="'+otherId+'"]').click();releasePreview();await delay(100);assert.equal(await p.locator('[data-saved-review-text]').filter({hasText:secondText}).count(),0,'late preview cannot enter the other child task');await p.locator('#taskDialog [data-close="taskDialog"]').click();await p.locator('[data-child-filter="'+owner.id+'"]').click();await p.unroute('**/api/print/homework/saved-review**');await open();


  // The same recovery must retain a draft when the acknowledged ordinary feedback was later corrected.
  await panel.locator(':scope > details').evaluate(x=>x.open=true);await panel.locator(':scope > details > .homework-review-material [data-homework-review-photo]').check();await instruction.fill('虚构补充：单独反馈保存后还要继续核对漏答。');await panel.locator('[data-homework-review-run]').click();await panel.locator('[data-homework-review-result] textarea').waitFor({state:'attached'});const thirdText=await panel.locator('[data-homework-review-result] textarea').inputValue();await p.locator('#taskForm [name=note]').fill('虚构单独反馈，稍后由另一处更正');const conflictBodies=[];let changedRecordId;await p.route('**/api/task/feedback',async r=>{conflictBodies.push(r.request().postDataJSON());if(conflictBodies.length===1){const response=await r.fetch();assert.equal(response.status(),200);const saved=await response.json();changedRecordId=saved.record_id;const correction=await fetch(host.url+'api/task/feedback',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify({task_id:task.id,child:owner.name,record_id:saved.record_id,expected_created:saved.feedback.created,note:'虚构另一处已经更正的反馈'})});assert.equal(correction.status,200);return r.fulfill({status:503,json:{error:'虚构单独反馈保存回执丢失'}})}return r.continue()});await p.locator('#saveTaskFeedback').click();await eventually(async()=>/虚构单独反馈保存回执丢失/.test(await p.locator('#taskError').innerText()),'ordinary feedback saved and corrected before its lost reply');assert.equal(await panel.locator('[data-homework-review-result] textarea').inputValue(),thirdText);assert.equal(await panel.locator('[data-homework-review-result] textarea').isDisabled(),true);assert.equal(await panel.locator('[data-homework-review-result] textarea').getAttribute('data-feedback-lock'),'enabled');
  const conflictResponse=p.waitForResponse(r=>r.url().endsWith('/api/task/feedback'));await p.locator('#saveTaskFeedback').click();const conflict=await conflictResponse;assert.equal(conflict.status(),409);assert.equal((await conflict.json()).code,'request_record_changed');await eventually(async()=>/这次反馈已保存，后来又被更正/.test(await p.locator('#taskFeedbackStatus').innerText()),'corrected lost receipt verified and unlocked');assert.equal(conflictBodies.length,2);assert.deepEqual(conflictBodies[1],conflictBodies[0]);assert.equal(await panel.locator('[data-homework-review-result] textarea').count(),1,'409 read-back recovery retains the same-answer draft');assert.equal(await panel.locator('[data-homework-review-result] textarea').inputValue(),thirdText);assert.equal(await panel.locator('[data-homework-review-result] textarea').isEnabled(),true);assert.equal(await instruction.isEnabled(),true);assert.equal(await p.locator('#taskForm [name=note]').inputValue(),'虚构另一处已经更正的反馈');const reconciled=await read();assert.equal(reconciled.records.filter(r=>r.request_key===conflictBodies[0].request_key).length,1);assert.equal(reconciled.records.find(r=>r.id===changedRecordId).note,'虚构另一处已经更正的反馈');assert.equal(reconciled.records.filter(r=>r.followup_kind==='作业检查'&&r.related_record_id===answer.id).length,2);assert.deepEqual(reconciled.records.find(r=>r.id===answer.id),answer);assert.deepEqual(reconciled.tasks.find(t=>t.id===task.id).update,task.update);await p.unroute('**/api/task/feedback');await fit(p);assert.deepEqual(errors,[]);checks.push({width,stagedThenRecheck:true,firstReplyRetry:true,newerDraftAndArchiveRetained:true,twoIndependentChecksReopened:true,correctedReply409KeepsDraft:true,originalAnswerChildAndStateUnchanged:true});
 }finally{await p.close()}
}
function daily(base){
 const day='2026-09-28',kids=base.children;
 const task=(id,title,due,owner=kids[0])=>({id,title,child:owner.name,due,action:'虚构要求：'+title,original_status:'待跟进',history:[],source:'message:synthetic-admin-'+owner.id+':'+id,agenda:{category:'todo',box:'inbox',published_on:'2026-09-27',due_on:due,scheduled_on:''}});
 const tasks=[task('sign','虚构回执签字','2026-09-27'),task('print','虚构打印两页回执',''),task('stamp','虚构材料盖章','2026-09-29',kids[1])];
 const notices=kids.flatMap((kid,k)=>Array.from({length:4},(_,n)=>({id:'admin-'+k+'-'+n,kind:'school',child_id:kid.id,state:'pending',title:'虚构办理通知 '+k+'-'+n,body:'虚构要求：核对材料后交回。',evidence:[],plan:{school_task:{state:'review',purpose:'admin',title:'虚构办理通知 '+k+'-'+n,goal:'虚构要求：核对材料后交回。',reason:'虚构适用条件仍待核对。'}}})));
 const inbox=[...tasks.map(t=>({id:t.id,task_id:t.id,kind:'task',title:t.title,child_ids:[kids.find(k=>k.name===t.child).id],closed:false,status:'待跟进',agenda:t.agenda})),...notices.map((n,i)=>({id:n.id,kind:'school',title:n.title,child_ids:[n.child_id],closed:false,status:'待核对',agenda:{category:'todo',box:'inbox',published_on:i<4?'2026-09-27':'2026-09-26',published_at:(i<4?'2026-09-27':'2026-09-26')+'T'+String(12+i%4).padStart(2,'0')+':00:00+08:00',due_on:'',scheduled_on:''}}))];
 return {...base,today:day,tasks,records:[],agent:{...base.agent,sources:kids.map(k=>({id:'synthetic-admin-'+k.id,child_id:k.id,platform:'qq',name:'虚构学校群',enabled:true})),items:notices},today_calendar:{inbox,agenda:[],events:[],timetables:kids.map((k,i)=>({id:'table-'+i,child_id:k.id,day,title:'虚构当天课表',sessions:[{slot:'第一节',title:'虚构数学 '+i},{slot:'第二节',title:'虚构语文 '+i}]})),source_error:''}};
}
(async()=>{
 let host,browser;const checks=[];
 try{
  host=await server();browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  const read=async()=>await(await fetch(host.url+'api/state')).json(),base=await read(),pdf=Buffer.from(await(await fetch(host.url+'attachment/'+encodeURIComponent('演示练习.pdf'))).arrayBuffer());
  assert.equal(pdf.subarray(0,5).toString(),'%PDF-','use the disposable demo PDF');
  for(const width of [360,1440]){
   const p=await browser.newPage({viewport:{width,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
   try{
    const state=daily(base);await p.route('**/api/state',r=>r.fulfill({json:state}));await p.goto(host.url);await ready(p);
    const todo=p.locator('#task-group-todo');await selectedChild(p,state.children,state.children[0]);assert.equal(await todo.locator('[data-query-target="task:stamp"]').count(),0,'default first child omits the other child task');
    await fit(p);await proof(p,'daily-'+width);
    for(const [k,kid] of state.children.entries()){
     await p.locator('[data-child-filter="'+kid.id+'"]').click();await selectedChild(p,state.children,kid);const tasks=state.tasks.filter(t=>t.child===kid.name);assert.match(await todo.locator('h2').innerText(),new RegExp('要办的事 · '+tasks.length+'[\\s\\S]*待核对 4'));assert.equal(await todo.locator('[data-agent-item]').count(),4);
     assert.deepEqual(await todo.locator('[data-query-target^="task:"]').evaluateAll(xs=>xs.map(x=>x.dataset.queryTarget)),tasks.map(t=>'task:'+t.id),'only this child administration is listed');
     for(const task of tasks){const card=todo.locator('[data-query-target="task:'+task.id+'"]');assert.equal(await card.isVisible(),true);assert.equal(await card.locator('[data-school-original-ref]').isVisible(),true,'administrative original stays directly visible');assert.equal(await card.evaluate(x=>!!x.closest('.task-list')),true,'administration remains in the task list');assert.match(await card.innerText(),task.due?new RegExp((task.id==='sign'?'逾期 · ':'')+'截止：'+task.due):/截止待核对/)}
     const boxes=await todo.locator('[data-query-target^="task:"]').evaluateAll(xs=>xs.map(x=>({top:x.getBoundingClientRect().top,bottom:x.getBoundingClientRect().bottom})));assert.ok(boxes.every((x,i)=>!i||x.top>=boxes[i-1].bottom),'administration is a single vertical list at both widths');
     for(const id of [0,1,2,3]){const notice=todo.locator('[data-agent-item="admin-'+k+'-'+id+'"]');assert.equal(await notice.isVisible(),true,'all four notices for the selected child remain visible');assert.equal(await p.locator('[data-agent-item="admin-'+k+'-'+id+'"]').count(),1)}
     assert.equal(await todo.locator('[data-agent-item] [data-check]').count(),0,'unreviewed notices cannot be completed');
     assert.equal(await todo.locator('[data-agent-item^="admin-'+(1-k)+'-"]').count(),0,'other child notices are omitted');assert.equal(await p.locator('#today-courses .calendar-timetable').count(),1);
     const table=state.today_calendar.timetables.find(t=>t.child_id===kid.id),card=p.locator('[data-query-target="timetable:'+table.id+':'+state.today+'"]');assert.equal(await card.locator('ol').isVisible(),true,'courses need no expansion');assert.equal(await card.evaluate(x=>x.open),true);assert.equal(await card.evaluate(x=>!!x.closest('.task-list')),true,'courses use the same list section');assert.deepEqual(await card.locator('li strong').allTextContents(),table.sessions.map(s=>s.title),'today courses retain their original order');const lessons=await card.locator('li').evaluateAll(xs=>xs.map(x=>({top:x.getBoundingClientRect().top,bottom:x.getBoundingClientRect().bottom})));assert.ok(lessons.every((x,i)=>!i||x.top>=lessons[i-1].bottom),'courses stay one lesson per row');
     await fit(p);await proof(p,'daily-child-'+k+'-'+width);
    }
    const retained=state.children.at(-1);await p.locator('nav [data-page="tasks"]').click();await p.locator('nav [data-page="home"]').click();await ready(p);await selectedChild(p,state.children,retained);assert.equal(await todo.locator('[data-agent-item]').count(),4,'returning to today keeps the selected child notices');assert.equal(await todo.locator('[data-query-target="task:sign"]').count(),0);await p.reload();await ready(p);await selectedChild(p,state.children,retained);assert.equal(await todo.locator('[data-agent-item]').count(),4,'reload keeps the selected child notices');assert.equal(await todo.locator('[data-query-target="task:stamp"]').isVisible(),true);assert.equal(await p.locator('#today-courses .calendar-timetable').count(),1);assert.deepEqual(errors,[]);checks.push({width,dailyAdministration:true,eightNoticesAcrossChildren:true,coursesVisible:true,childIsolation:true,defaultSingleChild:true,noAllChildren:true,childPersistsAcrossNavigationAndReload:true,taskLists:true});
   }catch(e){await proof(p,'daily-failure-'+width);throw e}finally{await p.close()}
   const q=await browser.newPage({viewport:{width,height:850}}),manualErrors=[];q.on('pageerror',e=>manualErrors.push(e.message));q.on('dialog',d=>d.accept());let modelCalls=0;
   await q.route('**/api/study/draft',r=>{modelCalls++;return r.fulfill({status:503,json:{error:'Manual scenario must not invoke a model'}})});
   await q.route('**/api/print/homework/draft',r=>{modelCalls++;return r.fulfill({status:503,json:{error:'Manual scenario must not invoke a model'}})});
   try{
    const owner=base.children[0],other=base.children[1],title='虚构电子卷与照片 '+width,goal='完成虚构第1题，保留原题供核对。';await q.goto(host.url);await ready(q);await q.locator('[data-homework-new="'+owner.id+'"]').click();
    const entry=q.locator('#homeworkInputDialog'),form=entry.locator('[data-homework-item="0"]');
    assert.equal(await entry.locator('[data-homework-original]').evaluate(x=>x.open),false);assert.equal(await entry.locator('.homework-materials').isVisible(),true,'trial sheet upload is a primary entry');assert.match(await entry.locator('.homework-materials').innerText(),/上传试卷 \/ 参考答案[\s\S]*拍试卷/);
    assert.equal(await form.locator('[name=reviewed]').count(),0);assert.equal(await form.locator('[name=subject]').isVisible(),false);assert.equal(await form.locator('[name=planned_minutes]').isVisible(),false);
    assert.match(await entry.locator('[data-homework-files]').first().getAttribute('accept'),/application\/pdf/);await form.locator('[name=title]').fill(title);await form.locator('[name=goal]').fill(goal);
    let uploads=0;await q.route('**/api/upload',r=>++uploads===1?r.fulfill({status:503,json:{error:'虚构上传失败'}}):r.continue());
    await entry.locator('[data-homework-files]').first().setInputFiles({name:'synthetic-paper.pdf',mimeType:'application/pdf',buffer:pdf});await entry.locator('[data-homework-retry-file]').waitFor();
    assert.equal(await form.locator('[name=title]').inputValue(),title);assert.equal(await form.locator('[name=goal]').inputValue(),goal);await form.locator('[type=submit]').click();assert.match(await entry.innerText(),/先完成或移除未成功的上传/);assert.equal((await read()).tasks.filter(t=>t.title===title).length,0,'failed upload does not create a partial task');
    await entry.locator('[data-homework-close]').click();await q.locator('[data-homework-new="'+owner.id+'"]').click();assert.equal(await form.locator('[name=title]').inputValue(),title);assert.equal(await form.locator('[name=goal]').inputValue(),goal);assert.equal(await entry.locator('[data-homework-retry-file]').count(),1,'failed PDF survives close and reopen');
    await entry.locator('[data-homework-retry-file]').click();await eventually(async()=>!await entry.locator('[data-homework-retry-file]').count(),'PDF retry');
    await entry.locator('[data-homework-files]').first().setInputFiles({name:'synthetic-question.png',mimeType:'image/png',buffer:png});await eventually(async()=>await entry.locator('.homework-files small').count()===2&&await entry.locator('.homework-files small').allTextContents().then(x=>x.every(t=>t==='原件已保存')),'two saved originals');
    await fit(q);await proof(q,'new-materials-'+width);await form.locator('[type=submit]').click();await entry.locator('.homework-saved').waitFor();await entry.locator('[data-homework-close]').click();await q.unroute('**/api/upload');
    const tasks=(await read()).tasks.filter(t=>t.title===title);assert.equal(tasks.length,1);const task=tasks[0];assert.equal(task.child,owner.name);assert.notEqual(task.update?.status,'已完成');
    const study=await(await fetch(host.url+'api/study?'+new URLSearchParams({child_id:owner.id,day:base.today}))).json(),saved=study.items.find(i=>i.task_id===task.id);assert.ok(saved);assert.equal(saved.report.attachments.length,2);const ids=saved.report.attachments;
    await q.reload();await ready(q);const card=q.locator('[data-query-target="task:'+task.id+'"]');assert.equal(await card.count(),1);assert.equal(await card.locator('.task-requirement').innerText(),goal);await card.locator('[data-task="'+task.id+'"]').click();
    await q.locator('#cameraInput').setInputFiles({name:'synthetic-answer.png',mimeType:'image/png',buffer:png});await q.locator('#pendingUploads img').waitFor();await q.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await q.locator('#taskFeedbackStatus').innerText()),'answer saved');
    const panel=q.locator('#taskFeedbackHistory [data-homework-review]').first();await panel.waitFor();await eventually(async()=>await panel.locator('[data-homework-review-sources] [data-review-source]').count()===2,'same task reported material sources');
    await panel.locator('details:has(> [data-homework-review-sources]) > summary').click();for(const id of ids)assert.equal(await panel.locator('[data-homework-review-sources] [data-review-source="'+id+'"]').isVisible(),true,'PDF/photo remain selectable for this task after reload');
    await fit(q);await proof(q,'same-task-materials-'+width);await q.locator('#taskDialog [data-close="taskDialog"]').click();await q.reload();await ready(q);await q.locator('[data-query-target="task:'+task.id+'"] [data-task="'+task.id+'"]').click();
    const reopened=q.locator('#taskFeedbackHistory [data-homework-review]').first();await eventually(async()=>await reopened.locator('[data-homework-review-sources] [data-review-source]').count()===2,'reopened task retains source identities');for(const id of ids)assert.equal(await reopened.locator('[data-review-source="'+id+'"]').count(),1);
    const answerRecordId=Number(await reopened.getAttribute('data-homework-review')),initialInstruction='请先检查第1题，保留缺少老师依据的说明。';
    assert.ok(answerRecordId);await reopened.locator(':scope > details').evaluate(x=>x.open=true);await reopened.locator(':scope > details > .homework-review-material [data-homework-review-photo]').first().check();
    const initialInput=reopened.locator('[data-homework-review-instruction]');assert.equal(await initialInput.getAttribute('maxlength'),'1000');await initialInput.fill(initialInstruction);
    await q.unroute('**/api/print/homework/draft');const reviewBodies=[];let failReview=false,holdReview=false,releaseReview;
    await q.route('**/api/print/homework/draft',async r=>{reviewBodies.push(r.request().postDataJSON());if(failReview){failReview=false;return r.fulfill({status:503,json:{error:'虚构模型暂不可用'}})}if(holdReview){holdReview=false;await new Promise(resolve=>releaseReview=resolve)}return r.continue()});
    const initialResponse=q.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'),{timeout:40000});await reopened.locator('[data-homework-review-run]').click();assert.equal((await initialResponse).status(),200);await reopened.locator('.homework-review-questions summary').first().waitFor();
    assert.equal(reviewBodies.at(-1).review_instruction,initialInstruction,'one parent sentence reaches review');assert.deepEqual(reviewBodies.at(-1).reference_sources,[]);assert.deepEqual(reviewBodies.at(-1).previous_sources,[]);
    const initialText=await reopened.locator('[data-homework-review-result] textarea').inputValue(),initialSelection=await reopened.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value));assert.match(initialText,/虚构检查第\d+轮/);
    q.removeAllListeners('dialog');q.once('dialog',d=>d.dismiss());const callsBeforeCancel=reviewBodies.length;await reopened.locator('[data-homework-review-run]').click();assert.equal(reviewBodies.length,callsBeforeCancel,'cancelling a further round calls no model');assert.equal(await reopened.locator('[data-homework-review-result] textarea').inputValue(),initialText);q.on('dialog',d=>d.accept());
    const teacherUploaded=q.waitForResponse(r=>r.url().endsWith('/api/upload'));await q.locator('#fileInput').setInputFiles({name:'synthetic-teacher.txt',mimeType:'text/plain',buffer:Buffer.from('第1题 B')});const teacher=(await(await teacherUploaded).json()).attachment;assert.ok(teacher?.id);await eventually(async()=>/synthetic-teacher\.txt/.test(await q.locator('#pendingUploads').innerText()),'teacher reference uploaded beside the unsaved initial check');await q.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await q.locator('#taskFeedbackStatus').innerText()),'teacher reference saved without saving initial check');await eventually(async()=>await reopened.locator('[data-review-source="'+teacher.id+'"]').count()===1,'new teacher reference reaches the preserved original answer panel');
    assert.equal(await reopened.locator('[data-homework-review-result] textarea').inputValue(),initialText,'saving teacher reference retains the unsaved initial opinion');assert.equal(await initialInput.inputValue(),initialInstruction);assert.deepEqual(await reopened.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value)),initialSelection,'saving another reference keeps existing material choices');await reopened.locator('details:has(> [data-homework-review-sources])').evaluate(x=>x.open=true);const firstTeacher=reopened.locator('[data-review-source="'+teacher.id+'"]');assert.equal(await firstTeacher.locator('[data-homework-review-role]').inputValue(),'reference');await firstTeacher.locator('[data-homework-review-photo]').check();const failedSelection=await reopened.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value));
    failReview=true;await initialInput.fill('请再检查第1题，上一轮意见先保留。');const failedReview=q.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'));await reopened.locator('[data-homework-review-run]').click();assert.equal((await failedReview).status(),503);await eventually(async()=>await reopened.locator('[data-homework-review-run]').isEnabled(),'failed recheck unlocked');
    assert.match(await reopened.locator('[data-homework-review-status]').innerText(),/虚构模型暂不可用/);assert.equal(await reopened.locator('[data-homework-review-result] textarea').inputValue(),initialText,'failed recheck keeps the initial editable opinion');assert.deepEqual(await reopened.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value)),failedSelection);assert.equal(await initialInput.inputValue(),'请再检查第1题，上一轮意见先保留。');assert.equal(reviewBodies.at(-1).previous_text,initialText.trim(),'unsaved prior opinion survives teacher reference save and is sent for recheck');assert.ok(reviewBodies.at(-1).reference_sources.some(x=>x.id===teacher.id),'the new teacher reference accompanies the retained initial opinion');
    await initialInput.fill(initialInstruction);await firstTeacher.locator('[data-homework-review-photo]').uncheck();await reopened.locator('[data-homework-review-confirm]').check();let checkUploads=0;await q.route('**/api/upload',r=>++checkUploads===1?r.fulfill({status:503,json:{error:'虚构检查文字上传失败'}}):r.continue());
    await reopened.locator('[data-homework-review-apply]').click();await eventually(async()=>/虚构检查文字上传失败/.test(await reopened.innerText()),'initial opinion upload fails safely');assert.equal(await reopened.locator('[data-homework-review-result] textarea').inputValue(),initialText);assert.equal(await reopened.locator('[data-homework-review-apply]').isEnabled(),true);assert.equal(await q.locator('#taskForm [name=note]').inputValue(),'');
    await reopened.locator('[data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await reopened.innerText()),'initial opinion staged after upload retry');await q.unroute('**/api/upload');await q.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await q.locator('#taskFeedbackStatus').innerText()),'initial opinion saved');
    const firstState=await read(),firstResult=firstState.records.find(r=>r.followup_kind==='作业检查'&&r.related_record_id===answerRecordId);assert.ok(firstResult,'saved initial opinion explicitly follows its original answer');assert.equal(firstResult.source,'事项:'+task.id);assert.equal(firstResult.comparison_note,initialInstruction);
    const previousId=firstResult.attachments.find(id=>firstState.uploads.find(a=>a.id===id)?.mime.split(';')[0]==='text/plain');assert.ok(previousId);
    // The later teacher reference is independent feedback and remains available on reopening the original answer.
    await q.locator('#taskDialog [data-close="taskDialog"]').click();await q.reload();await ready(q);await q.locator('[data-query-target="task:'+task.id+'"] [data-task="'+task.id+'"]').click();
    const check=q.locator('#taskFeedbackHistory [data-homework-review="'+answerRecordId+'"]');await eventually(async()=>await check.locator('[data-review-source="'+teacher.id+'"]').count()===1,'later teacher is available to original answer');
    await check.locator(':scope > details').evaluate(x=>x.open=true);await check.locator(':scope > details > .homework-review-material [data-homework-review-photo]').first().check();await check.locator('details:has(> [data-homework-review-sources])').evaluate(x=>x.open=true);
    const sourceResponse=await fetch(host.url+'api/print/homework/sources?'+new URLSearchParams({task_id:task.id,record_id:String(answerRecordId)}));assert.equal(sourceResponse.status,200);assert.equal((await sourceResponse.json()).sources.find(a=>a.id===previousId)?.origin,'review_result','saved AI opinion has explicit history provenance');
    const oldOpinion=check.locator('[data-review-source="'+previousId+'"]');await oldOpinion.waitFor();assert.equal(await oldOpinion.locator('[data-homework-review-role]').inputValue(),'previous','saved AI opinion is not teacher reference');assert.equal(await oldOpinion.locator('[data-homework-review-role] option[value=reference]').count(),0,'saved AI opinion cannot be selected as teacher evidence');await oldOpinion.locator('[data-homework-review-photo]').check();const recheckInstruction='第1题请优先按老师参考核对，并说明上次哪里漏看。';await check.locator('[data-homework-review-instruction]').fill(recheckInstruction);
    const txt=check.locator('[data-review-source="'+teacher.id+'"]');await txt.locator('[data-homework-review-photo]').check();assert.equal(await txt.locator('[data-homework-review-role]').inputValue(),'reference','TXT with charset is explicitly reference');
    const paperSource=check.locator('[data-review-source="'+ids[0]+'"]');await paperSource.locator('[data-homework-review-photo]').check();await paperSource.locator('details').evaluate(x=>x.open=true);await paperSource.locator('[data-homework-review-role]').selectOption('reference');await paperSource.locator('[data-homework-review-pages]').fill('1');
    const responsePending=q.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'),{timeout:40000});await check.locator('[data-homework-review-run]').click();const referenceResponse=await responsePending;assert.equal(referenceResponse.status(),200,await referenceResponse.text());assert.equal(reviewBodies.at(-1).review_instruction,recheckInstruction);assert.deepEqual(reviewBodies.at(-1).previous_sources,[{type:'upload',id:previousId}]);assert.equal(!!reviewBodies.at(-1).previous_text,false,'saved prior opinion is not duplicated as inline text');assert.ok(reviewBodies.at(-1).reference_sources.some(x=>x.id===teacher.id));assert.ok(!reviewBodies.at(-1).reference_sources.some(x=>x.id===previousId),'AI history never becomes teacher evidence');await check.locator('.homework-review-questions summary').first().waitFor();assert.match(await check.locator('[data-homework-review-status]').innerText(),/题/,'reference model status: '+await check.innerText());assert.match(await check.innerText(),/第1题 · 需要订正/);assert.match(await check.innerText(),/教师参考：B/);
    assert.equal(await check.locator('[data-homework-review-result] > details').evaluate(x=>x.open),false,'long text stays secondary');assert.match(await check.locator('[data-homework-review-result]').innerText(),/补充老师参考后，第1题需订正/);await proof(q,'reference-check-'+width);
    const referenceText=await check.locator('[data-homework-review-result] textarea').inputValue();await check.locator('[data-homework-review-result] [data-homework-review-confirm]').check();const requestsBeforeChange=reviewBodies.length;
    await check.locator('[data-homework-review-instruction]').fill('已改变的核对要求，不得套用上一轮结果。');await check.locator('[data-homework-review-result] [data-homework-review-apply]').click();assert.match(await check.locator('[data-homework-review-status]').innerText(),/变化|重新|改变/);assert.equal(await check.locator('[data-homework-review-result] textarea').inputValue(),referenceText);assert.equal(await q.locator('#taskForm [name=note]').inputValue(),'');assert.equal(reviewBodies.length,requestsBeforeChange,'editing the instruction does not silently call a model');
    await check.locator('[data-homework-review-instruction]').fill(recheckInstruction);await oldOpinion.locator('[data-homework-review-photo]').uncheck();await check.locator('[data-homework-review-result] [data-homework-review-apply]').click();assert.match(await check.locator('[data-homework-review-status]').innerText(),/变化|重新|改变/);assert.equal(await check.locator('[data-homework-review-result] textarea').inputValue(),referenceText);assert.equal(await q.locator('#taskForm [name=note]').inputValue(),'');await oldOpinion.locator('[data-homework-review-photo]').check();
    holdReview=true;releaseReview=null;const staleResponse=q.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'),{timeout:40000});await check.locator('[data-homework-review-run]').click();await eventually(()=>!!releaseReview,'recheck held in flight');assert.equal(await check.locator('[data-homework-review-result] textarea').inputValue(),referenceText,'starting a round keeps the earlier opinion');assert.equal(reviewBodies.at(-1).previous_text,referenceText);await check.locator('[data-homework-review-instruction]').evaluate(x=>x.value='请求飞行中修改的要求');releaseReview();assert.equal((await staleResponse).status(),200);await eventually(async()=>await check.locator('[data-homework-review-run]').isEnabled(),'stale instruction response unlocked');assert.match(await check.locator('[data-homework-review-status]').innerText(),/变化|重新|改变/);assert.equal(await check.locator('[data-homework-review-result] textarea').inputValue(),referenceText,'late response cannot replace the original opinion after instruction changes');assert.equal(await check.locator('[data-homework-review-previous] > details').count(),0,'rejected response does not archive or overwrite the current opinion');
    const nextInstruction='再核查第1题的老师依据，说明与上一轮的变化。';await check.locator('[data-homework-review-instruction]').fill(nextInstruction);const nextResponse=q.waitForResponse(r=>r.url().endsWith('/api/print/homework/draft'),{timeout:40000});await check.locator('[data-homework-review-run]').click();assert.equal((await nextResponse).status(),200);await eventually(async()=>await check.locator('[data-homework-review-result] textarea').inputValue()!==referenceText,'latest result replaces only after success');
    const previous=check.locator('[data-homework-review-previous] > details');assert.equal(await previous.count(),1);assert.equal(await previous.evaluate(x=>x.open),false,'previous result stays in a collapsed comparison');assert.equal(await previous.locator('textarea').inputValue(),referenceText);assert.equal(await previous.locator('textarea').isDisabled(),true,'old opinion cannot overwrite the latest edit');assert.match(await check.locator('[data-homework-review-result]').innerText(),/补充老师参考后，第1题需订正/);assert.equal(reviewBodies.at(-1).review_instruction,nextInstruction);assert.deepEqual(reviewBodies.at(-1).previous_sources,[{type:'upload',id:previousId}]);assert.equal(reviewBodies.at(-1).previous_text,referenceText,'third round includes the immediately preceding unsaved opinion alongside saved history');const latestText=await check.locator('[data-homework-review-result] textarea').inputValue();await fit(q);await proof(q,'continuous-recheck-'+width);
    const longPrior='虚构较长的上一轮意见：'+'字'.repeat(8000),longRequest=await fetch(host.url+'api/print/homework/draft',{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':(await read()).token},body:JSON.stringify({...reviewBodies.at(-1),previous_text:longPrior})});assert.equal(longRequest.status,200,'declared 12000-character recheck input works through the HTTP byte boundary');assert.ok((await longRequest.json()).draft.text);
    const choicesBeforeSave=await check.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value)),addendumUploaded=q.waitForResponse(r=>r.url().endsWith('/api/upload'));await q.locator('#fileInput').setInputFiles({name:'synthetic-teacher-addendum.txt',mimeType:'text/plain',buffer:Buffer.from('第1题老师参考仍为B，仅补充核对要求。')});const addendum=(await(await addendumUploaded).json()).attachment;assert.ok(addendum?.id);await eventually(async()=>/synthetic-teacher-addendum\.txt/.test(await q.locator('#pendingUploads').innerText()),'another teacher reference uploaded after a successful recheck');await q.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await q.locator('#taskFeedbackStatus').innerText()),'another teacher reference saved beside the retained rounds');await eventually(async()=>await check.locator('[data-review-source="'+addendum.id+'"]').count()===1,'reference list refreshed without discarding recheck rounds');assert.equal(await check.locator('[data-homework-review-result] textarea').inputValue(),latestText);assert.equal(await previous.locator('textarea').inputValue(),referenceText);assert.equal(await previous.locator('textarea').isDisabled(),true,'saving another reference does not unlock an archived opinion');assert.deepEqual(await check.locator('[data-homework-review-photo]:checked').evaluateAll(xs=>xs.map(x=>x.value)),choicesBeforeSave,'reference refresh preserves selected source roles');
    await check.locator('[data-homework-review-result] [data-homework-review-confirm]').check();await check.locator('[data-homework-review-result] [data-homework-review-apply]').click();await eventually(async()=>/请点下方/.test(await check.innerText()),'reference check staged');await q.locator('#saveTaskFeedback').click();await eventually(async()=>/反馈已保存/.test(await q.locator('#taskFeedbackStatus').innerText()),'reference basis saved');
    await q.locator('#taskDialog [data-close="taskDialog"]').click();await q.reload();await ready(q);await q.locator('[data-query-target="task:'+task.id+'"] [data-task="'+task.id+'"]').click();assert.match(await q.locator('#taskFeedbackHistory').innerText(),new RegExp('检查意见[\\s\\S]*原作答 #'+answerRecordId));const finalState=await read(),reviewRecords=finalState.records.filter(r=>r.followup_kind==='作业检查'&&r.related_record_id===answerRecordId);assert.equal(reviewRecords.length,2,'initial opinion and recheck are separate saved records');assert.ok(reviewRecords.every(r=>r.child===owner.name&&r.source==='事项:'+task.id));assert.ok(reviewRecords.some(r=>r.comparison_note===initialInstruction));assert.ok(reviewRecords.some(r=>r.comparison_note===nextInstruction));const lastRecord=reviewRecords.find(r=>r.comparison_note===nextInstruction),latestTxt=lastRecord.attachments.find(id=>id!==teacher.id&&id!==previousId&&finalState.uploads.find(a=>a.id===id)?.mime.split(';')[0]==='text/plain');assert.ok(latestTxt);await eventually(async()=>await q.locator('[data-saved-homework-review="'+lastRecord.id+'"] [data-saved-review-text]').innerText()===latestText.trim(),'latest teacher-based saved check reopens directly in the task');const downloaded=await fetch(host.url+'upload/'+latestTxt);assert.equal(downloaded.status,200);const retainedText=await downloaded.text();assert.ok(retainedText.includes(referenceText.trim()),'reopened result TXT retains the previous unsaved round in full');assert.ok(retainedText.includes(latestText.trim()),'reopened result TXT retains the latest round in full');assert.match(retainedText,/此前检查草稿|不是教师参考|供对照/);assert.notEqual(finalState.tasks.find(t=>t.id===task.id).update?.status,'已完成','saving a recheck is not task completion');await q.locator('#taskDialog [data-close="taskDialog"]').click();
    const legacyState={...finalState,records:finalState.records.map(r=>reviewRecords.some(x=>x.id===r.id)?{...r,followup_kind:'',related_record_id:null}:r)};await q.route('**/api/state',r=>r.fulfill({json:legacyState}));await q.reload();await ready(q);await q.locator('[data-query-target="task:'+task.id+'"] [data-task="'+task.id+'"]').click();for(const r of reviewRecords){assert.equal(await q.locator('[data-homework-review="'+r.id+'"]').count(),0,'unambiguously marked old AI record is not another child answer');assert.equal(await q.locator('[data-task-feedback-edit="'+r.id+'"]').count(),0)}await q.locator('#taskDialog [data-close="taskDialog"]').click();
    await q.locator('[data-child-filter="'+other.id+'"]').click();assert.equal(await q.locator('[data-query-target="task:'+task.id+'"]').count(),0,'same material task is absent for the other child');
    const otherStudy=await(await fetch(host.url+'api/study?'+new URLSearchParams({child_id:other.id,day:base.today}))).json();assert.equal(otherStudy.items.some(i=>i.task_id===task.id),false);assert.equal(modelCalls,0);assert.deepEqual(manualErrors,[]);checks.push({width,parentPDFAndPhoto:true,uploadFailurePreservesDraft:true,retry:true,savedOnce:true,reopenSameTaskSources:true,noModelDuringCapture:true,referencePDFAndText:true,laterReference:true,referenceBasisSaved:true,naturalLanguageRecheck:true,teacherSaveKeepsInitial:true,archivedOpinionStaysLocked:true,failedRecheckKeepsInitial:true,previousAISeparate:true,changedInstructionAndSelectionRejected:true,comparisonRetainsBoth:true,checkUploadRetry:true,relatedReviewReopen:true,childIsolation:true});
   }catch(e){await proof(q,'manual-failure-'+width);throw e}finally{await q.close()}
   await stagedRecheck(browser,host,base,width,checks);
   await multiplePapers(browser,host,base,width,checks);
  }
  const result={passed:checks.length,syntheticOnly:true,realPhone:false,realModels:false,checks};if(process.env.SCENARIOS_UI_PROOF_DIR)await fs.writeFile(path.join(process.env.SCENARIOS_UI_PROOF_DIR,'passed.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }finally{await browser?.close();await host?.stop()}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
