// Disposable synthetic family only. Optional PLAYWRIGHT_MODULE, PLAYWRIGHT_CHANNEL,
// FAMILY_TEST_PYTHON and STUDY_UI_PROOF_DIR; no real accounts, model, or device calls.
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const net=require('node:net');
const {setTimeout:delay}=require('node:timers/promises');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
async function eventually(check,label,timeout=12000){const until=Date.now()+timeout;while(Date.now()<until){if(await check())return;await delay(50)}throw Error('Timed out: '+label)}
async function server(){
 const socket=net.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(resolve=>socket.close(resolve));
 const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('FAMILY_'))delete env[k];
 // Seed a forgotten timer only inside demo.py's temporary directory. This Store
 // instance uses a prior clock; HTTP requests still use the real current clock.
 const launch=`import app, runpy, sys, datetime as dt, uuid
prepare=app.prepare_assets
def prepare_demo():
    store=app.study_store()
    prior=store._now()-dt.timedelta(days=5)
    store._now=lambda:prior
    base=dict(child_id='child-1',day=prior.date().isoformat(),version=0,request_key=str(uuid.uuid4()))
    result=store.save_item(dict(base,title='虚构忘停计时',planned_minutes=20))
    item=result['items'][0]
    store.action(dict(base,id=item['id'],version=item['version'],request_key=str(uuid.uuid4()),action='start'))
    prepare()
app.prepare_assets=prepare_demo
sys.argv=['demo.py','--port',sys.argv[1]]
runpy.run_path('demo.py',run_name='__main__')`;
 const child=spawn(process.env.FAMILY_TEST_PYTHON||'python3',['-c',launch,String(port)],{cwd:__dirname,env,stdio:['ignore','pipe','pipe']});let err='';child.stdout.resume();child.stderr.on('data',b=>err+=String(b));
 const url='http://127.0.0.1:'+port+'/',stop=async()=>{if(child.exitCode!==null||child.signalCode!==null)return;const end=once(child,'exit');child.kill('SIGINT');await Promise.race([end,delay(2500)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await end}};
 try{await eventually(async()=>{if(child.exitCode!==null)throw Error(err||'Demo exited');try{return(await fetch(url,{signal:AbortSignal.timeout(400)})).ok}catch{return false}},'synthetic server');return{url,stop}}catch(e){await stop();throw e}
}
async function fit(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'no horizontal overflow');assert.equal(await p.locator('.study-view button:visible').evaluateAll(xs=>xs.some(x=>x.getBoundingClientRect().height<44)),false,'44px touch buttons')}
async function proof(p,name){if(process.env.STUDY_UI_PROOF_DIR){const fs=require('node:fs/promises'),path=require('node:path');await fs.mkdir(process.env.STUDY_UI_PROOF_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.STUDY_UI_PROOF_DIR,name+'.png'),fullPage:false})}}
(async()=>{
 let app,browser;const results=[];
 try{
  app=await server();browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  const state=await(await fetch(app.url+'api/state')).json(),child=state.children[0],other=state.children[1];
  const read=async(who=child.id,day=state.today)=>await(await fetch(app.url+'api/study?'+new URLSearchParams({child_id:who,day}))).json();
  const post=async(path,body)=>{const r=await fetch(app.url+path,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Token':state.token},body:JSON.stringify(body)});const data=await r.json();assert.equal(r.ok,true,JSON.stringify(data));return data};
  for(const width of [360,1440]){
   const p=await browser.newPage({viewport:{width,height:900}}),errors=[];let beforeUnloadDialogs=0;p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async dialog=>{if(dialog.type()==='beforeunload')beforeUnloadDialogs++;await dialog.accept()});
   try{
    await p.goto(app.url);await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await fit(p);
    if(width===360){
     await p.locator('select[data-study-child]').selectOption(other.id);await eventually(async()=>await p.locator('select[data-study-child]').inputValue()===other.id,'switch study child');
     await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();
     assert.equal(await p.locator('select[data-study-child]').inputValue(),other.id,'main navigation preserves selected study child');
     await p.locator('select[data-study-child]').selectOption(child.id);await eventually(async()=>await p.locator('select[data-study-child]').inputValue()===child.id,'restore primary study child');await p.locator('[data-study-ready]').waitFor();
    }
    if(width===360){
     const ensureAdd=async()=>{await eventually(async()=>await p.locator('[data-study-ready]').count()===1,'study ready for draft');const details=p.locator('.study-add');if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();await eventually(async()=>await p.locator('[data-study-form="new"]').isVisible(),'new form visible')};
     await ensureAdd();const warningDraft=p.locator('[data-study-form="new"]');await warningDraft.locator('[name="title"]').fill('虚构离开前草稿');await p.reload();await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();assert.ok(beforeUnloadDialogs>=1,'cached draft warns before reload');await ensureAdd();const newDraft=p.locator('[data-study-form="new"]');
     await newDraft.locator('[name="title"]').fill('虚构跨页草稿 A');await newDraft.locator('[name="subject"]').fill('虚构数学');await newDraft.locator('[name="planned_minutes"]').fill('12');
     await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();
     assert.equal(await p.locator('select[data-study-child]').inputValue(),child.id);assert.equal(await p.locator('[data-study-date]').inputValue(),state.today);assert.equal(await newDraft.locator('[name="title"]').inputValue(),'虚构跨页草稿 A');assert.equal(await newDraft.locator('[name="subject"]').inputValue(),'虚构数学');assert.equal(await newDraft.locator('[name="planned_minutes"]').inputValue(),'12');
     await p.locator('select[data-study-child]').selectOption(other.id);await eventually(async()=>await p.locator('select[data-study-child]').inputValue()===other.id,'draft child isolation');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),'');assert.equal(await p.locator('[data-study-form="new"] [name="subject"]').inputValue(),'');
     await p.locator('[data-study-form="new"] [name="title"]').fill('虚构跨页草稿 B');await p.locator('[data-study-form="new"] [name="planned_minutes"]').fill('7');const priorDay=new Date(state.today+'T12:00:00Z');priorDay.setUTCDate(priorDay.getUTCDate()-1);await p.locator('[data-study-date]').fill(priorDay.toISOString().slice(0,10));await p.locator('[data-study-date]').dispatchEvent('change');await eventually(async()=>await p.locator('[data-study-date]').inputValue()===priorDay.toISOString().slice(0,10),'draft date isolation');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),'');
     await p.locator('[data-study-date]').fill(state.today);await p.locator('[data-study-date]').dispatchEvent('change');await eventually(async()=>await p.locator('[data-study-form="new"] [name="title"]').inputValue()==='虚构跨页草稿 B','restore child draft');await p.locator('select[data-study-child]').selectOption(child.id);await eventually(async()=>await p.locator('[data-study-form="new"] [name="title"]').inputValue()==='虚构跨页草稿 A','restore original draft');
     const sourceCandidate=(await read()).available_tasks[0];assert.ok(sourceCandidate,'synthetic source task available');await p.locator('nav [data-page="home"]').click();for(const details of await p.locator('.today-backlog').all())if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();await p.locator('[data-study-task-add="'+sourceCandidate.id+'"]').click();await p.locator('[data-study-ready]').waitFor();assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),'虚构跨页草稿 A','source entry preserves draft');assert.match(await p.locator('#studyStatus').innerText(),/保存|清空/,'source conflict explains next action');assert.equal(await p.locator('[data-study-form="new"] [name="task_id"]').inputValue(),'','source does not silently replace task selection');await p.locator('[data-study-discard-new]').click();await eventually(async()=>await p.locator('[data-study-form="new"] [name="task_id"]').inputValue()===sourceCandidate.id,'discard then applies queued source');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),sourceCandidate.title,'queued source owns title');await p.locator('[data-study-discard-new]').click();
     const retained='虚构保存时段仍保留的新稿';await p.locator('[data-study-form="new"] [name="title"]').fill(retained);await p.locator('[data-study-form="new"] [name="planned_minutes"]').fill('9');let settingsDraft=p.locator('.study-settings');await settingsDraft.locator('summary').click();await settingsDraft.locator('[name="start_time"]').fill('17:00');await settingsDraft.locator('[name="stop_time"]').fill('20:30');await settingsDraft.locator('[name="bed_time"]').fill('21:00');await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();settingsDraft=p.locator('.study-settings');if(!await settingsDraft.locator('form').isVisible())await settingsDraft.locator('summary').click();assert.equal(await settingsDraft.locator('[name="start_time"]').inputValue(),'17:00','schedule draft survives page switch');assert.equal(await settingsDraft.locator('[name="stop_time"]').inputValue(),'20:30');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),retained);await settingsDraft.locator('button').click();await eventually(async()=>(await read()).day.stop_time==='20:30','saving schedule');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),retained,'saving schedule keeps new draft');assert.equal(await p.locator('[data-study-form="new"] [name="planned_minutes"]').inputValue(),'9');await p.locator('[data-study-discard-new]').click();
    }
    if(width===360){
     const active=(await read()).active_item;assert.ok(active&&active.day<state.today,'forgotten timer is discoverable from today');
     assert.match(await p.locator('.study-active-gap').innerText(),/有一项较早的计时未结束/);await proof(p,'study-forgotten-'+width);await p.locator('.study-active-gap button').click();await eventually(async()=>await p.locator('[data-study-date]').inputValue()===active.day,'jump to forgotten timer date');
     const forgotten=p.locator('[data-study-item="'+active.id+'"]');await forgotten.locator('[data-study-action="pause"]').click();await eventually(async()=>(await read()).active_item===null,'pause old timer through real API');
     assert.equal((await read(child.id,active.day)).items[0].actual_minutes,null,'forgotten duration stays unknown');await forgotten.locator('[data-study-editor="manual"]').click();let manual=p.locator('[data-study-form="manual"]');await manual.locator('[name="actual_minutes"]').fill('18');await manual.locator('[type="submit"]').click();await eventually(async()=>(await read(child.id,active.day)).items[0].actual_minutes===18,'parent corrects forgotten duration');
     await p.locator('[data-study-date]').fill(state.today);await p.locator('[data-study-date]').dispatchEvent('change');await eventually(async()=>await p.locator('.study-active-gap').count()===0&&await p.locator('.study-item').count()===0,'today unblocked after correction');
    }
    const settings=p.locator('.study-settings');await settings.locator('summary').click();
    const time=settings.locator('form');await time.locator('[name="start_time"]').fill('16:30');await time.locator('[name="stop_time"]').fill('21:00');await time.locator('[name="bed_time"]').fill('21:30');await time.locator('button').click();
    await eventually(async()=>(await read()).day.stop_time==='21:00','night boundary saves');
    const add=p.locator('[data-study-form="new"]');if(!await add.isVisible())await p.locator('.study-add>summary').click();
    const title='虚构课后数学 '+width,requirement='虚构要求：读完第 3 页，再写两句自己的解释。\n保留自己的草稿。';
    const sourceTask=(await post('api/task/new',{child:child.name,title,due:'虚构下次课前',action:requirement})).task;
    const focusBody={id:sourceTask.id,version:0,mode:'next',next_action:'虚构下一步：先读第一题',waiting_for:'',review_on:'',request_key:crypto.randomUUID()};
    await post('api/task/focus',focusBody);await p.reload();await eventually(async()=>await p.locator('[data-study-task-add="'+sourceTask.id+'"]').count()===1,'school task opens study');for(const details of await p.locator('.today-backlog').all())if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();await p.locator('[data-study-task-add="'+sourceTask.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await eventually(async()=>await add.locator('[name="task_id"]').inputValue()===sourceTask.id,'task preselected from school card');assert.equal(await add.locator('[name="title"]').inputValue(),title,'task title prefilled');assert.equal(await add.locator('[name="title"]').getAttribute('readonly'),'','task title stays source-owned');assert.equal(await p.locator('.study-add').evaluate(el=>el.open),true,'task card expands add form');
    await add.locator('[name="subject"]').fill('数学');await add.locator('[name="planned_minutes"]').fill('25');
    const keys=[];let drop=true;
    const lost=async route=>{const body=route.request().postDataJSON();keys.push(body.request_key);if(drop){drop=false;const r=await route.fetch();assert.equal(r.ok(),true);await route.abort('failed')}else await route.continue()};
    await p.route('**/api/study/item',lost);await add.locator('[type="submit"]').click();await p.locator('[data-study-retry]').waitFor();
    assert.equal(await add.locator('[name="title"]').inputValue(),title,'lost response keeps entered text');
    if(width===360){
     await p.locator('nav [data-page="home"]').click();await p.locator('[data-study-child="'+other.id+'"]').click();await p.locator('[data-study-ready]').waitFor();
     assert.equal(await p.locator('select[data-study-child]').inputValue(),child.id,'pending save takes priority over another child entry');
     await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();
     assert.equal(await p.locator('select[data-study-child]').inputValue(),child.id,'pending restore keeps child ownership');assert.equal(await p.locator('[data-study-retry]').count(),1,'pending save remains actionable after remount');
    }
    await p.locator('[data-study-retry]').click();
    await eventually(async()=>await p.locator('.study-item h3').filter({hasText:title}).count()===1,'retry shows one saved item');await p.unroute('**/api/study/item',lost);assert.equal(keys.length,2);assert.equal(keys[0],keys[1],'same save request key on retry');let saved=(await read()).items.filter(x=>x.title===title);assert.equal(saved.length,1);const id=saved[0].id,item=p.locator('[data-study-item="'+id+'"]');
    if(width===360){
     const retainedWhileEditing='虚构编辑期间保留的新稿';await eventually(async()=>!await p.locator('[data-study-form="new"] [name="title"]').isDisabled(),'save lock released');if(!await add.isVisible())await p.locator('.study-add>summary').click();await add.locator('[name="title"]').fill(retainedWhileEditing);await add.locator('[name="planned_minutes"]').fill('8');await item.locator('[data-study-editor="item"]').click();let estimate=p.locator('[data-study-form="item"]');await estimate.locator('[name="planned_minutes"]').fill('26');await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();assert.equal(await p.locator('[data-study-form="item"] [name="planned_minutes"]').inputValue(),'26','estimate draft survives page switch');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),retainedWhileEditing,'saving another form does not clear new draft');await p.locator('[data-study-form="item"] [type="submit"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).planned_minutes===26,'estimate draft saves');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),retainedWhileEditing,'successful edit clears only its own form');await p.locator('[data-study-discard-new]').click();
     await item.locator('[data-study-editor="finish"]').click();let finishDraft=p.locator('[data-study-form="finish"]');await finishDraft.locator('[value="需要帮助"]').check();await finishDraft.locator('summary').click();await finishDraft.locator('[name="assistance"]').selectOption('少量提示');await finishDraft.locator('[name="note"]').fill('虚构跨页结果草稿');await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();assert.equal(await p.locator('[data-study-form="finish"] [value="需要帮助"]').isChecked(),true);assert.equal(await p.locator('[data-study-form="finish"] [name="note"]').inputValue(),'虚构跨页结果草稿','finish draft survives page switch');await p.locator('[data-study-form="finish"] [data-study-cancel]').click();
     await item.locator('[data-study-editor="manual"]').click();const manualDraft=p.locator('[data-study-form="manual"]');await manualDraft.locator('[name="actual_minutes"]').fill('19');await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();assert.equal(await p.locator('[data-study-form="manual"] [name="actual_minutes"]').inputValue(),'19','manual duration draft survives page switch');await p.locator('[data-study-form="manual"] [data-study-cancel]').click();assert.equal(await p.locator('[data-study-form="manual"]').count(),0,'cancel drops only the duration editor');
     if(!await add.isVisible())await p.locator('.study-add>summary').click();await add.locator('[name="title"]').fill('虚构动作期间保留的新稿');await item.locator('[data-study-editor="finish"]').click();await p.locator('[data-study-form="finish"] [value="需要帮助"]').check();await p.locator('[data-study-form="finish"] [data-study-cancel]').click();assert.equal(await p.locator('[data-study-form="finish"]').count(),0);assert.equal(await add.locator('[name="title"]').inputValue(),'虚构动作期间保留的新稿','cancel leaves new draft intact');await item.locator('[data-study-action="start"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).status==='running','start leaves new draft');assert.equal(await add.locator('[name="title"]').inputValue(),'虚构动作期间保留的新稿');await item.locator('[data-study-action="pause"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).status==='paused','pause leaves new draft');assert.equal(await add.locator('[name="title"]').inputValue(),'虚构动作期间保留的新稿');await p.locator('[data-study-discard-new]').click();
    }
    await p.locator('nav [data-page="home"]').click();await eventually(async()=>await p.locator('[data-study-task-add="'+sourceTask.id+'"]').count()===1,'same school task opens again');for(const details of await p.locator('.today-backlog').all())if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();await p.locator('[data-study-task-add="'+sourceTask.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await eventually(async()=>await p.locator('[data-study-item="'+id+'"]').evaluate(el=>document.activeElement===el),'existing task receives repeat open');assert.equal((await read()).items.filter(x=>x.task_id===sourceTask.id).length,1,'repeat open does not add duplicate');assert.equal(await p.locator('.study-add').evaluate(el=>el.open),false,'repeat open does not expand add form');
    const otherTitle='虚构另一孩子作业 '+width,otherTask=(await post('api/task/new',{child:other.name,title:otherTitle,due:'虚构另一孩子下次课前',action:'虚构另一孩子要求'})).task;await p.reload();await eventually(async()=>await p.locator('[data-study-task-add="'+otherTask.id+'"]').count()===1,'other child task opens study');for(const details of await p.locator('.today-backlog').all())if(!await details.evaluate(el=>el.open))await details.locator(':scope > summary').click();await p.locator('[data-study-task-add="'+otherTask.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await eventually(async()=>await p.locator('select[data-study-child]').inputValue()===other.id&&await p.locator('[data-study-form="new"] [name="task_id"]').inputValue()===otherTask.id,'other child task stays owned');assert.equal(await p.locator('[data-study-form="new"] [name="title"]').inputValue(),otherTitle,'other child title is isolated');assert.equal((await read(other.id)).items.length,0,'other child task is not auto-added');await p.locator('select[data-study-child]').selectOption(child.id);await eventually(async()=>await p.locator('[data-study-item="'+id+'"]').isVisible(),'return to original child after cross-child check');
    assert.match(await item.innerText(),/行动要求：虚构要求：读完第 3 页/);assert.match(await item.innerText(),/原截止：虚构下次课前/);
    assert.equal(await item.locator('.study-note').filter({hasText:'虚构下一步：先读第一题'}).isVisible(),true,'next action visible without expanding');
    assert.equal(await item.locator('.study-note').evaluateAll(xs=>xs.some(x=>x.closest('details'))),false,'requirements are outside collapsed details');
    const beforeSource=(await read()).items.find(x=>x.id===id);
    await post('api/task/focus',{...focusBody,version:1,next_action:'虚构下一步：圈出题目中的条件',request_key:crypto.randomUUID()});
    await p.locator('[data-study-refresh]').click();await eventually(async()=>/虚构下一步：圈出题目中的条件/.test(await item.innerText()),'current source action changes on read');
    const afterSource=(await read()).items.find(x=>x.id===id);assert.equal(afterSource.version,beforeSource.version);assert.equal(afterSource.elapsed_seconds,beforeSource.elapsed_seconds,'reading a new action never changes timer');
    const missingSource=async route=>{const response=await route.fetch(),body=await response.json();body.items=body.items.map(x=>x.id===id?{...x,source_task_action:null,source_task_due:null,source_task_next_action:null}:x);await route.fulfill({response,json:body})};
    await p.route('**/api/study?**',missingSource);await p.locator('[data-study-refresh]').click();await eventually(async()=>/原事项暂时无法核对/.test(await item.innerText()),'missing source is explicit');
    assert.equal(await item.locator('.study-note').count(),0,'missing source does not invent requirements');await p.unroute('**/api/study?**',missingSource);await p.locator('[data-study-refresh]').click();await eventually(async()=>/虚构下一步：圈出题目中的条件/.test(await item.innerText()),'source recovers on read');
    await item.getByRole('button',{name:'查看原事项',exact:true}).click();await p.locator('[data-query-target="task:'+sourceTask.id+'"]').waitFor();
    await p.locator('nav [data-page="home"]').click();await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await fit(p);await proof(p,'study-requirements-'+width);
    await item.locator('[data-study-action="start"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).status==='running','start timer');await item.locator('[data-study-clock]').waitFor();
    await p.reload();await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();await item.locator('[data-study-clock]').waitFor();
    await item.locator('[data-study-action="pause"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).status==='paused','pause restored timer');
    await item.locator('[data-study-editor="finish"]').click();let finish=p.locator('[data-study-form="finish"]');await finish.locator('[value="需要帮助"]').check();await finish.locator('[name="actual_minutes"]').fill('22');await finish.locator('summary').click();await finish.locator('[name="assistance"]').selectOption('少量提示');await finish.locator('[name="note"]').fill('虚构记录：最后一道题需要一起读题。');await fit(p);await proof(p,'study-feedback-'+width);await finish.locator('[type="submit"]').click();
    await eventually(async()=>(await read()).items.find(x=>x.id===id).result==='需要帮助','partial outcome saved');await item.locator('[data-study-action="start"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).status==='running','partial work resumes');
    await item.locator('[data-study-editor="finish"]').click();finish=p.locator('[data-study-form="finish"]');await finish.locator('[value="完成"]').check();await finish.locator('[name="actual_minutes"]').fill('30');await finish.locator('[type="submit"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).result==='完成','complete outcome saved');
    await item.locator('[data-study-editor="manual"]').click();const manual=p.locator('[data-study-form="manual"]');await manual.locator('[name="actual_minutes"]').fill('28');await manual.locator('[type="submit"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===id).actual_minutes===28,'manual correction saved');
    const recordID=(await read()).items.find(x=>x.id===id).record_id;await item.locator('[data-study-record]').click();
    const record=p.locator('[data-query-target="record:'+recordID+'"]');await record.locator('[data-record]').click();const recordForm=p.locator('#recordForm');await p.locator('#recordDialog').waitFor();
    assert.equal(await recordForm.locator('h2').innerText(),'给这次功课补充原件');assert.match(await p.locator('#studyRecordNotice').innerText(),/用时、结果和说明统一在“放学后”更正/);
    const owned=['child','day','category','subject','title','note','source','assistance'];for(const name of owned)assert.equal(await recordForm.locator('[name="'+name+'"]').isDisabled(),true,'study-owned field is locked: '+name);
    assert.equal(await recordForm.locator('#fileInput').isEnabled(),true,'original upload remains available');await proof(p,'study-originals-'+width);await recordForm.locator('[data-close="recordDialog"]').click();
    await p.locator('#add').click();await p.locator('#recordDialog').waitFor();assert.equal(await recordForm.locator('h2').innerText(),'记下一个成长瞬间');assert.equal(await p.locator('#studyRecordNotice').count(),0);for(const name of owned)assert.equal(await recordForm.locator('[name="'+name+'"]').isEnabled(),true,'ordinary capture unlocks field: '+name);await recordForm.locator('[name="title"]').fill('虚构普通观察草稿');await recordForm.locator('[data-close="recordDialog"]').click();
    await p.locator('nav [data-page="home"]').click();await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();
    // Concurrent estimate update must preserve the user's current edit on conflict.
    const more='虚构待安排 '+width;if(!await add.isVisible())await p.locator('.study-add>summary').click();await add.locator('[name="title"]').fill(more);await add.locator('[name="planned_minutes"]').fill('10');await add.locator('[type="submit"]').click();await eventually(async()=>(await read()).items.some(x=>x.title===more),'another item saved');
    const second=(await read()).items.find(x=>x.title===more),row=p.locator('[data-study-item="'+second.id+'"]');await row.locator('[data-study-editor="item"]').click();const edit=p.locator('[data-study-form="item"]');await edit.locator('[name="planned_minutes"]').fill('35');await p.locator('nav [data-page="calendar"]').click();await p.locator('nav [data-page="study"]').click();await p.locator('[data-study-ready]').waitFor();assert.equal(await p.locator('[data-study-form="item"] [name="planned_minutes"]').inputValue(),'35','estimate draft survives before version conflict');
    await post('api/study/item',{child_id:child.id,day:state.today,request_key:crypto.randomUUID(),id:second.id,version:second.version,planned_minutes:15,subject:''});await edit.locator('[type="submit"]').click();await eventually(async()=>/刷新状态/.test(await p.locator('#studyStatus').innerText()),'conflict visible');assert.equal(await edit.locator('[name="planned_minutes"]').inputValue(),'35');await p.locator('[data-study-refresh]').click();await eventually(async()=>await row.innerText().then(t=>t.includes('15 分钟')),'latest state refresh');assert.equal(await edit.locator('[name="planned_minutes"]').inputValue(),'35','refresh preserves conflicting edit');await edit.locator('[type="submit"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===second.id).planned_minutes===35,'revised estimate saves');
    if(width===360){
     await row.locator('[data-study-action="start"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===second.id).status==='running','timer starts before family decision');
     const started=(await read()).items.find(x=>x.id===second.id),beforeDecision=await(await fetch(app.url+'api/state')).json(),source=beforeDecision.tasks.find(t=>t.id===second.task_id);
     await post('api/task',{id:source.id,status:'不参加',note:'虚构家庭决定：这次不参加',expected_updated:source.update?.updated||''});
     await p.locator('[data-study-refresh]').click();await eventually(async()=>/原事项：不参加/.test(await row.innerText()),'study reads another parent dismissal');
     const held=(await read()).items.find(x=>x.id===second.id);assert.equal(held.status,'paused');assert.equal(held.running_since,null);assert.equal(held.source_task_status,'不参加');assert.ok(held.elapsed_seconds>=started.elapsed_seconds,'recorded time is preserved');assert.equal(held.time_source,started.time_source);
     assert.match(await row.innerText(),/已记用时保留/);assert.equal(await row.locator('[data-study-action="start"],[data-study-editor="finish"]').count(),0,'dismissed homework offers no start or finish');
     assert.equal((await read()).summary.unfinished_count,0,'dismissed item leaves tonight pending count');await fit(p);await proof(p,'study-dismissed-'+width);
     await row.locator('[data-study-task]').click();const sourceCard=p.locator('[data-query-target="task:'+source.id+'"]');await sourceCard.waitFor();
     assert.equal(await p.locator('[data-view="已搁置"]').getAttribute('aria-pressed'),'true');assert.match(await sourceCard.innerText(),new RegExp(child.name));assert.equal(await sourceCard.locator('[data-check]').count(),0,'decision opens matching dismissed task');
     await sourceCard.locator('[data-task-restore]').click();await eventually(async()=>!(await sourceCard.count()),'explicit restore from linked task');
     await p.locator('nav [data-page="home"]').click();await p.locator('[data-study-child="'+child.id+'"]').click();await p.locator('[data-study-ready]').waitFor();
     await row.locator('[data-study-action="start"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===second.id).status==='running','restored homework can continue');
     await row.locator('[data-study-action="pause"]').click();await eventually(async()=>(await read()).items.find(x=>x.id===second.id).status==='paused','restored timer can pause');
     const afterDecision=await(await fetch(app.url+'api/state')).json();assert.deepEqual(afterDecision.records,beforeDecision.records,'decision and restore create no learning result');assert.deepEqual(afterDecision.rewards,beforeDecision.rewards,'decision and restore award no energy');
    }
    await p.locator('[data-study-close]').click();await eventually(async()=>Boolean((await read()).day.closed_at),'close night');assert.ok((await read()).items.find(x=>x.id===id).record_id,'result links a learning record');
    const prior=new Date(state.today+'T12:00:00Z');prior.setUTCDate(prior.getUTCDate()-(width===360?1:2));const priorDay=prior.toISOString().slice(0,10);
    await p.locator('[data-study-date]').fill(priorDay);await p.locator('[data-study-date]').dispatchEvent('change');await eventually(async()=>await p.locator('.study-item').count()===0,'select historical day');
    assert.equal((await read(child.id,priorDay)).day.start_time,'','no invented schedule for another day');await add.locator('[name="title"]').fill('虚构历史作业 '+width);await add.locator('[type="submit"]').click();await eventually(async()=>(await read(child.id,priorDay)).items.length===1,'past task can be recorded');
    const past=p.locator('.study-item');assert.equal(await past.locator('[data-study-action="start"]').isDisabled(),true,'past day cannot start live timer');await past.locator('[data-study-editor="finish"]').click();finish=p.locator('[data-study-form="finish"]');await finish.locator('[value="做了一部分"]').check();await finish.locator('[type="submit"]').click();await eventually(async()=>(await read(child.id,priorDay)).items[0].result==='做了一部分','past result saves without inventing duration');assert.equal((await read(child.id,priorDay)).items[0].actual_minutes,null);
    await p.locator('[data-study-date]').fill(state.today);await p.locator('[data-study-date]').dispatchEvent('change');await eventually(async()=>await item.isVisible(),'return to today');
    await p.locator('select[data-study-child]').selectOption(other.id);await eventually(async()=>await p.locator('.study-item').count()===0,'other child isolated');assert.equal((await read(other.id)).items.length,0);
    await p.locator('select[data-study-child]').selectOption(child.id);await p.locator('.study-item').first().waitFor();await fit(p);await proof(p,'study-'+width);
    assert.deepEqual(errors,[]);results.push({width,visibleRequirements:true,currentSourceWithoutTimerChange:true,activeSourceJump:true,persistentTimer:true,resultAndCorrection:true,originalsFieldOwnership:true,ordinaryCaptureReset:true,exactRetry:true,conflictPreservesInput:true,dismissedTimerCrossPage:width===360,childIsolation:true,noOverflow:true,draftContexts:width===360,sourceDraftGuard:width===360,crossFormDrafts:width===360,beforeUnloadWarning:width===360?beforeUnloadDialogs>0:false});
   }finally{await p.close()}
  }
  console.log(JSON.stringify({passed:results.length,syntheticOnly:true,realPhone:false,checks:results},null,2));
 }finally{await browser?.close();await app?.stop()}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
